//! The content compile (ARCHITECTURE.md §6): parse, convert units, intern, check, emit.
//!
//! `build` is what `jane-data`'s build script and the `dev-data` loader both call, so the
//! compiled statics and a startup load cannot differ; `jane check` calls it without the emit.

pub mod ctx;
pub mod diag;
pub mod fraction;
pub mod lists;
pub mod source;
pub mod tables;

use std::path::Path;

use crate::emit::{Emit, PRELUDE};
use crate::model::Catalog;
use ctx::{Ctx, Ids, leak, leak_str};
use diag::Diagnostics;
use source::Source;

/// The result of a compile: the catalog, if there were no errors, and every diagnostic.
#[derive(Debug)]
pub struct Built {
    pub catalog: Option<&'static Catalog>,
    pub diag: Diagnostics,
}

/// Compile the data dir at `root`.
pub fn build(root: &Path) -> Built {
    let mut diag = Diagnostics::default();
    let src = Source::read(root, &mut diag);
    let mut built = build_source(&src);
    diag.errors.append(&mut built.diag.errors);
    diag.warnings.append(&mut built.diag.warnings);
    Built { catalog: if diag.is_ok() { built.catalog } else { None }, diag }
}

/// Compile an already-read source.
pub fn build_source(src: &Source) -> Built {
    let mut cx = Ctx::default();
    cx.ids = Ids::collect(src, &mut cx.diag);
    let combat = tables::combat::compile(src, &mut cx);
    let story = tables::story::compile(src, &mut cx);
    let county = tables::county::compile(src, &mut cx);
    let dungeons = tables::dungeons::compile(src, &mut cx);
    check_limits(&mut cx);

    let mut catalog = Catalog {
        content_hash: 0,
        names: leak(cx.names.strings().map(leak_str).collect()),
        texts: leak(cx.texts.strings().map(leak_str).collect()),
        sprites: leak(cx.sprites.strings().map(leak_str).collect()),
        lists: leak(cx.lists.drain(..).map(leak).collect()),
        conds: leak(cx.conds.drain(..).map(leak).collect()),
        name_lists: leak(cx.name_lists.drain(..).map(leak).collect()),
        combat,
        story,
        county,
        dungeons,
    };
    catalog.content_hash = content_hash(&catalog);
    let ok = cx.diag.is_ok();
    Built { catalog: ok.then(|| &*Box::leak(Box::new(catalog))), diag: cx.diag }
}

/// Every pool is indexed by a `u16`.
fn check_limits(cx: &mut Ctx) {
    let pools = [
        ("names", cx.names.len()),
        ("texts", cx.texts.len()),
        ("sprites", cx.sprites.len()),
        ("lists", cx.lists.len()),
        ("condition lists", cx.conds.len()),
        ("name lists", cx.name_lists.len()),
    ];
    for (what, n) in pools {
        cx.diag.need(u16::try_from(n).is_ok(), "catalog", format!("{n} {what}: more than a u16 can index"));
    }
}

/// xxh3 of the emitted catalog with the English left out: everything that changes behaviour.
pub fn content_hash(c: &Catalog) -> u64 {
    let behaviour = Catalog { content_hash: 0, texts: &[], ..*c };
    xxhash_rust::xxh3::xxh3_64(crate::emit::to_rust(&behaviour).as_bytes())
}

/// The Rust source of `pub static CATALOG`.
pub fn codegen(c: &Catalog) -> String {
    let mut out = String::with_capacity(1 << 22);
    out.push_str("// Generated by jane-schema from /data. Do not edit.\n");
    out.push_str(PRELUDE);
    out.push_str("\npub static CATALOG: Catalog = ");
    c.emit(&mut out);
    out.push_str(";\n");
    out
}
