// 16x16 inventory / spell / status icons. Same rules as every other sheet: one
// character per pixel, "." transparent, everything else looked up in the palette.
// Icons sit on a dark slot, so: 1px near-black outline, bright fills, light from
// the top-left. Families that differ only by colour (potions, keys, bars, meat,
// shields, enchanted blades) are one template grid run through recolour().

import type { Palette, SpriteSheet, SpriteSrc } from "@/art/types";
import { PAL } from "@/art/types";

/** Shared palette plus the few extra inks icons need. Template chars H L D M are never inks. */
const ICON_PAL: Palette = {
  ...PAL,
  a: "#f09080", // light red / raw flesh
  U: "#1c3470", // navy
  c: "#40d0c8", // cyan
  C: "#1c7c80", // teal
  j: "#48a090", // moss light
  d: "#2a7068", // moss
  J: "#184844", // moss dark
  h: "#f8b848", // honey
  O: "#a8501c", // burnt orange
  q: "#d8a8f0", // light purple
  f: "#fff4a8", // pale yellow / glow
  v: "#b0c840", // sickly green
  V: "#6c8424", // sickly green shade
  x: "#ead8a0", // old paper
  X: "#b89c5c", // old paper shade
  z: "#4a6a88", // dim glass
  Z: "#34506c", // dim glass shade
};

function icon(rows: string[]): SpriteSrc {
  return { w: 16, h: 16, ax: 0, ay: 0, palette: ICON_PAL, frames: { base: rows } };
}

/** Swap template characters for palette characters. Characters not in the map pass through. */
function recolour(template: string[], map: Record<string, string>): string[] {
  return template.map((row) => Array.from(row, (ch) => map[ch] ?? ch).join(""));
}

/** Lay `over` on top of `under`; "." in `over` lets `under` show through. */
function overlay(under: string[], over: string[]): string[] {
  return under.map((row, y) => Array.from(row, (ch, x) => (over[y][x] === "." ? ch : over[y][x])).join(""));
}

// ---------------------------------------------------------------- templates

// Round flask. H = liquid surface / shine, L = liquid, D = liquid shade.
const FLASK = [
  "......kkkk......",
  "......kTtk......",
  ".....kkttkk.....",
  ".....kwWWgk.....",
  "......kiwk......",
  "......kiwk......",
  ".....kkiwkk.....",
  "....kiiwiiik....",
  "...kiHHHHHHHk...",
  "..kiwHLLLLLLDk..",
  "..kHwLLLLLLLDk..",
  "..kHwLLLLLLDDk..",
  "..kHLLLLLLDDDk..",
  "...kLLLLLDDDk...",
  "....kkDDDDkk....",
  "......kkkk......",
];

// Slim straight-sided vial. Same H / L / D roles as the flask.
const VIAL = [
  "................",
  "......kkkk......",
  "......kTtk......",
  ".....kkttkk.....",
  ".....kwiigk.....",
  "......kiik......",
  ".....kkiikk.....",
  "....kiwiiiik....",
  "....kiwHHHHk....",
  "....kiwLLLDk....",
  "....kiwLLLDk....",
  "....kiLLLLDk....",
  "....kiLLLDDk....",
  "....kLLLDDDk....",
  ".....kkkkkk.....",
  "................",
];

// Key, bow top-left, bit bottom-right. H / L / D = metal light / mid / shade.
const KEY = [
  "..kkkkk.........",
  ".kHHHHLk........",
  "kHHLLLLLk.......",
  "kHLkkkLLk.......",
  "kHLk.kLLk.......",
  "kHLkkkLDk.......",
  "kLLLLLDDk.......",
  ".kLLLDDDDk......",
  "..kkkkkHLDk.....",
  "......kkHLDk....",
  ".....kLLLHLDk...",
  ".....kLLkkHLDk..",
  "......kkLLLHLDk.",
  ".......kLLkkHLDk",
  "........kk..kkkk",
  "................",
];

// Cast bar. H = top light, L = face, M = maker's stamp, D = shade.
const BAR = [
  "................",
  "................",
  "................",
  "....kkkkkkkk....",
  "...kHHHHHHHHk...",
  "..kHLLLLLLLLDk..",
  "..kkkkkkkkkkkk..",
  ".kHLLLLLLLLLLDk.",
  ".kHLLMMMMMMLLDk.",
  ".kHLMLLLLLLMLDk.",
  "kHLLLMMMMMMLLLDk",
  "kHLLLLLLLLLLLDDk",
  "kLDDDDDDDDDDDDDk",
  "kkkkkkkkkkkkkkkk",
  "................",
  "................",
];

// Smooth magic stone. H / L / D / M = glow core out to the dark rim.
const ORB = [
  "................",
  ".....kkkkkk.....",
  "....kHHHHLLk....",
  "...kHwHHLLLLk...",
  "..kHwHHLLLLLDk..",
  ".kHHHHLLLLLDDDk.",
  ".kHHHLLLLLLDDDk.",
  ".kHLLLLLLLDDDDk.",
  ".kLLLLLLLDDDDMk.",
  ".kLLLLLLDDDDMMk.",
  ".kLLLLDDDDDMMMk.",
  "..kLDDDDDDMMMk..",
  "...kDDDDMMMMk...",
  "....kMMMMMMk....",
  ".....kkkkkk.....",
  "................",
];

// Glow ticks around the light stone.
const ORB_RAYS = [
  "y......ff......y",
  ".y............y.",
  "................",
  "................",
  "................",
  "................",
  "................",
  "f..............f",
  "f..............f",
  "................",
  "................",
  "................",
  "................",
  "................",
  ".y............y.",
  "y......ff......y",
];

// Raw cut with the bone through it. H / L / D = flesh, M = fat streak.
const MEAT = [
  "............kk..",
  "...........kwwkk",
  "..........kkwwwk",
  ".......kkkwWkWk.",
  ".....kkHHLkWkk..",
  "....kHHwHLLkk...",
  "...kHHwHLLMLDk..",
  "...kHHHLLMLLDk..",
  "..kHLLLLMLLDDk..",
  "..kLLLLMLLLDDk..",
  "..kLLLLLLLDDk...",
  ".kkkLLLLDDDkk...",
  "kwWkkDDDkkk.....",
  "kwwWkkkk........",
  "kWkwk...........",
  ".k.kk...........",
];

const MEAT_DRIP = [
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "...........lk...",
  "..........kvk...",
  "......kvk..k....",
  ".......k........",
];

// Heater shield. H / L / D = face, M = emblem.
const SHIELD = [
  "................",
  ".kkkkkkkkkkkkkk.",
  ".kHLLLLLLLLLLDk.",
  ".kHLLLLMMLLLDDk.",
  ".kHLLLLMMLLLDDk.",
  ".kHLLMMMMMMLDDk.",
  ".kHLLMMMMMMLDDk.",
  ".kHLLLLMMLLLDDk.",
  ".kLLLLLMMLLDDDk.",
  "..kLLLLMMLLDDk..",
  "..kLLLLLLLDDDk..",
  "...kLLLLLDDDk...",
  "....kLLLDDDk....",
  ".....kLDDDk.....",
  "......kDDk......",
  ".......kk.......",
];

// Drawn blade, tip top-right. H / L / D = the enchanted edge.
const BLADE = [
  ".............kkk",
  "............kHLk",
  "...........kHLDk",
  "..........kHLDk.",
  ".........kHLDk..",
  "........kHLDk...",
  ".......kHLDk....",
  "..kk..kHLDk.....",
  ".kyykkHLDk......",
  ".kYyykLDk.......",
  "..kYyykkk.......",
  "..kTtYyyk.......",
  ".kTtkkYyyk......",
  "kyYk...kkk......",
  "kYYk............",
  ".kk.............",
];

const BLADE_FLAME = [
  ".....k..........",
  "....krk.........",
  "...krok.........",
  "..kroork........",
  "..kryyrk........",
  "..kryfrk........",
  "...kkkk.........",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

const BLADE_FROST = [
  "................",
  "..i.i.i.........",
  "...iii..........",
  "..iiwii.........",
  "...iii..........",
  "..i.i.i.........",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

// Fat droplet. H / L / D = liquid.
const DROP = [
  "................",
  ".......kk.......",
  "......kHLk......",
  "......kHLk......",
  ".....kHHLLk.....",
  ".....kHLLLk.....",
  "....kHHLLLLk....",
  "...kHHLLLLLDk...",
  "..kHHLLLLLLLDk..",
  "..kHwHLLLLLLDk..",
  "..kHwHLLLLLDDk..",
  "..kHHLLLLLLDDk..",
  "..kLLLLLLLDDDk..",
  "...kLLLLDDDDk...",
  "....kkDDDDkk....",
  "......kkkk......",
];

const DROP_SKULL = [
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "....kk....kk....",
  "....kkk..kkk....",
  ".....kk..kk.....",
  ".......kk.......",
  "................",
  ".....k.kk.k.....",
  "................",
  "................",
];

// Orb web on a dark pad so the strands read on any slot.
const WEB = [
  "....KKKwKKK.....",
  "...KWWWwWWWK....",
  "..wWKKKwKKKWw...",
  ".KWwKKKwKKKwWK..",
  "KWKKwKWwWKwKKWK.",
  "KWKKKwKwKwKKKWK.",
  "KWKKWKwwwKWKKWK.",
  "wwwwwwwwwwwwwww.",
  "KWKKWKwwwKWKKWK.",
  "KWKKKwKwKwKKKWK.",
  "KWKKwKWwWKwKKWK.",
  ".KWwKKKwKKKwWK..",
  "..wWKKKwKKKWw...",
  "...KWWWwWWWK....",
  "....KKKwKKK.....",
  "................",
];

// The thing that spun it, sitting on the hub.
const WEB_SPIDER = [
  "................",
  "................",
  "................",
  "................",
  "................",
  "....p.....p.....",
  ".....pqppp......",
  "......ppP.......",
  ".....prPrp......",
  "....p.....p.....",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

// ------------------------------------------------------------------ colours

const LIQUID = {
  red: { H: "a", L: "r", D: "R" },
  blue: { H: "b", L: "B", D: "U" },
  cyan: { H: "i", L: "c", D: "C" },
  green: { H: "l", L: "n", D: "N" },
  grey: { H: "W", L: "g", D: "G" },
  orange: { H: "h", L: "o", D: "O" },
  purple: { H: "q", L: "p", D: "P" },
  yellow: { H: "f", L: "y", D: "Y" },
  water: { H: "i", L: "b", D: "B" },
  none: { H: "z", L: "Z", D: "Z" },
};

const METAL = {
  blue: { H: "i", L: "b", D: "B" },
  brass: { H: "h", L: "Y", D: "T" },
  gold: { H: "f", L: "y", D: "Y" },
  green: { H: "l", L: "n", D: "N" },
  iron: { H: "w", L: "g", D: "G" },
  purple: { H: "q", L: "p", D: "P" },
};

// -------------------------------------------------------------------- icons

export const ICONS: SpriteSheet = {
  // ---- status badges

  fx_burning: icon([
    "........k.......",
    ".......krk......",
    ".......krrk.....",
    "......kroork....",
    ".....kroorrk.k..",
    "....krooorrkkrk.",
    "...krooyoorkrrk.",
    "..kroooyyoorrork",
    "..kroyyyyyooorrk",
    ".kroyyyfyyyoorrk",
    ".kroyyffffyyoork",
    ".kroyyfwwfyyoork",
    ".krooyfwwfyoork.",
    "..krooyffyoork..",
    "...kkrooookk....",
    ".....kkkkkk.....",
  ]),

  fx_chilled: icon([
    ".......k........",
    ".....kkwkk......",
    "...kkikikikk....",
    "..kbkkiiikkbk...",
    "..kkbkkikkbkk...",
    ".kikkbkikbkkik..",
    ".kkikkbwbkkikk..",
    "kwiiiiwwwiiiiwk.",
    ".kkikkbwbkkikk..",
    ".kikkbkikbkkik..",
    "..kkbkkikkbkk...",
    "..kbkkiiikkbk...",
    "...kkikikikk....",
    ".....kkwkk......",
    ".......k........",
    "................",
  ]),

  fx_critical: icon(
    recolour(
      [
        "kkk..........kkk",
        "kLHk........kHLk",
        "kDLHk......kHLDk",
        ".kDLHk....kHLDk.",
        "..kDLHk..kHLDk..",
        "...kDLHkkHLDk...",
        "....kDLkHLDk....",
        "..kk.kkHLDk.kk..",
        ".kyykkHLDkkkyyk.",
        ".kYyykLDkLkyyYk.",
        "..kYyykkkkyyYk..",
        "..kTtYyykyYtTk..",
        ".kTtkkYyykkktTk.",
        "kyYk..kkkk..kYyk",
        "kYYk........kYYk",
        ".kk..........kk.",
      ],
      { H: "w", L: "W", D: "g" },
    ),
  ),

  fx_firelash: icon(overlay(recolour(BLADE, { H: "f", L: "o", D: "r" }), BLADE_FLAME)),

  fx_lifesteal: icon([
    "................",
    "..kkkk....kkkk..",
    ".karrrk..krrrrk.",
    "kaawrrrkkrrrrrRk",
    "kawrrrrrrrrrrrRk",
    "karrrrrrrrrrrRRk",
    "krrrrrrrrrrrrRRk",
    ".krrrrrrrrrrRRk.",
    "..krrrrrrrrRRk..",
    "...krrrrrrRRk...",
    "....krrrRRRk....",
    ".....kkrRkk.....",
    "......kaRk......",
    ".....karrRk.....",
    ".....krrRRk.....",
    "......kkkk......",
  ]),

  fx_manashield: icon(recolour(SHIELD, { H: "i", L: "b", D: "B", M: "w" })),

  fx_poisoned: icon(overlay(recolour(DROP, { H: "f", L: "l", D: "n" }), DROP_SKULL)),

  fx_sparktongue: icon([
    "................",
    "........kkkkkk..",
    ".......kfyyyyk..",
    "......kfyyyyk...",
    ".....kfyyyyk....",
    "....kfyyyyk.....",
    "...kfyyyykkkk...",
    "..kfyyyyyyyyk...",
    "..kkkkkyyyyk....",
    "......kyyyk.....",
    ".....kyyYk......",
    "....kyyYk.......",
    "...kyyYk........",
    "..kyYYk.........",
    "..kYkk..........",
    "..kk............",
  ]),

  fx_stoneskin: icon(recolour(SHIELD, { H: "w", L: "g", D: "G", M: "K" })),

  fx_stranglethorn: icon([
    "......k.........",
    ".....kwk....k...",
    "..k..klkkkkkwk..",
    ".kwkklllnnnnk...",
    "..klllllnnnnnk..",
    "..kllllkknnnnkk.",
    ".kklllk..knnnnwk",
    ".kllnk....knnNk.",
    ".kllnk....knNNk.",
    "kwnnnnk..kNNNkk.",
    ".kknnnnkkNNNNk..",
    "..knnnnnNNNNNk..",
    "...knnnnNNNkkwk.",
    "..kwkkkkknkk.k..",
    "...k....kwk.....",
    ".........k......",
  ]),

  fx_stunned: icon([
    ".....kk.........",
    "....kyyk........",
    "....kfyk........",
    "kkkkyfyykkkk....",
    "kyyffffyyyYk....",
    ".kyyfwfyyYk..k..",
    "..kyfffyYk..kyk.",
    "..kyfyyyYk.kyfyk",
    ".kyyykkyyYkyfwfy",
    ".kyYk..kyYkkyfyk",
    ".kkkk...kkk.kyk.",
    "...kyk.......k..",
    "..kyfyk....y....",
    ".kyfwfyk..yfy...",
    "..kyfyk....y....",
    "...kyk..........",
  ]),

  fx_webbed: icon(overlay(WEB, WEB_SPIDER)),

  fx_winterbite: icon(overlay(recolour(BLADE, { H: "w", L: "i", D: "b" }), BLADE_FROST)),

  // ---- items

  item_apple: icon([
    "................",
    "........k.kkk...",
    ".......kTklllk..",
    "...kkkkkTknnk...",
    "..kaarrkkrrkk...",
    ".karrrrrrrrrrk..",
    ".kawrrrrrrrrRk..",
    "kaawrrrrrrrrRRk.",
    "karrrrrrrrrrRRk.",
    "krrrrrrrrrrrRRk.",
    "krrrrrrrrrrRRRk.",
    ".krrrrrrrrrRRk..",
    ".krrrrrrrrRRRk..",
    "..kRrrrRRRRRk...",
    "...kkRRkRRkk....",
    ".....kk.kk......",
  ]),

  item_coal: icon([
    "................",
    "................",
    ".....kkkk.......",
    "....kgWgGkkkk...",
    "...kgWgGKkGggk..",
    "..kGgGGKKkgWgGk.",
    ".kGGGGKKkGgGGKk.",
    ".kGKKKKkGGGGKKk.",
    "kgWgGKkkGGKKKKk.",
    "kgGGGKKkKKKKkKk.",
    "kGGKKKKKkKKKKKk.",
    ".kKKKkKKKKKKKk..",
    "..kkKKKKKKKkk...",
    "....kkkkkkk.....",
    "................",
    "................",
  ]),

  item_fire_stone: icon([
    "................",
    "......kkkk......",
    "....kkoorrkk....",
    "...koooyrrrRk...",
    "..kooooyrrrrRk..",
    ".kooyoyyfrrrRRk.",
    ".koooyffyrryRRk.",
    ".korryfwfyyrrRk.",
    ".krrryyffyrrRRk.",
    ".krRryrfyrrRRRk.",
    ".kRRrrryrrRRRRk.",
    "..kRRrryrRRRRk..",
    "...kRRRyRRRRk...",
    "....kkRRRRkk....",
    "......kkkk......",
    "................",
  ]),

  item_glass: icon([
    "................",
    "....kkkkkk......",
    "..kkyyyyyykk....",
    ".kyykkkkkkyyk...",
    ".kykziwizzkyk...",
    "kykziwizzzzkyk..",
    "kykiwizzzzzkyk..",
    "kykwizzzzzZkYk..",
    "kykizzzzzZZkYk..",
    "kykzzzzzZZikYk..",
    ".kykzzzZZikYk...",
    ".kyYkkkkkkYYkk..",
    "..kkYYYYYYkkttk.",
    "....kkkkkk.kTttk",
    "............kTtk",
    ".............kk.",
  ]),

  item_gold_bar: icon(recolour(BAR, { H: "f", L: "y", M: "h", D: "Y" })),

  item_gold_dust: icon([
    "................",
    "..f.......f.....",
    ".fwf.....fwf....",
    "..f...f...f.....",
    "......y.........",
    ".....kkkk.......",
    "....kfyyykk.....",
    "...kfyyfyyykk...",
    "..kyyfyyyyhyyk..",
    ".kyfyyyhyyyyfyk.",
    "kyyyhyyyfyyhyyyk",
    "kYyyyyhyyyyyyhYk",
    ".kkYYYYYYYYYYkk.",
    "...kkkkkkkkkk...",
    "................",
    "................",
  ]),

  item_grape: icon([
    "................",
    ".........kk.....",
    "........kTk.kk..",
    "........kTkknlk.",
    "..kkkkkkkTknnk..",
    ".kqppkqppkqppk..",
    ".kpppkpppkpppk..",
    ".kpPPkpPPkpPPk..",
    "..kkqppkqppkk...",
    "...kpppkpppk....",
    "...kpPPkpPPk....",
    "....kkqppkk.....",
    ".....kpppk......",
    ".....kpPPk......",
    "......kkk.......",
    "................",
  ]),

  item_herb_cap: icon([
    "................",
    ".....kkkkkk.....",
    "...kkwwwwwwkk...",
    "..kwwwwwiwwwWk..",
    ".kwwiwwwwwwwwWk.",
    ".kwwwwwwwiwwWWk.",
    "kwwwwwwwwwwwWWWk",
    "kwiwwwwwwwwWWWgk",
    "kWWWWWWWWWWWWggk",
    ".kkkkgGGGGgkkkk.",
    "....kWWWWWgk....",
    ".....kwWWgk.....",
    ".....kwWWgk.....",
    "....kwwWWWgk....",
    "....kkkkkkkk....",
    "................",
  ]),

  item_herb_lily: icon([
    "................",
    ".k...kkkk...k...",
    "khk.kfhhfk.khk..",
    "khhkkfhhfkkhhk..",
    ".khhhfhhfhhhk...",
    ".khhhhyyhhhhk...",
    "..kohhyryhhok...",
    "..koohhhhhook...",
    "...kooohhoook...",
    "....kkooookk....",
    "......knnk......",
    ".......knk..kk..",
    ".......knkklnk..",
    ".......knnnnk...",
    ".......knkkk....",
    "........k.......",
  ]),

  item_herb_moss: icon([
    "................",
    "...k....k.......",
    "..kjk.kkjk.kk...",
    "..kjdkkjjdkjdk..",
    ".kkjddkjdddjdkk.",
    ".kjjdjdjdjdJdjk.",
    ".kjdjJddjdjddJk.",
    "kjjdddjjdJdjdJJk",
    "kjdJdjdddjdjdJJk",
    "kddjdddjJddddJJk",
    ".kdJddjdddJdjJk.",
    ".kJJdddJJddJJJk.",
    "..kkJJJJJJJJkk..",
    "....kkkkkkkk....",
    "................",
    "................",
  ]),

  item_herb_nasturtium: icon([
    "................",
    ".....kkkkkk.....",
    "...kkhoRoohkk...",
    "..khooRroooohk..",
    ".khoooRrroooRrk.",
    ".koooorryrRRook.",
    ".kRRrryyyyroook.",
    ".koorRyyyyrrRRk.",
    ".koooryyrRooook.",
    ".khoRrrroRooook.",
    "..kRroooroRook..",
    "...kkooorookk...",
    ".....kkkknkk....",
    "........knk.....",
    ".......knk......",
    ".......kk.......",
  ]),

  item_herb_pansy: icon([
    "................",
    "...kkkk..kkkk...",
    "..kqppPkkqppPk..",
    ".kqpppppkpppppk.",
    ".kppppppppppPPk.",
    ".kpppppPPpppPPk.",
    "..kpPPPkkPPPPk..",
    ".kkkkyPkkPykkkk.",
    "kfyyyyPPPPyyyyYk",
    "kyyyyyPkkPyyyyYk",
    "kyyyyyyPPyyyyYYk",
    ".kyyyyyyyyyyYYk.",
    "..kkyyyyyyYYkk..",
    "....kkkkkkkk....",
    "................",
    "................",
  ]),

  item_herb_root: icon([
    "................",
    "......kk.kk.....",
    ".....knkknk.....",
    "....kkmtkTkk....",
    "...kmmttttTtk...",
    "..kmmtttTtttTk..",
    "..kmtTtttttTTk..",
    "..kmttTtTttTTk..",
    "...kmttttTTTk...",
    "...kmtTtttTkk...",
    "..kmttkkttTk....",
    ".kmtTk.kmtTkk...",
    ".ktTk..kttkTtk..",
    "kmTk..kmTk.kTTk.",
    "kTk...kTk...kTk.",
    ".k.....k.....k..",
  ]),

  item_herb_rose: icon([
    "................",
    ".....kkkkkk.....",
    "...kkwwwwwwkk...",
    "..kwwwggggwwWk..",
    ".kwwggwwwwgwwWk.",
    ".kwgwwwgggwgwWk.",
    ".kwgwwgwwwgwgWk.",
    ".kwgwgwwgwgwgWk.",
    ".kwgwwgggwwgWWk.",
    ".kWwgwwwwwgWWgk.",
    "knkWwgggggWWgknk",
    "knnkkWWWWWkknnNk",
    ".knnnkkkkknnnNk.",
    "..kkNNk..kNNkk..",
    "....kk....kk....",
    "................",
  ]),

  item_herb_snakeroot: icon([
    "...........kkkk.",
    "..........klllnk",
    ".........kllnnk.",
    "...kkkkkkknnkk..",
    "..kvllnnnnnk....",
    ".kvlnnkkkkk.....",
    ".klnnNk.........",
    ".klnnNkkkkk.....",
    "..knnnnnnnnkk...",
    "...kkkNnnlnnNk..",
    "......kkkklnNNk.",
    ".........klnnNk.",
    "...kkkkkkknnNNk.",
    "..kvllnnnnnNNk..",
    "..knnNNNNNNkk...",
    "...kkkkkkkk.....",
  ]),

  item_iron: icon(recolour(BAR, { H: "w", L: "g", M: "G", D: "G" })),

  item_key_blue: icon(recolour(KEY, METAL.blue)),
  item_key_brass: icon(recolour(KEY, METAL.brass)),
  item_key_gold: icon(recolour(KEY, METAL.gold)),
  item_key_green: icon(recolour(KEY, METAL.green)),
  item_key_iron: icon(recolour(KEY, METAL.iron)),
  item_key_purple: icon(recolour(KEY, METAL.purple)),

  item_letter: icon([
    "................",
    "................",
    "kkkkkkkkkkkkkkkk",
    "kXxxxxxxxxxxxxXk",
    "kxXxxxxxxxxxxXxk",
    "kxxXxxxxxxxxXxxk",
    "kxxxXxxxxxxXxxxk",
    "kxxxxXxkkxXxxxxk",
    "kxxxxxkrakxxxxxk",
    "kxxxxkrrrRkxxxxk",
    "kxxxXxkrRkxXxxxk",
    "kxxXxxxkkxxxXxxk",
    "kxXxxxxxxxxxxXxk",
    "kXXXXXXXXXXXXXXk",
    "kkkkkkkkkkkkkkkk",
    "................",
  ]),

  item_light_stone: icon(overlay(recolour(ORB, { H: "w", L: "f", D: "y", M: "Y" }), ORB_RAYS)),

  item_meat: icon(recolour(MEAT, { H: "a", L: "r", D: "R", M: "W" })),
  item_meat_green: icon(overlay(recolour(MEAT, { H: "v", L: "V", D: "N", M: "l" }), MEAT_DRIP)),

  item_potion_blue: icon(recolour(FLASK, LIQUID.blue)),
  item_potion_cyan: icon(recolour(FLASK, LIQUID.cyan)),
  item_potion_green: icon(recolour(FLASK, LIQUID.green)),
  item_potion_grey: icon(recolour(FLASK, LIQUID.grey)),
  item_potion_orange: icon(recolour(FLASK, LIQUID.orange)),
  item_potion_purple: icon(recolour(FLASK, LIQUID.purple)),
  item_potion_red: icon(recolour(FLASK, LIQUID.red)),
  item_potion_yellow: icon(recolour(FLASK, LIQUID.yellow)),

  item_present: icon([
    "................",
    "...kkk....kkk...",
    "..kyyykkkkyyyk..",
    "..kyYyykkyyYyk..",
    "...kkyyyyyykk...",
    ".kkkkkkyykkkkkk.",
    ".kaarrkyykrrrRk.",
    ".kkkkkkyykkkkkk.",
    "..karrkyykrrRk..",
    "..krrrkyykrrRk..",
    "..krrrkyykrrRk..",
    "..krrrkyYkrrRk..",
    "..krrrkyYkrRRk..",
    "..kRRRkYYkRRRk..",
    "..kkkkkkkkkkkk..",
    "................",
  ]),

  item_rock: icon([
    "................",
    "................",
    ".....kkkkkk.....",
    "...kkWWWggGkk...",
    "..kWWwWgggggGk..",
    ".kWwWggggkgggGk.",
    ".kWWgggggkggGGk.",
    "kWWgggkggGkgGGGk",
    "kWgggggkgggGGGGk",
    "kWggggggkgGGGGGk",
    "kgggGggggGGGGGKk",
    "kggGGGgGGGGGGKKk",
    ".kGGGGGGGGGKKKk.",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ]),

  item_stone: icon([
    "................",
    "................",
    "......kkkk......",
    ".....kWWggk.....",
    "....kWwggGGk....",
    "....kWgggGGk....",
    "..kkkkgGGGkkkk..",
    ".kWWggkkkkWWggk.",
    "kWwgggGkkWwgggGk",
    "kWggggGkkWgggGGk",
    "kgggGGGkkggGGGGk",
    ".kGGGGk..kGGGGk.",
    "..kkkk....kkkk..",
    "................",
    "................",
    "................",
  ]),

  item_vial_empty: icon(recolour(VIAL, LIQUID.none)),
  item_vial_water: icon(recolour(VIAL, LIQUID.water)),

  item_wood: icon([
    "................",
    "................",
    ".kkkkkkkkkkkkk..",
    "kmmmmmmmmmmmmtk.",
    "kmttTtttttTttTk.",
    "ktttttTTtttttTk.",
    "kTTTTTTTTTTTTTk.",
    ".kkkkkkkkkkkkkk.",
    "..kmmmmmmmmmmmtk",
    "..kmtttTTttttTTk",
    "..ktTtttttTTttTk",
    "..kTTTTTTTTTTTTk",
    "...kkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ]),

  // ---- spells

  spell_fire: icon([
    "................",
    ".......kkkkkk...",
    ".....kkrooorrk..",
    "....kroyyyyoork.",
    "...kroyyffyyyork",
    "..kroyyfwwfyyork",
    "..kroyffwwfyyork",
    ".kroyyyfffyyork.",
    ".krooyyyyyyoork.",
    ".krkrooyyyoorkk.",
    "krk.krooooorrk..",
    "kk.krrkrrrrkk...",
    "..krkk.kkkk.....",
    ".krk............",
    ".kk.............",
    "................",
  ]),

  spell_frost: icon([
    "................",
    "............kkk.",
    "..........kkwik.",
    ".........kwwibk.",
    "........kwiibk..",
    ".......kwiibbk..",
    "..k...kwiibbk...",
    ".kik.kwiibbBk...",
    "..k.kwiibbBk....",
    "...kwiibbBk.....",
    "..kwiibbBBk..k..",
    "..kiibbBBk..kik.",
    ".kiibBBkk....k..",
    ".kbBBkk.........",
    ".kkkk...........",
    "................",
  ]),

  spell_melee: icon([
    "...kkkkkkkkk....",
    ".kkwwwwwwwwwkk..",
    "kwwwkkkkkkwwwwk.",
    ".kkk......kkwwwk",
    ".kk.kk.kk.kk.kwk",
    "kssksskssksskkwk",
    "kssksskssksskkWk",
    "kssksskssksskkWk",
    "ksssssssssssSkk.",
    "kkkkkkkkssssSk..",
    "ksssssssSksSSk..",
    "kssssssSSksSSk..",
    ".kkkkkkkkSSSk...",
    "..kSSSSSSSSk....",
    "...kkkkkkkk.....",
    "................",
  ]),

  spell_nature: icon(recolour(DROP, { H: "l", L: "n", D: "N" })),

  spell_repair: icon([
    "................",
    "....kkk.........",
    "...kgggk........",
    "..kgWggGk.......",
    ".kgWggGGkk......",
    "kgWggGGktTk.....",
    "kggGGGkkmtTk....",
    ".kGGGk..kmtTk...",
    "..kkk....kmtTk..",
    "..........kmtTk.",
    "kkkkkkkkkkkkmtTk",
    "kmmmmmmmmmmmkmtk",
    "kmtttTttttTttkkk",
    "ktttttttTtttttTk",
    "kkkkkkkkkkkkkkkk",
    "................",
  ]),

  spell_web: icon(WEB),
};
