import type { Palette, SpriteSheet, SpriteSrc } from "@/art/types";
import { PAL } from "@/art/types";

// Prop sprites. Width is always footprint w*8; tall props rise UP out of their
// footprint, so ay = spriteHeight - footprintH*8. Top-down 3/4: you see the top
// face and the front face, light from the top-left, 1px dark outline.

/** Shared palette plus the handful of extra tones props need. */
const PX: Palette = {
  ...PAL,
  x: "#0c0a12", // void: inside of mouths, chests, windows
  d: "#3a3e4a", // darkest stone / cold iron
  h: "#fff4b0", // flame / lamp core
  q: "#5a3a18", // dim warm glow on black
  z: "#1a2a58", // deep blue glow
  u: "#b0603a", // rust
  U: "#70382a", // dark rust
  c: "#6fa8a0", // sun-faded teal car paint
  C: "#47756f", // teal shade
  v: "#2c2018", // darkest root
  // PAL jumps straight from l to n, which is too big a step to round a canopy off with.
  f: "#5aa84e", // leaf, lit body
  F: "#2a6838", // leaf, shade
  j: "#e0685c", // wool, lit: PAL has no red above r, and a blanket needs one
  // Contact shadow. Translucent, so a plant sits on grass, dirt or cobble without
  // carrying a black bar around with it.
  "-": "#00000030",
  "=": "#00000050",
};

/** footH is the footprint height in 8 px cells. */
function prop(w: number, h: number, footH: number, frames: Record<string, string[]>): SpriteSrc {
  return { w, h, ax: 0, ay: h - footH * 8, palette: PX, frames };
}

/** Same drawing with some palette characters swapped (spent orb, picked tree). */
function swap(rows: string[], map: Record<string, string>): string[] {
  return rows.map((r) => Array.from(r, (ch) => map[ch] ?? ch).join(""));
}

const ORB_ICE = [
  ".....kkkkkk.....",
  "...kkiiiiiikk...",
  "..kiiwwiiiiibk..",
  ".kiiwwiiiiiibbk.",
  ".kiiwiiiiiibbbk.",
  "kiiiiiiiiiibbbBk",
  "kiiiiiiiiibbbbBk",
  ".kiiiiiibbbbbBk.",
  ".kibbbbbbbbBBBk.",
  "..kbbbbbbBBBBk..",
  "...kkBBBBBBkk...",
  ".....kkkkkk.....",
  "....kgggggGk....",
  ".....kgggGk.....",
  "......kgGk......",
  "......kgGk......",
  ".....kkgGkk.....",
  "...kkggggGGkk...",
  "..kgggggggGGGk..",
  "..kkkkkkkkkkkk..",
];

// A lumpy canopy, not a lollipop: the silhouette steps in and out, the light runs from
// the top-left corner down to the bottom-right, and the three apples are spread unevenly
// so the eye finds them one at a time. The trunk flares into a root and casts a shadow.
const APPLE_TREE = [
  "......kkkk......",
  "....kkllllkk....",
  "..kkllllllffk...",
  ".kllllllfflffk..",
  "klllllfflrrffnk.",
  "kllllffflRRfnnk.",
  "klllfffffffnnnNk",
  "kllffffffnnnnFNk",
  "kffffnnnnnnnFNk.",
  "kfffnnrrnnnFFNk.",
  "kkfnnnRRnnFFFNkk",
  ".knnnnnnnnFFFFNk",
  ".knnnnnnFFFFFFNk",
  "kknnnnFFFFFFFNk.",
  "kNnnnFFrrFFFNk..",
  ".kNNnFFRRFFNk...",
  "..kkNNFFFNkk....",
  "....kkNNNk......",
  "......ktTk......",
  "......ktTk......",
  ".....kmtTk......",
  ".....kmtTk......",
  ".....kmttTk.....",
  "....kmmttTTk....",
  "...kmmtttTTTk...",
  "..kmttttttTTTk..",
  "..kkeeeeeeeekk..",
  "...===========..",
];

const CAR_WRECK = [
  ".................l......................",
  "...............nln......l...............",
  "..............kkkkkkkkkkkkkk............",
  "............kkccccccccccccuukk..........",
  "...........kccccccccccccuuuuUck.........",
  "...........kcccnccccccccuuuUUck.........",
  "...........kccnlnccccccccuUUcck.........",
  "...........kCCnNCCCCCCCCCCCCCCk.........",
  "..........kkkknkkkkkkkkkkkkkkkkk....kk..",
  "..kkkkkkkkkcckKnxxxkCkxxxxKxkcckkkkkkcck",
  ".kcccccuuckckxKnlxxkCkxxxKxxxkckccnuucck",
  "kcccccuUcckkxxxxnxxkCkxxKxxxxxkkcclnUcck",
  "kccccuuUUckkkkknkkkkkkkkkkkkkkkkcuunUcck",
  "kWWWWWWWWWWkxxxxxxxkccCkWWWWWWWWWWWnWWWk",
  "kWCCCCUUCCCkxxRRRRxkccCkCCCCCCCUUUnlCCrk",
  "kgCCCUUUUCCkxxRRRRxkccCkCCCCCCUUUUNCCCRk",
  "kWgCCUUUCCCkxxkkkkxxkccCkCCCCCCUUCCCCgWk",
  "kWCkkkkkCCCkxxxxxxxxkccCkCCCCCkkkkkCCCWk",
  "kgkKWWWKkUCkxxxxxxxxkccCkCUUCkKWWWKkCUgk",
  "kUkWggGWkUUkUUUUUUUUUkcCCkUUUkWggGWkUUUk",
  ".kkWgWGWkkkkkkkkkkkkkkcCCkkkkkWgWGWkkkk.",
  "..kWGGGWkKKKKKKKKKKKKkcCCkKKKkWGGGWk....",
  "..kKWWWKkKKKKKKKKKKKKKkCUUkKKkKWWWKk....",
  "...kkkkk..............kUUUk...kkkkk.....",
  "...n..................kkkkk.....l.......",
  "..nl.l..........................n.ln....",
];

export const PROP_SPRITES: SpriteSheet = {
  door: prop(16, 20, 2, {
    base: [
      "..kkkkkkkkkkkk..",
      ".kmmmmmmmmmmmmk.",
      "kmttttttttttttTk",
      "kmtkkkkkkkkkktTk",
      "kmtkmttTmttTktTk",
      "kmtkmtkkkktTktTk",
      "kmtkmtkibktTktTk",
      "kmtkmtkbBktTktTk",
      "kmtkmtkkkktTktTk",
      "kmtkmttTmttTktTk",
      "kmtkTTTTTTTTktTk",
      "kmtkmttTmttTktTk",
      "kmtkmttTmyyTktTk",
      "kmtkmttTmYYTktTk",
      "kmtkmttTmttTktTk",
      "kmtkmttTmttTktTk",
      "kmtkTTTTTTTTktTk",
      "kmtkmttTmttTktTk",
      "kmtkeeeeeeeektTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  mine_mouth: prop(24, 24, 2, {
    base: [
      "......kkkkkkkkkkkk......",
      "...kkkggWgggggWggGkkk...",
      ".kkgGgggggGggggggGgggkk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kttTtttttTtttttTtttttTtk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmttTkxxxxxxGxxxxxkmttTk",
      "kmttTkxxxxqkkkqxxxkmttTk",
      "kmttTkxxxqkyhykqxxkmttTk",
      "kmttTkxxxqkohokqxxkmttTk",
      "kmttTkxxxxqkkkqxxxkmttTk",
      "kmttTkxxxxxqqqxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxKKGKKKKGKKxkmttTk",
      "kmttTkKeeGeeeeGeeKkmttTk",
      "kmttTkeTTGTTTTGTTekmttTk",
      "kkkkkkeeeGeeeeGeeekkkkkk",
    ],
  }),

  burial_mouth: prop(24, 24, 2, {
    base: [
      ".kkkkkkkkkkkkkkkkkkkkkk.",
      "kWWWWWWWWWWWWWWWWWWWWWWk",
      "kWgNNggggNNggggNNgggNygk",
      "kWNggNggNggNggNggNggNNgk",
      "kWggggNNggggNNggggNNgggk",
      "kggggggggggggggggggggggk",
      "kGGGGGGGGGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kWggGkxxxxxxxxxxxxkWggGk",
      "kWggGkxxxzzzzzzxxxkWggGk",
      "kWggGkxxzzBBBBzzxxkWggGk",
      "kWggGkxzzBBbbBBzzxkWggGk",
      "kWggGkxzzBBbbBBzzxkWggGk",
      "kWggGkzzzzBBBBzzzzkWggGk",
      "kWggGkddddddddddddkWggGk",
      "kWggGkkkkkkkkkkkkkkWggGk",
      "kWggGkGGGGGGGGGGGGkWggGk",
      "kWggGkGGGGGGGGGGGGkWggGk",
      "kWggGkkkkkkkkkkkkkkWggGk",
      "kWggGkggggggggggggkWggGk",
      "kWggGkggggggggggggkWggGk",
      "kWggGkkkkkkkkkkkkkkWggGk",
      "kWggGkWWWWWWWWWWWWkWggGk",
      "kkkkkkggggggggggggkkkkkk",
    ],
  }),

  hatch: prop(16, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kTTGGTTTTTTGGTTk",
      "kTmGGmmmmmmGGmTk",
      "kTttttttttttttTk",
      "kTttttttttttttTk",
      "kTeeeeeeeeeeeeTk",
      "kTmmmmmggmmmmmTk",
      "kTttttgttgttttTk",
      "kTttttGttGttttTk",
      "kTeeeeeGGeeeeeTk",
      "kTmmmmmmmmmmmmTk",
      "kTttttttttttttTk",
      "kTttttttttttttTk",
      "kTeeeeeeeeeeeeTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  stairs: prop(16, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kGwwwwwwwwwwwwGk",
      "kGWWWWWWWWWWWWGk",
      "kGddddddddddddGk",
      "kGWWWWWWWWWWWWGk",
      "kGWWWWWgWWWWWWGk",
      "kGddddddddddddGk",
      "kGWWWWWWWWWWWWGk",
      "kGWgWWWWWWWWWgGk",
      "kGddddddddddddGk",
      "kGWWWWWWWWWgWWGk",
      "kGggggggggggggGk",
      "kGddddddddddddGk",
      "kGggggggggggggGk",
      "kGggggggggggggGk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  gate_h: prop(24, 16, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kgggggggggggggggggggggGk",
      "kGGGGGGGGGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kgk.kgk.kgk..kgk.kgk.kgk",
      "kgk.kgk.kgk..kgk.kgk.kgk",
      "kgk.kgk.kkkkkkkk.kgk.kgk",
      "kgk.kgk.kYyyyyYk.kgk.kgk",
      "kgk.kgk.kyykkyyk.kgk.kgk",
      "kgk.kgk.kyykkyyk.kgk.kgk",
      "kgk.kgk.kYyyyyYk.kgk.kgk",
      "kgk.kgk.kkkkkkkk.kgk.kgk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kGGGGGGGGGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      ".k...k...k....k...k...k.",
    ],
  }),

  gate_v: prop(8, 28, 3, {
    base: [
      ".kkkkkk.",
      "kggggggk",
      "kgGGGGGk",
      ".kkkkkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      ".kkkkkk.",
      ".kYyyYk.",
      ".kykkyk.",
      ".kYyyYk.",
      ".kkkkkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      "..kkkk..",
    ],
  }),

  chest: prop(16, 16, 2, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kmmgGmmmmmmgGmmk",
      "kmtgGttttttgGttk",
      "kttgGttttttgGttk",
      "kttgGttttttgGttk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      "kttgGttkkttgGttk",
      "kttgGtkyYktgGttk",
      "kttgGtkYYktgGttk",
      "kttgGttkkttgGttk",
      "kttgGttttttgGttk",
      "kTTgGTTTTTTgGTTk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
    open: [
      ".kkkkkkkkkkkkkk.",
      "kTTgGTTTTTTgGTTk",
      "kTegGeeeeeegGeTk",
      "kTegGeeeeeegGeTk",
      "kTegGeeeeeegGeTk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      "kmxxxxxxxxxxxxmk",
      "kmxxxxxxxxxxxxmk",
      "kmKKKKKKKKKKKKmk",
      "kkkkkkkkkkkkkkkk",
      "kttgGttkkttgGttk",
      "kttgGttttttgGttk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
  }),

  boss_chest: prop(16, 18, 2, {
    base: [
      "..kkkkkkkkkkkk..",
      ".kyyyyyyyyyyyyk.",
      "kyrryYrrrryYrryk",
      "kyrryYrrrryYrryk",
      "kYrRyYRRRRyYRrYk",
      "kYRRyYRRRRyYRRYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      "kyyyyyykkyyyyyyk",
      "kyrryYkibkyYrryk",
      "kyrryYkbBkyYrryk",
      "kyrryYrkkryYrryk",
      "kyrryYrrrryYrryk",
      "kYRRyYRRRRyYRRYk",
      "kYRRyYRRRRyYRRYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
    open: [
      "..kkkkkkkkkkkk..",
      ".kYYYYYYYYYYYYk.",
      "kYPPPPPPPPPPPPYk",
      "kYPpPPPPPPPPpPYk",
      "kYPPPPPPPPPPPPYk",
      "kYPPPPPPPPPPPPYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      "kyxxxxxxxxxxxxyk",
      "kyxxxxxxxxxxxxyk",
      "kyPPPPPPPPPPPPyk",
      "kkkkkkkkkkkkkkkk",
      "kyrryYrrrryYrryk",
      "kYRRyYRRRRyYRRYk",
      "kYRRyYRRRRyYRRYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
  }),

  // It was one flat tan square with a brace drawn on it. Now the lid catches the light,
  // the left plank is the lit side, and the brace is cut into the wood rather than
  // painted over it.
  crate: prop(16, 18, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmtk",
      "kmttttttttttttTk",
      "kmtmmmmmmmmmttTk",
      "kmttttttttttttTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "kmttttttttttttTk",
      "kmtTTttttttTTtTk",
      "kmttTTttttTTttTk",
      "kmtttTTttTTtttTk",
      "kmttttTTTTttttTk",
      "kmttttTTTTttttTk",
      "kmtttTTttTTtttTk",
      "kmttTTttttTTttTk",
      "kmtTTttttttTTtTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  barrel: prop(16, 18, 2, {
    base: [
      "....kkkkkkkk....",
      "..kkmmtmmtmmkk..",
      ".kmmmmtmmtmmmtk.",
      ".kmmmmtmmtmmmtk.",
      ".kkkmmtmmtmtkkk.",
      ".kmtkkkkkkkkTTk.",
      "kggGGGGGGGGGGGGk",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kggGGGGGGGGGGGGk",
      "kmmtTtttTtttTTek",
      ".kmtTtttTtttTTk.",
      "..kkkkkkkkkkkk..",
      "...KKKKKKKKKK...",
    ],
  }),

  rock: prop(8, 8, 1, {
    base: [
      "........",
      "..kkkk..",
      ".kWWggk.",
      "kWWgggGk",
      "kggggGGk",
      "kgGGGGGk",
      ".kkkkkk.",
      ".------.",
    ],
  }),

  bench: prop(24, 20, 2, {
    base: [
      "........................",
      "........................",
      "...TT...................",
      "..kllk.............kkk..",
      "..klnk.........W...kik..",
      "kkklnkkTkkkkkkWkkkkkikkk",
      "kmklnkkrkmmkkWkkkmkibbkk",
      "kmknNkkrkmmkWGGgkmkibBkk",
      "kmkkkkkRkmmkgggGkmkbBBkk",
      "ktttttkkktttkgGktttkkktk",
      "kmmmmmmmmmmmkkkkmmmmmmmk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kttttttttttttttttttttttk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktttttttttttttttttttttTk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktTkKKKKKKKKKKKKKKKKktTk",
      "ktTk................ktTk",
      "kkkk................kkkk",
    ],
  }),

  table: prop(24, 18, 2, {
    base: [
      ".kkkkkkkkkkkkkkkkkkkkkk.",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kttttttttttttttttttttttk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kmmmmmmmtmmmmmmmmmmmmmmk",
      "kttttttttttttttttttttttk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kmmmmmmmmmmmmmmmtmmmmmmk",
      "kttttttttttttttttttttttk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kttttttttttttttttttttttk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktTkKKKKKKKKKKKKKKKKktTk",
      "ktTk................ktTk",
      "ktTk................ktTk",
      "kkkk................kkkk",
    ],
  }),

  // The lost-property desk at the Halt: the table, with the book open on it, a pen, and a bell nobody answers.
  // Before this the quest's giver was a bare table with a label, and read as furniture, not as a thing to read.
  lost_property_desk: prop(24, 18, 2, {
    base: [
      ".kkkkkkkkkkkkkkkkkkkkkk.",
      "kmmmkkkkkkkkkkkkmmmmmmmk",
      "kmmkwwwwwkwwwwwwkmmkkkmk",
      "kttkwGGGwkwGGGGwktkyYYkk",
      "kmmkwwwwwkwwwwwwkmkyyyYk",
      "kmmkwGGwwkwGGGwwkmmkkkmk",
      "kttkwwwwwkwwwwwwkttttttk",
      "kmmkwGGGwkwGGwwwkmmmdmmk",
      "kmmmkkkkkkkkkkkkmmmdmmmk",
      "kttttttttttttttttttttttk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kttttttttttttttttttttttk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktTkKKKKKKKKKKKKKKKKktTk",
      "ktTk................ktTk",
      "ktTk................ktTk",
      "kkkk................kkkk",
    ],
  }),

  shelf: prop(24, 18, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kteeeeeeeeeeeeeeeeeeeeTk",
      "ktrReenNepPeeeeeeeeeeeTk",
      "ktrRbBnNWpPeeeeTTeeeeeTk",
      "ktyybBnNWpPYeekiikeeeeTk",
      "ktrRbBnNWpPYeeklnkeYYYTk",
      "ktrRbBnNWpPYeeklnkerrRTk",
      "ktrRbBnNWpPYeekkkkebbBTk",
      "ktmmmmmmmmmmmmmmmmmmmmTk",
      "kteeeeeeeeeeeeeeeeeeeeTk",
      "kteeTTeeeeeTTeeeeeeeeeTk",
      "ktekiikeeekiikeekkkkkeTk",
      "ktekrrkeeekyykeekmmmkeTk",
      "ktekrRkeeekyYkeektytkeTk",
      "ktekkkkeeekkkkeekkkkkeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  // A bed to rest in, not a picnic blanket. The quilt was a red and blue chequerboard
  // that read as bunting; it is now banded wool, lit at the pillow end and in shadow at
  // the foot, with the top sheet turned down over it.
  bed: prop(16, 26, 3, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kmmmmmmmmmmmmmmk",
      "kmttttttttttttTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "kTkwwwwwwwwwwkTk",
      "ktkwwwwwwwwWWkTk",
      "ktkwwwwwwwWWWkTk",
      "ktkWWWWWWWWWWkTk",
      "ktkkkkkkkkkkkkTk",
      "ktwwwwwwwwwwwwTk",
      "ktWWWWWWWWWWWWTk",
      "ktkkkkkkkkkkkkTk",
      "ktjjjjjjjjjjrRTk",
      "ktjjjjjrrrrrrRTk",
      "ktWWWWWWWWWWWRTk",
      "ktrjjrrrrrrrrRTk",
      "ktrrrrrrrrrrrRTk",
      "ktWWWWWWWWWWWRTk",
      "ktrrrrrrrrrrRRTk",
      "ktRrrrrrrrrRRRTk",
      "ktRRRRRRRRRRRRTk",
      "kkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  stove: prop(16, 20, 2, {
    base: [
      ".....kkkk.......",
      ".....kgGk.......",
      ".....kgGk.......",
      ".kkkkkgGkkkkkkk.",
      "kggggkgGkggggggk",
      "kgGkkkGGGGkkkGGk",
      "kgkGGGkGGkGGGkGk",
      "kgGkkkGGGGkkkGGk",
      "kkkkkkkkkkkkkkkk",
      "kgGGGGGGGGGGGGGk",
      "kgkkkkkkkkkkkkGk",
      "kgkoyykoyykoykGk",
      "kgkyhykyhhkyhkGk",
      "kgkoyykoyykoykGk",
      "kgkrookrookrokGk",
      "kgkkkkkkkkkkkkGk",
      "kgGGGGGGGGGGGGGk",
      "kGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkk",
      ".kk..........kk.",
    ],
  }),

  fruit_bowl: prop(16, 12, 1, {
    base: [
      "......T...T.....",
      ".....kkk.kkk....",
      "....krwrkrwrk...",
      "kkkkkrrrRrrRkkkk",
      "kmkWWWWWWWWWgkmk",
      "kmmkbbbbbbbbkmmk",
      "kmmmkWWWWWgkmmmk",
      "kttttkkkkkkttttk",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "ktk..........ktk",
    ],
    open: [
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kmkgGGGGGGGGgkmk",
      "kmmkbbbbbbbbkmmk",
      "kmmmkWWWWWgkmmmk",
      "kttttkkkkkkttttk",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "ktk..........ktk",
    ],
  }),

  orb_ice: prop(16, 20, 2, {
    base: ORB_ICE,
    on: swap(ORB_ICE.slice(0, 11), { i: "g", w: "W", b: "G", B: "d" }).concat(ORB_ICE.slice(11)),
  }),

  scroll_fire: prop(16, 16, 2, {
    base: [
      "................",
      ".kkkkkkkkkkkkkk.",
      "kWWWWWWkkWWWWeek",
      "kWGGGGWkkWGGeook",
      "kWWWWWWkkWWeoyok",
      "kWGGGWWkkWGGeook",
      "kWWWWWekkWWWWeek",
      "keeWWeekkeWWeeek",
      ".kkkkkkkkkkkkkk.",
      ".kmmmmmmmmmmmmk.",
      ".kkkkkkkkkkkkkk.",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "....kkttTTkk....",
      "....kkkkkkkk....",
    ],
    on: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......kkkk......",
      "....kkgGGgkk....",
      "...kgGGgGGgGk...",
      ".kkkkkkkkkkkkkk.",
      ".kmmmmmmmmmmmmk.",
      ".kkkkkkkkkkkkkk.",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "....kkttTTkk....",
      "....kkkkkkkk....",
    ],
  }),

  note: prop(8, 8, 1, {
    base: [
      ".kkkkkk.",
      ".kwwwwk.",
      ".kwGGwk.",
      ".kwwwwk.",
      ".kwGGwk.",
      ".kwwwWk.",
      ".kWWWWk.",
      ".kkkkkk.",
    ],
  }),

  sign: prop(16, 16, 1, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kmmmmmmmmmmmmmmk",
      "kmttttttttttttTk",
      "kmtkktkkktkkttTk",
      "kmttttttttttttTk",
      "kmtkkkktkktkttTk",
      "kmttttttttttttTk",
      "kTTTTTTTTTTTTTTk",
      ".kkkkkkkkkkkkkk.",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      ".....kktTkk.....",
      ".....kkkkkk.....",
    ],
  }),

  torch: prop(8, 16, 1, {
    base: [
      "...kk...",
      "..kook..",
      "..koyk..",
      ".koyyok.",
      ".koyhyk.",
      ".kyhhyk.",
      ".koyyok.",
      ".kkookk.",
      ".kgggGk.",
      "..kgGk..",
      "..ktTk..",
      "..ktTk..",
      "..ktTk..",
      "..ktTk..",
      "..ktTk..",
      "..kkkk..",
    ],
  }),

  torch_blue: prop(8, 16, 1, {
    base: [
      "........",
      "........",
      "........",
      "........",
      "........",
      "........",
      "..kKKk..",
      ".kkKKkk.",
      ".kgggGk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kkkk..",
    ],
    on: [
      "...kk...",
      "..kBBk..",
      "..kBbk..",
      ".kBbbBk.",
      ".kBbibk.",
      ".kbwwbk.",
      ".kBbbBk.",
      ".kkBBkk.",
      ".kgggGk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kkkk..",
    ],
  }),

  // A lantern on a post, the kind a county council put up once and never came back to: a glass box
  // under a cap, a crossbar to lean a ladder on, a stepped foot.
  lamp_post: prop(8, 28, 1, {
    base: [
      "...kk...",
      "..kgGk..",
      ".kgggGk.",
      "kkkkkkkk",
      ".kWdddk.",
      ".kWdddk.",
      ".kddddk.",
      ".kddddk.",
      "kkkkkkkk",
      "..kgGk..",
      ".kkgGkk.",
      "kggggGGk",
      ".kkgGkk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      "kgggGGGk",
      "kkkkkkkk",
    ],
    on: [
      "...kk...",
      "..kgGk..",
      ".kgggGk.",
      "kkkkkkkk",
      ".khhhyk.",
      ".khhyyk.",
      ".kyyyok.",
      ".koyook.",
      "kkkkkkkk",
      "..kgGk..",
      ".kkgGkk.",
      "kggggGGk",
      ".kkgGkk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      "kgggGGGk",
      "kkkkkkkk",
    ],
  }),

  campfire: prop(16, 16, 2, {
    base: [
      ".......kk.......",
      "......kook......",
      ".....kooyk......",
      "....kkoyyok.....",
      "....koyyyokk....",
      "...kooyhyyook...",
      "...koyyhhyyok...",
      "...kroyhhyork...",
      "..kkkroyyorkkk..",
      ".kWgktkrrrktkWgk",
      "kWgGkttTTTTtkgGk",
      "kgGGkkkkkkkkkgGk",
      ".kkkWggkkWggkkk.",
      "...kgGGkkgGGk...",
      "....kkk..kkk....",
      "................",
    ],
  }),

  lever: prop(8, 12, 1, {
    base: [
      ".kk.....",
      "krrk....",
      "kRRk....",
      ".kgk....",
      "..kgk...",
      "..kgk...",
      "...kgk..",
      "...kgk..",
      ".kkkGkk.",
      "kgggkggk",
      "kGGGGGGk",
      "kkkkkkkk",
    ],
    on: [
      ".....kk.",
      "....krrk",
      "....kRRk",
      "....kgk.",
      "...kgk..",
      "...kgk..",
      "..kgk...",
      "..kgk...",
      ".kkGkkk.",
      "kggkgggk",
      "kGGGGGGk",
      "kkkkkkkk",
    ],
  }),

  plate: prop(16, 16, 2, {
    base: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kWWWWWWWWWWWWk.",
      ".kWggggggggggGk.",
      ".kWggggggggggGk.",
      ".kWgggGGGGgggGk.",
      ".kWggGggggGggGk.",
      ".kWggGggggGggGk.",
      ".kWggGggggGggGk.",
      ".kWggGggggGggGk.",
      ".kWgggGGGGgggGk.",
      ".kWggggggggggGk.",
      ".kWggggggggggGk.",
      ".kGGGGGGGGGGGGk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
    on: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kddddddddddddk.",
      ".kdGGGGGGGGGGgk.",
      ".kdGGGGGGGGGGgk.",
      ".kdGGGddddGGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGGddddGGGgk.",
      ".kdGGGGGGGGGGgk.",
      ".kdGGGGGGGGGGgk.",
      ".kggggggggggggk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  }),

  broken_steps: prop(24, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmkKKKKkmmmmmmmTk",
      "kTtttttkkKKKKKKkktttttTk",
      "kTeeeekKKKKKKKKKKkeeeeTk",
      "kkkkkkKKKKKKKKKKKKkkkkkk",
      "kTmmkKKKKKmkKKKKKKKkmmTk",
      "kTtkKKKKKmtkKKKKKKKKktTk",
      "kTekKKKKmtkKKKKKmkKKkeTk",
      "kkkKKKKmtkKKKKKmtkKKKkkk",
      "kTkKKKmtkKKKKKmtkKKKKkTk",
      "kTkKKKkkKKKKKmtkKKKKKkTk",
      "kTkKKKKKKKKKKkkKKKKKKkTk",
      "kkkkkmmmtkKKKKKkmmmkkkkk",
      "kTmmmttttkkKKKkktttmmmTk",
      "kTttttttttttkkktttttttTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
    on: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kTeeeeeeeeeeeeeeeeeeeeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kTeeeeeeeeeeeeeeeeeeeeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kTeeeeeeeeeeeeeeeeeeeeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  broken_track: prop(24, 16, 2, {
    base: [
      ".kkkk....kkk.......kkkk.",
      ".ktTk...kggk.......ktTk.",
      "kkkkkkkkgGk........kkkkk",
      "ggggggggGk...k.....kgggg",
      "GGGGGGGkk...kgk....kGGGG",
      "kkkkkkk....kgGGk...kkkkk",
      ".ktTk.kk...kkkkk...ktTk.",
      ".ktTkktTk..........ktTk.",
      ".ktTk.ktTk.....kk..ktTk.",
      ".ktTk..kkk....ktTk.ktTk.",
      "kkkkkkk.......kkkk.kkkkk",
      "ggggggGk...........kgggg",
      "GGGGGGkgk.........kgGGGG",
      "kkkkkkkkgkk.....kkgkkkkk",
      ".ktTk...kggkkkkkggkktTk.",
      ".kkkk....kkgggggkk.kkkk.",
    ],
    on: [
      ".kkkk..kkkk..kkkk..kkkk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "gggggggggggggggggggggggg",
      "GGGGGGGGGGGGGGGGGGGGGGGG",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "gggggggggggggggggggggggg",
      "GGGGGGGGGGGGGGGGGGGGGGGG",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".kkkk..kkkk..kkkk..kkkk.",
    ],
  }),

  root_wall: prop(16, 20, 2, {
    base: [
      "...kkk....kk....",
      "..kTeekk.kTekkk.",
      ".kTeevkTkkTevTek",
      "kTTeevkTekTevkek",
      "kTeevkkTevkTevvk",
      "WkTeevkTeevkTevk",
      "kkTTeevkTevkkTek",
      "nNkTeevkTeevkTek",
      "kNkkTeevkTevWkek",
      "kTekTTeevkTevkvk",
      "kTevkTeevkTeevkk",
      "kTevkkTeevkTevNn",
      "WkTevkTTeevkTekN",
      "kkTeevkTeevkTevk",
      "kTTeevkkTevkTevk",
      "kTeevkWkTevkkTek",
      "kTeevkkTTeevkTek",
      "kTTeevkTeeevkTek",
      "kTeeevkTeeevkevk",
      ".kkkkkkkkkkkkkk.",
    ],
  }),

  pillar: prop(16, 28, 2, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kWWWWWWWWWWWWWWk",
      "kWWWWWWWWWWWWWgk",
      "kWWWWWWWWWWWWggk",
      "kkkkkkkkkkkkkkkk",
      "kWggggggggggggGk",
      ".kGGGGGGGGGGGGk.",
      "..kkkkkkkkkkkk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWggkGgggGGk..",
      "..kWgggkgggGGk..",
      "..kWgggGkggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kNgggGgggGGk..",
      "..knNggGgggGGk..",
      "..kNnNgGgggGGk..",
      "..kWNggGgggGGk..",
      ".kkkkkkkkkkkkkk.",
      "kWggggggggggggGk",
      "kgGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  coffin: prop(16, 24, 3, {
    base: [
      "....kkkkkkkk....",
      "...kWWWWWWWWk...",
      "..kWggggggggGk..",
      ".kWggggGGggggGk.",
      "kWgggggGGgggggGk",
      "kWgggggGGgggggGk",
      "kWggGGGGGGGGggGk",
      "kWggGGGGGGGGggGk",
      "kWgggggGGgggggGk",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWggggggggGk..",
      "..kgGGGGGGGGGk..",
      "..kkkkkkkkkkkk..",
      "..kddddddddddk..",
      "..kkkkkkkkkkkk..",
    ],
  }),

  car_wreck: prop(40, 26, 3, { base: CAR_WRECK, open: CAR_WRECK }),

  apple_tree: prop(16, 28, 2, {
    base: APPLE_TREE,
    // Picked: the apples become leaves, and the hole they leave keeps the canopy lumpy.
    open: swap(APPLE_TREE, { r: "f", R: "F" }),
  }),

  // Scattered by the hundred, so it has to survive being seen a hundred times: three
  // blades of different lengths leaning different ways, two seed heads at different
  // heights, and a shadow at the root. Nothing centred, nothing repeated.
  //
  // base2 and base3 are the same plant at other ages, not the same drawing flipped: one
  // gone up to a single tall head, one grown out sideways with its heads wide apart. The
  // renderer picks among the three by the prop's own id, so a hillside is a meadow rather
  // than a print run, and any one herb stays the herb it was.
  herb: prop(8, 8, 1, {
    base: [
      "...y....",
      "..llY.y.",
      "l.flF.lY",
      "lf.lF.lF",
      ".lFflfF.",
      "..lfnFf.",
      ".=nFNN=.",
      "..-==-..",
    ],
    base2: [
      "....y...",
      "...lY...",
      "...lF...",
      "l..lF...",
      "lf.lF.l.",
      ".lfnFflF",
      ".=nFNNF=",
      "..-==-..",
    ],
    base3: [
      "......y.",
      "..y..lY.",
      ".lY.lF..",
      "l.lflF..",
      "lfflfF.l",
      ".lfnFFlF",
      "=nFFNNF=",
      ".-==-=..",
    ],
  }),

  // The white water rose: one head, off centre and leaning away from its leaves, so it
  // reads as a flower on a plant rather than a white dot on the grass. base2 leans the
  // other way, which is enough variety for something this rare; a third drawn in bud was
  // cut, because a closed one reads as a rose you are not meant to pick.
  rose: prop(8, 8, 1, {
    base: [
      "........",
      "..ww....",
      ".wwWw.l.",
      "wwWyWwlF",
      ".wWWWfF.",
      "l.fnf.F.",
      ".lFnFF..",
      "..=nN=..",
    ],
    base2: [
      "........",
      "....ww..",
      ".l..wwWw",
      "lF.wwyWw",
      ".Ff.wWW.",
      "l.fnf...",
      ".lFnFF..",
      "..=nN=..",
    ],
  }),

  // The well on the station road: a ring of stone with the dark in it, a little tiled roof on two posts,
  // the windlass and the bucket. Footprint 2 x 2.
  well: prop(16, 24, 2, {
    base: [
      "...kkkkkkkkkk...",
      "..krrrrrrrrrrk..",
      ".krrRrrRrrRrrrk.",
      "kRRRRRRRRRRRRRRk",
      "kkkkkkkkkkkkkkkk",
      "..kTk......kTk..",
      "..ktk.kkkk.ktk..",
      "..ktkkmmmmkktk..",
      "..ktk.kkkk.ktk..",
      "..ktk..kk..ktk..",
      "..ktk.kttk.ktk..",
      "..ktk.kTTk.ktk..",
      ".kkkkkkkkkkkkkk.",
      "kWWWgWWWgWWWgWWk",
      "kWkkkkkkkkkkkkgk",
      "kgkxxxxxxxxxxkGk",
      "kgkxzzBzzzzzxkGk",
      "kgkxxxxxxxxxxkGk",
      "kWkkkkkkkkkkkkGk",
      "kggGgggGgggGggGk",
      "kgGGkgGGkgGGkgGk",
      "kGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkk",
      ".--------------.",
    ],
  }),

  // A farm cart with its shafts down and sacks in the bed. Footprint 2 x 2.
  cart: prop(16, 20, 2, {
    base: [
      "................",
      ".kkk............",
      "kmmtk...........",
      "kkktkkkkkkkkkkk.",
      "..kmmmmmmmmmmmmk",
      "..ktttttttttttTk",
      "..kTkkkkkkkkkkTk",
      "..kTkWWkeWWWekTk",
      "..kTkWWWeWWeekTk",
      "kkkkkkkkkkkkkkkk",
      "kmtmtmtmtmtmtmTk",
      "kttttttttttttttk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "..kkkk....kkkk..",
      ".kTmmTk..kTmmTk.",
      ".kmkkmk..kmkkmk.",
      ".kTmmTk..kTmmTk.",
      "..kkkk-..-kkkk-.",
      "................",
    ],
  }),

  minecart: prop(16, 16, 2, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kuuuuuuuuuuuuuuk",
      "kukkkkkkkkkkkkUk",
      "kukxxxxxxxxxxkUk",
      "kukxxGgxxxGxxkUk",
      "kukxGggGxGgGxkUk",
      "kukkkkkkkkkkkkUk",
      "kuuuuuuuuuuuuuUk",
      "kkkkkkkkkkkkkkkk",
      ".kuuuUuuuuuUuUk.",
      ".kuGuUuuuuuGUUk.",
      ".kuuUUuuuuuUUUk.",
      "..kUUUUUUUUUUk..",
      "..kkkkkkkkkkkk..",
      "..kGgk....kGgk..",
      "...kk......kk...",
    ],
  }),
};

// --- fragments -------------------------------------------------------------------------
// A dungeon's creatures, a region's props: each set may live in a file of its own under
// ./props/ and `export default` a SpriteSheet. Merged here in path order; an id drawn twice is an error.
const PROP_SPRITES_FRAGMENTS = import.meta.glob("./props/*.ts", { eager: true, import: "default" }) as Record<string, SpriteSheet>;
for (const path of Object.keys(PROP_SPRITES_FRAGMENTS).sort()) {
  for (const [id, sprite] of Object.entries(PROP_SPRITES_FRAGMENTS[path])) {
    if (id in PROP_SPRITES) throw new Error(`art: "${id}" is drawn twice (again in ${path})`);
    PROP_SPRITES[id] = sprite;
  }
}
