import type { Palette, SpriteSheet, SpriteSrc } from "@/art/types";
import { PAL } from "@/art/types";

// Prop sprites. Width is always footprint w*8; tall props rise UP out of their
// footprint, so ay = spriteHeight - footprintH*8. Top-down 3/4: you see the top
// face and the front face, light from the top-left, 1px dark outline.

/** Shared palette plus the handful of extra tones props need. */
const PX: Palette = {
  ...PAL,
  x: "#0c0a12", // void: inside of mouths, chests, windows
  d: "#3a3e4a", // darkest stone / cold iron
  h: "#fff4b0", // flame / lamp core
  q: "#5a3a18", // dim warm glow on black
  z: "#1a2a58", // deep blue glow
  u: "#b0603a", // rust
  U: "#70382a", // dark rust
  c: "#6fa8a0", // sun-faded teal car paint
  C: "#47756f", // teal shade
  v: "#2c2018", // darkest root
};

/** footH is the footprint height in 8 px cells. */
function prop(w: number, h: number, footH: number, frames: Record<string, string[]>): SpriteSrc {
  return { w, h, ax: 0, ay: h - footH * 8, palette: PX, frames };
}

/** Same drawing with some palette characters swapped (spent orb, picked tree). */
function swap(rows: string[], map: Record<string, string>): string[] {
  return rows.map((r) => Array.from(r, (ch) => map[ch] ?? ch).join(""));
}

const ORB_ICE = [
  ".....kkkkkk.....",
  "...kkiiiiiikk...",
  "..kiiwwiiiiibk..",
  ".kiiwwiiiiiibbk.",
  ".kiiwiiiiiibbbk.",
  "kiiiiiiiiiibbbBk",
  "kiiiiiiiiibbbbBk",
  ".kiiiiiibbbbbBk.",
  ".kibbbbbbbbBBBk.",
  "..kbbbbbbBBBBk..",
  "...kkBBBBBBkk...",
  ".....kkkkkk.....",
  "....kgggggGk....",
  ".....kgggGk.....",
  "......kgGk......",
  "......kgGk......",
  ".....kkgGkk.....",
  "...kkggggGGkk...",
  "..kgggggggGGGk..",
  "..kkkkkkkkkkkk..",
];

const APPLE_TREE = [
  ".....kkkkkk.....",
  "...kkllllnnkk...",
  "..kllllnnnnnnk..",
  ".kllrlnnnnrnnNk.",
  ".klllnnnnnnnnNk.",
  "klllnnnnrnnnnnNk",
  "kllnnnnnnnnnnNNk",
  "klnnrnnnnnnrnNNk",
  "klnnnlnnnnnnnNNk",
  "knnnlnnnnNnnnNNk",
  "knnnnnnrnnnnNNNk",
  "knnrnnnnnnnnNNNk",
  "knnnnlnnnnnNNNNk",
  "kNnnnnnnnnNnrNNk",
  "kNnnrnnnnNNNNNNk",
  ".kNnnnnnnNNNNNk.",
  ".kNNnnnNNNNNNNk.",
  "..kkNNNNNNNNkk..",
  "....kkktTkkk....",
  "......ktTk......",
  "......ktTk......",
  "......ktTk......",
  "......ktTk......",
  "......ktTk......",
  "......ktTk......",
  ".....kttTTk.....",
  "....kkttTTkk....",
  "....kkkkkkkk....",
];

const CAR_WRECK = [
  ".................l......................",
  "...............nln......l...............",
  "..............kkkkkkkkkkkkkk............",
  "............kkccccccccccccuukk..........",
  "...........kccccccccccccuuuuUck.........",
  "...........kcccnccccccccuuuUUck.........",
  "...........kccnlnccccccccuUUcck.........",
  "...........kCCnNCCCCCCCCCCCCCCk.........",
  "..........kkkknkkkkkkkkkkkkkkkkk....kk..",
  "..kkkkkkkkkcckKnxxxkCkxxxxKxkcckkkkkkcck",
  ".kcccccuuckckxKnlxxkCkxxxKxxxkckccnuucck",
  "kcccccuUcckkxxxxnxxkCkxxKxxxxxkkcclnUcck",
  "kccccuuUUckkkkknkkkkkkkkkkkkkkkkcuunUcck",
  "kWWWWWWWWWWkxxxxxxxkccCkWWWWWWWWWWWnWWWk",
  "kWCCCCUUCCCkxxRRRRxkccCkCCCCCCCUUUnlCCrk",
  "kgCCCUUUUCCkxxRRRRxkccCkCCCCCCUUUUNCCCRk",
  "kWgCCUUUCCCkxxkkkkxxkccCkCCCCCCUUCCCCgWk",
  "kWCkkkkkCCCkxxxxxxxxkccCkCCCCCkkkkkCCCWk",
  "kgkKWWWKkUCkxxxxxxxxkccCkCUUCkKWWWKkCUgk",
  "kUkWggGWkUUkUUUUUUUUUkcCCkUUUkWggGWkUUUk",
  ".kkWgWGWkkkkkkkkkkkkkkcCCkkkkkWgWGWkkkk.",
  "..kWGGGWkKKKKKKKKKKKKkcCCkKKKkWGGGWk....",
  "..kKWWWKkKKKKKKKKKKKKKkCUUkKKkKWWWKk....",
  "...kkkkk..............kUUUk...kkkkk.....",
  "...n..................kkkkk.....l.......",
  "..nl.l..........................n.ln....",
];

export const PROP_SPRITES: SpriteSheet = {
  door: prop(16, 20, 2, {
    base: [
      "..kkkkkkkkkkkk..",
      ".kmmmmmmmmmmmmk.",
      "kmttttttttttttTk",
      "kmtkkkkkkkkkktTk",
      "kmtkmttTmttTktTk",
      "kmtkmtkkkktTktTk",
      "kmtkmtkibktTktTk",
      "kmtkmtkbBktTktTk",
      "kmtkmtkkkktTktTk",
      "kmtkmttTmttTktTk",
      "kmtkTTTTTTTTktTk",
      "kmtkmttTmttTktTk",
      "kmtkmttTmyyTktTk",
      "kmtkmttTmYYTktTk",
      "kmtkmttTmttTktTk",
      "kmtkmttTmttTktTk",
      "kmtkTTTTTTTTktTk",
      "kmtkmttTmttTktTk",
      "kmtkeeeeeeeektTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  mine_mouth: prop(24, 24, 2, {
    base: [
      "......kkkkkkkkkkkk......",
      "...kkkggWgggggWggGkkk...",
      ".kkgGgggggGggggggGgggkk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kttTtttttTtttttTtttttTtk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmttTkxxxxxxGxxxxxkmttTk",
      "kmttTkxxxxqkkkqxxxkmttTk",
      "kmttTkxxxqkyhykqxxkmttTk",
      "kmttTkxxxqkohokqxxkmttTk",
      "kmttTkxxxxqkkkqxxxkmttTk",
      "kmttTkxxxxxqqqxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxxxxxxxxxxxxkmttTk",
      "kmttTkxKKGKKKKGKKxkmttTk",
      "kmttTkKeeGeeeeGeeKkmttTk",
      "kmttTkeTTGTTTTGTTekmttTk",
      "kkkkkkeeeGeeeeGeeekkkkkk",
    ],
  }),

  burial_mouth: prop(24, 24, 2, {
    base: [
      ".kkkkkkkkkkkkkkkkkkkkkk.",
      "kWWWWWWWWWWWWWWWWWWWWWWk",
      "kWgNNggggNNggggNNgggNygk",
      "kWNggNggNggNggNggNggNNgk",
      "kWggggNNggggNNggggNNgggk",
      "kggggggggggggggggggggggk",
      "kGGGGGGGGGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kWggGkxxxxxxxxxxxxkWggGk",
      "kWggGkxxxzzzzzzxxxkWggGk",
      "kWggGkxxzzBBBBzzxxkWggGk",
      "kWggGkxzzBBbbBBzzxkWggGk",
      "kWggGkxzzBBbbBBzzxkWggGk",
      "kWggGkzzzzBBBBzzzzkWggGk",
      "kWggGkddddddddddddkWggGk",
      "kWggGkkkkkkkkkkkkkkWggGk",
      "kWggGkGGGGGGGGGGGGkWggGk",
      "kWggGkGGGGGGGGGGGGkWggGk",
      "kWggGkkkkkkkkkkkkkkWggGk",
      "kWggGkggggggggggggkWggGk",
      "kWggGkggggggggggggkWggGk",
      "kWggGkkkkkkkkkkkkkkWggGk",
      "kWggGkWWWWWWWWWWWWkWggGk",
      "kkkkkkggggggggggggkkkkkk",
    ],
  }),

  hatch: prop(16, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kTTGGTTTTTTGGTTk",
      "kTmGGmmmmmmGGmTk",
      "kTttttttttttttTk",
      "kTttttttttttttTk",
      "kTeeeeeeeeeeeeTk",
      "kTmmmmmggmmmmmTk",
      "kTttttgttgttttTk",
      "kTttttGttGttttTk",
      "kTeeeeeGGeeeeeTk",
      "kTmmmmmmmmmmmmTk",
      "kTttttttttttttTk",
      "kTttttttttttttTk",
      "kTeeeeeeeeeeeeTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  stairs: prop(16, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kGwwwwwwwwwwwwGk",
      "kGWWWWWWWWWWWWGk",
      "kGddddddddddddGk",
      "kGWWWWWWWWWWWWGk",
      "kGWWWWWgWWWWWWGk",
      "kGddddddddddddGk",
      "kGWWWWWWWWWWWWGk",
      "kGWgWWWWWWWWWgGk",
      "kGddddddddddddGk",
      "kGWWWWWWWWWgWWGk",
      "kGggggggggggggGk",
      "kGddddddddddddGk",
      "kGggggggggggggGk",
      "kGggggggggggggGk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  gate_h: prop(24, 16, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kgggggggggggggggggggggGk",
      "kGGGGGGGGGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kgk.kgk.kgk..kgk.kgk.kgk",
      "kgk.kgk.kgk..kgk.kgk.kgk",
      "kgk.kgk.kkkkkkkk.kgk.kgk",
      "kgk.kgk.kYyyyyYk.kgk.kgk",
      "kgk.kgk.kyykkyyk.kgk.kgk",
      "kgk.kgk.kyykkyyk.kgk.kgk",
      "kgk.kgk.kYyyyyYk.kgk.kgk",
      "kgk.kgk.kkkkkkkk.kgk.kgk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kGGGGGGGGGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      ".k...k...k....k...k...k.",
    ],
  }),

  gate_v: prop(8, 28, 3, {
    base: [
      ".kkkkkk.",
      "kggggggk",
      "kgGGGGGk",
      ".kkkkkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      ".kkkkkk.",
      ".kYyyYk.",
      ".kykkyk.",
      ".kYyyYk.",
      ".kkkkkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      ".kkgGkk.",
      "..kgGk..",
      "..kkkk..",
    ],
  }),

  chest: prop(16, 16, 2, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kmmgGmmmmmmgGmmk",
      "kmtgGttttttgGttk",
      "kttgGttttttgGttk",
      "kttgGttttttgGttk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      "kttgGttkkttgGttk",
      "kttgGtkyYktgGttk",
      "kttgGtkYYktgGttk",
      "kttgGttkkttgGttk",
      "kttgGttttttgGttk",
      "kTTgGTTTTTTgGTTk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
    open: [
      ".kkkkkkkkkkkkkk.",
      "kTTgGTTTTTTgGTTk",
      "kTegGeeeeeegGeTk",
      "kTegGeeeeeegGeTk",
      "kTegGeeeeeegGeTk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      "kmxxxxxxxxxxxxmk",
      "kmxxxxxxxxxxxxmk",
      "kmKKKKKKKKKKKKmk",
      "kkkkkkkkkkkkkkkk",
      "kttgGttkkttgGttk",
      "kttgGttttttgGttk",
      "kTTgGTTTTTTgGTTk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
  }),

  boss_chest: prop(16, 18, 2, {
    base: [
      "..kkkkkkkkkkkk..",
      ".kyyyyyyyyyyyyk.",
      "kyrryYrrrryYrryk",
      "kyrryYrrrryYrryk",
      "kYrRyYRRRRyYRrYk",
      "kYRRyYRRRRyYRRYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      "kyyyyyykkyyyyyyk",
      "kyrryYkibkyYrryk",
      "kyrryYkbBkyYrryk",
      "kyrryYrkkryYrryk",
      "kyrryYrrrryYrryk",
      "kYRRyYRRRRyYRRYk",
      "kYRRyYRRRRyYRRYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
    open: [
      "..kkkkkkkkkkkk..",
      ".kYYYYYYYYYYYYk.",
      "kYPPPPPPPPPPPPYk",
      "kYPpPPPPPPPPpPYk",
      "kYPPPPPPPPPPPPYk",
      "kYPPPPPPPPPPPPYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      "kyxxxxxxxxxxxxyk",
      "kyxxxxxxxxxxxxyk",
      "kyPPPPPPPPPPPPyk",
      "kkkkkkkkkkkkkkkk",
      "kyrryYrrrryYrryk",
      "kYRRyYRRRRyYRRYk",
      "kYRRyYRRRRyYRRYk",
      "kYYYYYYYYYYYYYYk",
      "kkkkkkkkkkkkkkkk",
      ".KKKKKKKKKKKKKK.",
    ],
  }),

  crate: prop(16, 18, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmk",
      "kmttttttttttttmk",
      "kmtmmmmmmmmmmtmk",
      "kmttttttttttttmk",
      "kmmmmmmmmmmmmmmk",
      "kkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmtk",
      "kmeeeeeeeeeeeetk",
      "kmemmeeeeeemmetk",
      "kmeemmeeeemmeetk",
      "kmeeeemmmmeeeetk",
      "kmeeeemmmmeeeetk",
      "kmeemmeeeemmeetk",
      "kmemmeeeeeemmetk",
      "kmeeeeeeeeeeeetk",
      "kttttttttttttttk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  barrel: prop(16, 18, 2, {
    base: [
      "....kkkkkkkk....",
      "..kkmmtmmtmmkk..",
      ".kmmmmtmmtmmmtk.",
      ".kmmmmtmmtmmmtk.",
      ".kkkmmtmmtmtkkk.",
      ".kmtkkkkkkkkTTk.",
      "kggGGGGGGGGGGGGk",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kmmtTtttTtttTTek",
      "kggGGGGGGGGGGGGk",
      "kmmtTtttTtttTTek",
      ".kmtTtttTtttTTk.",
      "..kkkkkkkkkkkk..",
      "...KKKKKKKKKK...",
    ],
  }),

  rock: prop(8, 8, 1, {
    base: [
      "..kkkk..",
      ".kWWggk.",
      "kWWggggk",
      "kWgggGGk",
      "kgggGGGk",
      "kgGGGGGk",
      ".kGGGGk.",
      "..kkkk..",
    ],
  }),

  bench: prop(24, 20, 2, {
    base: [
      "........................",
      "........................",
      "...TT...................",
      "..kllk.............kkk..",
      "..klnk.........W...kik..",
      "kkklnkkTkkkkkkWkkkkkikkk",
      "kmklnkkrkmmkkWkkkmkibbkk",
      "kmknNkkrkmmkWGGgkmkibBkk",
      "kmkkkkkRkmmkgggGkmkbBBkk",
      "ktttttkkktttkgGktttkkktk",
      "kmmmmmmmmmmmkkkkmmmmmmmk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kttttttttttttttttttttttk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktttttttttttttttttttttTk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktTkKKKKKKKKKKKKKKKKktTk",
      "ktTk................ktTk",
      "kkkk................kkkk",
    ],
  }),

  table: prop(24, 18, 2, {
    base: [
      ".kkkkkkkkkkkkkkkkkkkkkk.",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kttttttttttttttttttttttk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kmmmmmmmtmmmmmmmmmmmmmmk",
      "kttttttttttttttttttttttk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kmmmmmmmmmmmmmmmtmmmmmmk",
      "kttttttttttttttttttttttk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kttttttttttttttttttttttk",
      "kTTTTTTTTTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "ktTkKKKKKKKKKKKKKKKKktTk",
      "ktTk................ktTk",
      "ktTk................ktTk",
      "kkkk................kkkk",
    ],
  }),

  shelf: prop(24, 18, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kteeeeeeeeeeeeeeeeeeeeTk",
      "ktrReenNepPeeeeeeeeeeeTk",
      "ktrRbBnNWpPeeeeTTeeeeeTk",
      "ktyybBnNWpPYeekiikeeeeTk",
      "ktrRbBnNWpPYeeklnkeYYYTk",
      "ktrRbBnNWpPYeeklnkerrRTk",
      "ktrRbBnNWpPYeekkkkebbBTk",
      "ktmmmmmmmmmmmmmmmmmmmmTk",
      "kteeeeeeeeeeeeeeeeeeeeTk",
      "kteeTTeeeeeTTeeeeeeeeeTk",
      "ktekiikeeekiikeekkkkkeTk",
      "ktekrrkeeekyykeekmmmkeTk",
      "ktekrRkeeekyYkeektytkeTk",
      "ktekkkkeeekkkkeekkkkkeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  bed: prop(16, 26, 3, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kmmmmmmmmmmmmmmk",
      "kttttttttttttttk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "kWWkkkkkkkkkkWWk",
      "kWkwwwwwwwwwWkWk",
      "kWkwwwwwwwwWWkWk",
      "kWWkkkkkkkkkkWWk",
      "kWWWWWWWWWWWWWWk",
      "krrrBBBBrrrrBBBk",
      "krrrBBBBrrrrBBBk",
      "krrrBBBBrrrrBBBk",
      "kBBBrrrrBBBBrrrk",
      "kBBBrrrrBBBBrrrk",
      "kBBBrrrrBBBBrrrk",
      "krrrBBBBrrrrBBBk",
      "krrrBBBBrrrrBBBk",
      "krrrBBBBrrrrBBBk",
      "kBBBrrrrBBBBrrrk",
      "kBBBrrrrBBBBrrrk",
      "kBBBrrrrBBBBrrrk",
      "kkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  stove: prop(16, 20, 2, {
    base: [
      ".....kkkk.......",
      ".....kgGk.......",
      ".....kgGk.......",
      ".kkkkkgGkkkkkkk.",
      "kggggkgGkggggggk",
      "kgGkkkGGGGkkkGGk",
      "kgkGGGkGGkGGGkGk",
      "kgGkkkGGGGkkkGGk",
      "kkkkkkkkkkkkkkkk",
      "kgGGGGGGGGGGGGGk",
      "kgkkkkkkkkkkkkGk",
      "kgkoyykoyykoykGk",
      "kgkyhykyhhkyhkGk",
      "kgkoyykoyykoykGk",
      "kgkrookrookrokGk",
      "kgkkkkkkkkkkkkGk",
      "kgGGGGGGGGGGGGGk",
      "kGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkk",
      ".kk..........kk.",
    ],
  }),

  fruit_bowl: prop(16, 12, 1, {
    base: [
      "......T...T.....",
      ".....kkk.kkk....",
      "....krwrkrwrk...",
      "kkkkkrrrRrrRkkkk",
      "kmkWWWWWWWWWgkmk",
      "kmmkbbbbbbbbkmmk",
      "kmmmkWWWWWgkmmmk",
      "kttttkkkkkkttttk",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "ktk..........ktk",
    ],
    open: [
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kmkgGGGGGGGGgkmk",
      "kmmkbbbbbbbbkmmk",
      "kmmmkWWWWWgkmmmk",
      "kttttkkkkkkttttk",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "ktk..........ktk",
    ],
  }),

  orb_ice: prop(16, 20, 2, {
    base: ORB_ICE,
    on: swap(ORB_ICE.slice(0, 11), { i: "g", w: "W", b: "G", B: "d" }).concat(ORB_ICE.slice(11)),
  }),

  scroll_fire: prop(16, 16, 2, {
    base: [
      "................",
      ".kkkkkkkkkkkkkk.",
      "kWWWWWWkkWWWWeek",
      "kWGGGGWkkWGGeook",
      "kWWWWWWkkWWeoyok",
      "kWGGGWWkkWGGeook",
      "kWWWWWekkWWWWeek",
      "keeWWeekkeWWeeek",
      ".kkkkkkkkkkkkkk.",
      ".kmmmmmmmmmmmmk.",
      ".kkkkkkkkkkkkkk.",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "....kkttTTkk....",
      "....kkkkkkkk....",
    ],
    on: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......kkkk......",
      "....kkgGGgkk....",
      "...kgGGgGGgGk...",
      ".kkkkkkkkkkkkkk.",
      ".kmmmmmmmmmmmmk.",
      ".kkkkkkkkkkkkkk.",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "....kkttTTkk....",
      "....kkkkkkkk....",
    ],
  }),

  note: prop(8, 8, 1, {
    base: [
      ".kkkkkk.",
      ".kwwwwk.",
      ".kwGGwk.",
      ".kwwwwk.",
      ".kwGGwk.",
      ".kwwwWk.",
      ".kWWWWk.",
      ".kkkkkk.",
    ],
  }),

  sign: prop(16, 16, 1, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kmmmmmmmmmmmmmmk",
      "kmttttttttttttTk",
      "kmtkktkkktkkttTk",
      "kmttttttttttttTk",
      "kmtkkkktkktkttTk",
      "kmttttttttttttTk",
      "kTTTTTTTTTTTTTTk",
      ".kkkkkkkkkkkkkk.",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      "......ktTk......",
      ".....kktTkk.....",
      ".....kkkkkk.....",
    ],
  }),

  torch: prop(8, 16, 1, {
    base: [
      "...kk...",
      "..kook..",
      "..koyk..",
      ".koyyok.",
      ".koyhyk.",
      ".kyhhyk.",
      ".koyyok.",
      ".kkookk.",
      ".kgggGk.",
      "..kgGk..",
      "..ktTk..",
      "..ktTk..",
      "..ktTk..",
      "..ktTk..",
      "..ktTk..",
      "..kkkk..",
    ],
  }),

  torch_blue: prop(8, 16, 1, {
    base: [
      "........",
      "........",
      "........",
      "........",
      "........",
      "........",
      "..kKKk..",
      ".kkKKkk.",
      ".kgggGk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kkkk..",
    ],
    on: [
      "...kk...",
      "..kBBk..",
      "..kBbk..",
      ".kBbbBk.",
      ".kBbibk.",
      ".kbwwbk.",
      ".kBbbBk.",
      ".kkBBkk.",
      ".kgggGk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kkkk..",
    ],
  }),

  lamp_post: prop(8, 28, 1, {
    base: [
      "...kk...",
      "..kGGk..",
      ".kkkkkk.",
      ".kdgddk.",
      ".kdgddk.",
      ".kddddk.",
      ".kddddk.",
      "..kddk..",
      "..kkkk..",
      "..kgGk..",
      "..kgGk..",
      ".kggGGk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      "kgggGGGk",
      "kkkkkkkk",
    ],
    on: [
      "...kk...",
      "..kGGk..",
      ".kkkkkk.",
      ".kyhhyk.",
      ".kyhhyk.",
      ".kyhhyk.",
      ".koyyok.",
      "..kook..",
      "..kkkk..",
      "..kgGk..",
      "..kgGk..",
      ".kggGGk.",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      "..kgGk..",
      ".kkgGkk.",
      ".kggGGk.",
      "kgggGGGk",
      "kkkkkkkk",
    ],
  }),

  campfire: prop(16, 16, 2, {
    base: [
      ".......kk.......",
      "......kook......",
      ".....kooyk......",
      "....kkoyyok.....",
      "....koyyyokk....",
      "...kooyhyyook...",
      "...koyyhhyyok...",
      "...kroyhhyork...",
      "..kkkroyyorkkk..",
      ".kWgktkrrrktkWgk",
      "kWgGkttTTTTtkgGk",
      "kgGGkkkkkkkkkgGk",
      ".kkkWggkkWggkkk.",
      "...kgGGkkgGGk...",
      "....kkk..kkk....",
      "................",
    ],
  }),

  lever: prop(8, 12, 1, {
    base: [
      ".kk.....",
      "krrk....",
      "kRRk....",
      ".kgk....",
      "..kgk...",
      "..kgk...",
      "...kgk..",
      "...kgk..",
      ".kkkGkk.",
      "kgggkggk",
      "kGGGGGGk",
      "kkkkkkkk",
    ],
    on: [
      ".....kk.",
      "....krrk",
      "....kRRk",
      "....kgk.",
      "...kgk..",
      "...kgk..",
      "..kgk...",
      "..kgk...",
      ".kkGkkk.",
      "kggkgggk",
      "kGGGGGGk",
      "kkkkkkkk",
    ],
  }),

  plate: prop(16, 16, 2, {
    base: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kWWWWWWWWWWWWk.",
      ".kWggggggggggGk.",
      ".kWggggggggggGk.",
      ".kWgggGGGGgggGk.",
      ".kWggGggggGggGk.",
      ".kWggGggggGggGk.",
      ".kWggGggggGggGk.",
      ".kWggGggggGggGk.",
      ".kWgggGGGGgggGk.",
      ".kWggggggggggGk.",
      ".kWggggggggggGk.",
      ".kGGGGGGGGGGGGk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
    on: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kddddddddddddk.",
      ".kdGGGGGGGGGGgk.",
      ".kdGGGGGGGGGGgk.",
      ".kdGGGddddGGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGdGGGGdGGgk.",
      ".kdGGGddddGGGgk.",
      ".kdGGGGGGGGGGgk.",
      ".kdGGGGGGGGGGgk.",
      ".kggggggggggggk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  }),

  broken_steps: prop(24, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmkKKKKkmmmmmmmTk",
      "kTtttttkkKKKKKKkktttttTk",
      "kTeeeekKKKKKKKKKKkeeeeTk",
      "kkkkkkKKKKKKKKKKKKkkkkkk",
      "kTmmkKKKKKmkKKKKKKKkmmTk",
      "kTtkKKKKKmtkKKKKKKKKktTk",
      "kTekKKKKmtkKKKKKmkKKkeTk",
      "kkkKKKKmtkKKKKKmtkKKKkkk",
      "kTkKKKmtkKKKKKmtkKKKKkTk",
      "kTkKKKkkKKKKKmtkKKKKKkTk",
      "kTkKKKKKKKKKKkkKKKKKKkTk",
      "kkkkkmmmtkKKKKKkmmmkkkkk",
      "kTmmmttttkkKKKkktttmmmTk",
      "kTttttttttttkkktttttttTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
    on: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kTeeeeeeeeeeeeeeeeeeeeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kTeeeeeeeeeeeeeeeeeeeeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kTeeeeeeeeeeeeeeeeeeeeTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTmmmmmmmmmmmmmmmmmmmmTk",
      "kTttttttttttttttttttttTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  broken_track: prop(24, 16, 2, {
    base: [
      ".kkkk....kkk.......kkkk.",
      ".ktTk...kggk.......ktTk.",
      "kkkkkkkkgGk........kkkkk",
      "ggggggggGk...k.....kgggg",
      "GGGGGGGkk...kgk....kGGGG",
      "kkkkkkk....kgGGk...kkkkk",
      ".ktTk.kk...kkkkk...ktTk.",
      ".ktTkktTk..........ktTk.",
      ".ktTk.ktTk.....kk..ktTk.",
      ".ktTk..kkk....ktTk.ktTk.",
      "kkkkkkk.......kkkk.kkkkk",
      "ggggggGk...........kgggg",
      "GGGGGGkgk.........kgGGGG",
      "kkkkkkkkgkk.....kkgkkkkk",
      ".ktTk...kggkkkkkggkktTk.",
      ".kkkk....kkgggggkk.kkkk.",
    ],
    on: [
      ".kkkk..kkkk..kkkk..kkkk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "gggggggggggggggggggggggg",
      "GGGGGGGGGGGGGGGGGGGGGGGG",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".ktTk..ktTk..ktTk..ktTk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "gggggggggggggggggggggggg",
      "GGGGGGGGGGGGGGGGGGGGGGGG",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      ".ktTk..ktTk..ktTk..ktTk.",
      ".kkkk..kkkk..kkkk..kkkk.",
    ],
  }),

  root_wall: prop(16, 20, 2, {
    base: [
      "...kkk....kk....",
      "..kTeekk.kTekkk.",
      ".kTeevkTkkTevTek",
      "kTTeevkTekTevkek",
      "kTeevkkTevkTevvk",
      "WkTeevkTeevkTevk",
      "kkTTeevkTevkkTek",
      "nNkTeevkTeevkTek",
      "kNkkTeevkTevWkek",
      "kTekTTeevkTevkvk",
      "kTevkTeevkTeevkk",
      "kTevkkTeevkTevNn",
      "WkTevkTTeevkTekN",
      "kkTeevkTeevkTevk",
      "kTTeevkkTevkTevk",
      "kTeevkWkTevkkTek",
      "kTeevkkTTeevkTek",
      "kTTeevkTeeevkTek",
      "kTeeevkTeeevkevk",
      ".kkkkkkkkkkkkkk.",
    ],
  }),

  pillar: prop(16, 28, 2, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kWWWWWWWWWWWWWWk",
      "kWWWWWWWWWWWWWgk",
      "kWWWWWWWWWWWWggk",
      "kkkkkkkkkkkkkkkk",
      "kWggggggggggggGk",
      ".kGGGGGGGGGGGGk.",
      "..kkkkkkkkkkkk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWggkGgggGGk..",
      "..kWgggkgggGGk..",
      "..kWgggGkggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kWgggGgggGGk..",
      "..kNgggGgggGGk..",
      "..knNggGgggGGk..",
      "..kNnNgGgggGGk..",
      "..kWNggGgggGGk..",
      ".kkkkkkkkkkkkkk.",
      "kWggggggggggggGk",
      "kgGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),

  coffin: prop(16, 24, 3, {
    base: [
      "....kkkkkkkk....",
      "...kWWWWWWWWk...",
      "..kWggggggggGk..",
      ".kWggggGGggggGk.",
      "kWgggggGGgggggGk",
      "kWgggggGGgggggGk",
      "kWggGGGGGGGGggGk",
      "kWggGGGGGGGGggGk",
      "kWgggggGGgggggGk",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      ".kWggggGGggggGk.",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWgggGGgggGk..",
      "..kWggggggggGk..",
      "..kgGGGGGGGGGk..",
      "..kkkkkkkkkkkk..",
      "..kddddddddddk..",
      "..kkkkkkkkkkkk..",
    ],
  }),

  car_wreck: prop(40, 26, 3, { base: CAR_WRECK, open: CAR_WRECK }),

  apple_tree: prop(16, 28, 2, {
    base: APPLE_TREE,
    open: swap(APPLE_TREE, { r: "n" }),
  }),

  herb: prop(8, 8, 1, {
    base: [
      "...p....",
      "..pyp.p.",
      "...p.pyp",
      ".l.n..p.",
      ".nlnln..",
      "..nnnl..",
      ".lnNnn..",
      "..NNN...",
    ],
  }),

  rose: prop(8, 8, 1, {
    base: [
      "..kkkk..",
      ".kwwWwk.",
      ".kwWwwk.",
      ".kWwwWk.",
      "..kkkk..",
      "..lNnl..",
      "...Nn...",
      "...N....",
    ],
  }),

  minecart: prop(16, 16, 2, {
    base: [
      ".kkkkkkkkkkkkkk.",
      "kuuuuuuuuuuuuuuk",
      "kukkkkkkkkkkkkUk",
      "kukxxxxxxxxxxkUk",
      "kukxxGgxxxGxxkUk",
      "kukxGggGxGgGxkUk",
      "kukkkkkkkkkkkkUk",
      "kuuuuuuuuuuuuuUk",
      "kkkkkkkkkkkkkkkk",
      ".kuuuUuuuuuUuUk.",
      ".kuGuUuuuuuGUUk.",
      ".kuuUUuuuuuUUUk.",
      "..kUUUUUUUUUUk..",
      "..kkkkkkkkkkkk..",
      "..kGgk....kGgk..",
      "...kk......kk...",
    ],
  }),
};

// --- fragments -------------------------------------------------------------------------
// A dungeon's creatures, a region's props: each set may live in a file of its own under
// ./props/ and `export default` a SpriteSheet. Merged here in path order; an id drawn twice is an error.
const PROP_SPRITES_FRAGMENTS = import.meta.glob("./props/*.ts", { eager: true, import: "default" }) as Record<string, SpriteSheet>;
for (const path of Object.keys(PROP_SPRITES_FRAGMENTS).sort()) {
  for (const [id, sprite] of Object.entries(PROP_SPRITES_FRAGMENTS[path])) {
    if (id in PROP_SPRITES) throw new Error(`art: "${id}" is drawn twice (again in ${path})`);
    PROP_SPRITES[id] = sprite;
  }
}
