// Unit sprites. Art is source code: one palette character per pixel, "." is transparent.
// Frames: down / up / side (side faces EAST, west is mirrored) + walk alternates down2 / up2 / side2 + dead.
// Light comes from the top-left; outlines are PAL.k. Every row is exactly w chars, every frame exactly h rows.
import { PAL } from "@/art/types";
import type { SpriteSheet } from "@/art/types";

export const UNIT_SPRITES: SpriteSheet = {
  // The hero. Plum travelling coat, mustard scarf, small tan backpack.
  jane: {
    w: 16,
    h: 20,
    ax: 8,
    ay: 18,
    palette: { ...PAL, h: "#3b2838", H: "#6a4c62", x: "#e89c88", c: "#8e4a86", C: "#5f2c5e", q: "#b673a8" },
    frames: {
      down: [
        ".....kkkkkk.....",
        "....khHHhhhk....",
        "...khHHhhhhhk...",
        "...khHhhhhhhk...",
        "...khhhhsshhk...",
        "...khsksskshk...",
        "...khsksskshk...",
        "...khxssssxhk...",
        "...khhsssshhk...",
        "...khyyyyyyhk...",
        "...kqccyYccCk...",
        "..kqCqcyYcCCck..",
        "..kqCqccccCCck..",
        "..kskCCCyCCksk..",
        "...kqcccCccCk...",
        "...kqcccCccCk...",
        "....kTTkkTTk....",
        "....kTekkTek....",
        "....kkkkkkkk....",
        "................",
      ],
      down2: [
        "................",
        ".....kkkkkk.....",
        "....khHHhhhk....",
        "...khHHhhhhhk...",
        "...khHhhhhhhk...",
        "...khhhhsshhk...",
        "...khsksskshk...",
        "...khsksskshk...",
        "...khxssssxhk...",
        "...khhsssshhk...",
        "...khyyyyyyhk...",
        "...kqccyYccCk...",
        "..kqCqcyYcCCck..",
        "..kqCqccccCCck..",
        "..kskCCCyCCksk..",
        "...kqcccCccCk...",
        "...kqcccCccCk...",
        "....kTTkkTTk....",
        "....kTekkkkk....",
        "....kkkk........",
      ],
      up: [
        ".....kkkkkk.....",
        "....khHHhhhk....",
        "...khHHhhhhhk...",
        "...khHhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "....khhkkhhk....",
        "...kqkkkkkkCk...",
        "..kqCkmmtTkCck..",
        "..kqCkmtYTkCck..",
        "..kskkttTTkksk..",
        "...kqckkkkcCk...",
        "...kqccccccCk...",
        "....kTTkkTTk....",
        "....kTekkTek....",
        "....kkkkkkkk....",
        "................",
      ],
      up2: [
        "................",
        ".....kkkkkk.....",
        "....khHHhhhk....",
        "...khHHhhhhhk...",
        "...khHhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "...khhhhhhhhk...",
        "....khhkkhhk....",
        "...kqkkkkkkCk...",
        "..kqCkmmtTkCck..",
        "..kqCkmtYTkCck..",
        "..kskkttTTkksk..",
        "...kqckkkkcCk...",
        "...kqccccccCk...",
        "....kTTkkTTk....",
        "....kkkkkTek....",
        "........kkkk....",
      ],
      side: [
        ".....kkkkkk.....",
        "....khHHhhhk....",
        "...khHHhhhhhk...",
        "...khHhhhhhhk...",
        "...khhhhhhhsk...",
        "...khhhhhsksk...",
        "...khhhhhsksS...",
        "...khhhhhxssk...",
        "...khhhhkssk....",
        "....khhyyyyk....",
        "..kkkkcqqcCk....",
        ".kmtTkcqqcCk....",
        ".kmYTkcqqcCk....",
        ".ktTTkckskCk....",
        "..kkkkcCCyCCk...",
        "....kqccccCCk...",
        "......kTTk......",
        "......kTeek.....",
        "......kkkkk.....",
        "................",
      ],
      side2: [
        "................",
        ".....kkkkkk.....",
        "....khHHhhhk....",
        "...khHHhhhhhk...",
        "...khHhhhhhhk...",
        "...khhhhhhhsk...",
        "...khhhhhsksk...",
        "...khhhhhsksS...",
        "...khhhhhxssk...",
        "...khhhhkssk....",
        "....khhyyyyk....",
        "..kkkkcqqcCk....",
        ".kmtTkcqqcCk....",
        ".kmYTkcqqcCk....",
        ".ktTTkckskCk....",
        "..kkkkcCCyCCk...",
        "....kqccccCCk...",
        "....kTTkkTTk....",
        "....kTkk.kTek...",
        "....kkk..kkkk...",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "..kkkkk.........",
        ".khHHhhkkkkkk...",
        ".khhhsskqcccckk.",
        ".khhksyycccCkTTk",
        ".khhssykcCCCkTTk",
        "..kkkkkkkkkkkkk.",
        "................",
      ],
    },
  },
  // Scruffy tan dog, darker near ear, one raised brow. It knows.
  dog: {
    w: 16,
    h: 14,
    ax: 8,
    ay: 12,
    palette: PAL,
    frames: {
      down: [
        "..kk........kk..",
        ".kTTk......kmtk.",
        ".kTTTkkkkkkmmtk.",
        ".kTTmmmmmmmmmtk.",
        "..kmmmmmmTTmtk..",
        "..kmmkmmmmkmtk..",
        "..kmmmwwwwmmtk..",
        "...kmwwkkwwmk...",
        "...kkmwwwwmkk...",
        "....ktmwwmtk.kk.",
        "....ktmkkmtkkmk.",
        "....kmmkkmmkkk..",
        "....kkkkkkkk....",
        "................",
      ],
      down2: [
        "..kk........kk..",
        ".kTTk......kmtk.",
        ".kTTTkkkkkkmmtk.",
        ".kTTmmmmmmmmmtk.",
        "..kmmmmmmTTmtk..",
        "..kmmkmmmmkmtk..",
        "..kmmmwwwwmmtk..",
        "...kmwwkkwwmk...",
        "...kkmwwwwmkk...",
        "....ktmwwmtk.kk.",
        "....ktmkkmtkkmk.",
        "....kmmkkkkkkk..",
        "....kkkk........",
        "................",
      ],
      up: [
        "..kk........kk..",
        ".ktmk......kTTk.",
        ".ktmmkkkkkkTTTk.",
        ".ktmmmmmmmmmTTk.",
        "..kmmmmmmmmmtk..",
        "..kmmmmmmmmmtk..",
        "..kmmmmmmmmttk..",
        "...kmmmkkmttk...",
        "...kkmkwwktkk...",
        "....ktkmmktk....",
        "....ktmkkmtk....",
        "....kmmkkmmk....",
        "....kkkkkkkk....",
        "................",
      ],
      up2: [
        "..kk........kk..",
        ".ktmk......kTTk.",
        ".ktmmkkkkkkTTTk.",
        ".ktmmmmmmmmmTTk.",
        "..kmmmmmmmmmtk..",
        "..kmmmmmmmmmtk..",
        "..kmmmmmmmmttk..",
        "...kmmmkkmttk...",
        "...kkmkwwktkk...",
        "....ktkmmktk....",
        "....ktmkkmtk....",
        "....kkkkkmmk....",
        "........kkkk....",
        "................",
      ],
      side: [
        "........kk......",
        ".......kTTkkk...",
        ".kk....kTTmmmkk.",
        "kmmk...kTmmmTmk.",
        "kmtk...kmmmwkmkk",
        ".ktk...kmmmmmmmk",
        ".ktkkkkkktmmwwwk",
        ".kttmmmmmttmkkkk",
        "..ktmmmmmmmtwk..",
        "..kTtttkkkttTk..",
        "..ktkkTk.ktkkTk.",
        "..kmkkTk.kmkkTk.",
        "..kkkkkk.kkkkkk.",
        "................",
      ],
      side2: [
        "........kk......",
        ".......kTTkkk...",
        ".kk....kTTmmmkk.",
        "kmmk...kTmmmTmk.",
        "kmtk...kmmmwkmkk",
        ".ktk...kmmmmmmmk",
        ".ktkkkkkktmmwwwk",
        ".kttmmmmmttmkkkk",
        "..ktmmmmmmmtwk..",
        "..kTtttkkkttTk..",
        "..ktkkTk.kTkktk.",
        ".kmkk.kTkkTk.kmk",
        ".kkk..kkkkkk.kkk",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "....kkkkkkk.kk..",
        ".kkkmmmmmmmkTTk.",
        "kmtmmmmmmmtmmkmk",
        "kkktkktkkkkttwkk",
        "..kkkkkk...kkkk.",
        "................",
      ],
    },
  },
  // Hunched bone-white skeleton in rags.
  skeleton: {
    w: 16,
    h: 20,
    ax: 8,
    ay: 18,
    palette: PAL,
    frames: {
      down: [
        "................",
        ".....kkkkkk.....",
        "....kwwwwWWk....",
        "...kwwwwwwWWk...",
        "...kwkkwwkkWk...",
        "...kwkkwwkkWk...",
        "...kwwwkkwWWk...",
        "....kwwwwwWk....",
        "....kwkwkwgk....",
        ".....kkkkkk.....",
        "...kkWkwwkWkk...",
        "..kwkkwkkwkkWk..",
        "..kwkeWwwWekWk..",
        "..kWkekkkkekgk..",
        "..kwkeeReeekWk..",
        "..kkkkeeRekkkk..",
        "....kwkkkkWk....",
        "...kwwk..kWgk...",
        "...kkkk..kkkk...",
        "................",
      ],
      down2: [
        "................",
        "................",
        ".....kkkkkk.....",
        "....kwwwwWWk....",
        "...kwwwwwwWWk...",
        "...kwkkwwkkWk...",
        "...kwkkwwkkWk...",
        "...kwwwkkwWWk...",
        "....kwwwwwWk....",
        "....kwkwkwgk....",
        ".....kkkkkk.....",
        "...kkWkwwkWkk...",
        "..kwkkwkkwkkWk..",
        "..kwkeWwwWekWk..",
        "..kWkekkkkekgk..",
        "..kwkeeReeekWk..",
        "..kkkkeeRekkkk..",
        "....kwkkkkWk....",
        "...kwwk.kkkk....",
        "...kkkk.........",
      ],
      up: [
        "................",
        ".....kkkkkk.....",
        "....kwwwwWWk....",
        "...kwwwwwwWWk...",
        "...kwwwgwwWWk...",
        "...kwwwwgWWWk...",
        "...kWwwwWWWgk...",
        "....kWWWWggk....",
        "....kkgggGkk....",
        ".....kkwWkk.....",
        "...kkWkwWkWkk...",
        "..kwkwkwWkWkWk..",
        "..kwkekwWkekWk..",
        "..kWkwkwWkWkgk..",
        "..kwkeeeReekWk..",
        "..kkkkeReekkkk..",
        "....kwkkkkWk....",
        "...kwwk..kWgk...",
        "...kkkk..kkkk...",
        "................",
      ],
      up2: [
        "................",
        "................",
        ".....kkkkkk.....",
        "....kwwwwWWk....",
        "...kwwwwwwWWk...",
        "...kwwwgwwWWk...",
        "...kwwwwgWWWk...",
        "...kWwwwWWWgk...",
        "....kWWWWggk....",
        "....kkgggGkk....",
        ".....kkwWkk.....",
        "...kkWkwWkWkk...",
        "..kwkwkwWkWkWk..",
        "..kwkekwWkekWk..",
        "..kWkwkwWkWkgk..",
        "..kwkeeeReekWk..",
        "..kkkkeReekkkk..",
        "....kwkkkkWk....",
        "....kkkk.kWgk...",
        ".........kkkk...",
      ],
      side: [
        "................",
        "......kkkkkk....",
        ".....kwwwwwWk...",
        "....kwwwwwwwWk..",
        "....kwwwwkkwWk..",
        "....kWwwwkkwwk..",
        "....kWWwwwwkk...",
        ".....kkWwwwwk...",
        "......kgkwkwk...",
        ".....kWkkkkk....",
        "....kwWkwwk.....",
        "...kewkkwkwk....",
        "...kewkwwkkwk...",
        "...kekkkwk.kwk..",
        "...keeRekk.kk...",
        "....kkeekk......",
        ".....kwkWk......",
        ".....kwkkWwk....",
        ".....kkkkkkk....",
        "................",
      ],
      side2: [
        "................",
        "................",
        "......kkkkkk....",
        ".....kwwwwwWk...",
        "....kwwwwwwwWk..",
        "....kwwwwkkwWk..",
        "....kWwwwkkwwk..",
        "....kWWwwwwkk...",
        ".....kkWwwwwk...",
        "......kgkwkwk...",
        ".....kWkkkkk....",
        "....kwWkwwk.....",
        "...kewkkwkwk....",
        "...kewkwwkkwk...",
        "...kekkkwk.kwk..",
        "...keeRekk.kk...",
        "....kkeekk......",
        "....kwkkkWk.....",
        "...kwkk..kWwk...",
        "...kkk...kkkk...",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        ".........kk.....",
        "..kkkk..kwWk.k..",
        ".kwwwWk.kkkkkwk.",
        "kwkwkwWkwkWkwkk.",
        "kwwkwwWkkwkkWwk.",
        "kwkwkWgkeeRekWk.",
        ".kkkkkkkkkkkkk..",
        "................",
      ],
    },
  },
  // Hooded bandit: green-brown cloak, red scarf over the face, dagger.
  bandit: {
    w: 16,
    h: 20,
    ax: 8,
    ay: 18,
    palette: { ...PAL, d: "#5f6a3c", D: "#3e4528", f: "#838c52" },
    frames: {
      down: [
        ".......kk.......",
        ".....kkffkk.....",
        "....kfffdddk....",
        "...kffddddddk...",
        "...kfdKKKKdDk...",
        "...kfKwKKwKDk...",
        "...kdrrrrrrDk...",
        "...kdRrrrrRDk...",
        "....kdRRRRDk....",
        "...kkddddddkk...",
        "..kffTdddddDDk..",
        "..kfddTddDddDk..",
        "..kfdddTdDddDk..",
        ".kskddDdTddDDk..",
        ".kgkddDdYTdDk...",
        ".kwkdkddkdDkk...",
        "..k.kTTkkTTk....",
        "....kTekkTek....",
        "....kkkkkkkk....",
        "................",
      ],
      down2: [
        "................",
        ".......kk.......",
        ".....kkffkk.....",
        "....kfffdddk....",
        "...kffddddddk...",
        "...kfdKKKKdDk...",
        "...kfKwKKwKDk...",
        "...kdrrrrrrDk...",
        "...kdRrrrrRDk...",
        "....kdRRRRDk....",
        "...kkddddddkk...",
        "..kffTdddddDDk..",
        "..kfddTddDddDk..",
        "..kfdddTdDddDk..",
        ".kskddDdTddDDk..",
        ".kgkddDdYTdDk...",
        ".kwkdkddkdDkk...",
        "..k.kTTkkTTk....",
        "....kTekkkkk....",
        "....kkkk........",
      ],
      up: [
        ".......kk.......",
        ".....kkffkk.....",
        "....kfffdddk....",
        "...kffddddddk...",
        "...kfdddddddk...",
        "...kfddddddDk...",
        "...kfddddddDk...",
        "...kddddddDDk...",
        "....kddddDDk....",
        "...kkdDDDDdkk...",
        "..kfdddddddDDk..",
        "..kfddddddddDk..",
        "..kfdddDddddDk..",
        "..kfdddDdddDDksk",
        "...kdddDdddDkkgk",
        "...kkdkdDkdDkkwk",
        "....kTTkkTTk..k.",
        "....kTekkTek....",
        "....kkkkkkkk....",
        "................",
      ],
      up2: [
        "................",
        ".......kk.......",
        ".....kkffkk.....",
        "....kfffdddk....",
        "...kffddddddk...",
        "...kfdddddddk...",
        "...kfddddddDk...",
        "...kfddddddDk...",
        "...kddddddDDk...",
        "....kddddDDk....",
        "...kkdDDDDdkk...",
        "..kfdddddddDDk..",
        "..kfddddddddDk..",
        "..kfdddDddddDk..",
        "..kfdddDdddDDksk",
        "...kdddDdddDkkgk",
        "...kkdkdDkdDkkwk",
        "....kTTkkTTk..k.",
        "....kkkkkTek....",
        "........kkkk....",
      ],
      side: [
        "......kk........",
        "....kkffkk......",
        "...kfffdddk.....",
        "..kffdddddDk....",
        "..kfddddKKKk....",
        "..kfdddKKwKk....",
        "..kfdddrrrrk....",
        "..kkdddRrrrk....",
        "...kkddRRRk.....",
        "...kfddddkk.....",
        "..kfdddddDk.....",
        "..kfddddddDk....",
        "..kfddddkskkk...",
        "..kfddddkkgwwk..",
        "..kdddddDkkkk...",
        "..kkdkddkDk.....",
        ".....kTTk.......",
        ".....kTeek......",
        ".....kkkkk......",
        "................",
      ],
      side2: [
        "................",
        "......kk........",
        "....kkffkk......",
        "...kfffdddk.....",
        "..kffdddddDk....",
        "..kfddddKKKk....",
        "..kfdddKKwKk....",
        "..kfdddrrrrk....",
        "..kkdddRrrrk....",
        "...kkddRRRk.....",
        "...kfddddkk.....",
        "..kfdddddDk.....",
        "..kfddddddDk....",
        "..kfddddkskkk...",
        "..kfddddkkgwwk..",
        "..kdddddDkkkk...",
        "..kkdkddkDk.....",
        "...kTTkkTTk.....",
        "...kTkk.kTek....",
        "...kkk..kkkk....",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "....kkkkkk......",
        "..kkfffdddkkk...",
        ".kffddddddddDkk.",
        "kfdKKrrdddddDDTk",
        "kfdKRrdddkdDDkTk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
    },
  },
  // Undead soldier: rusted helmet, grey-green skin, tattered tabard.
  soldier: {
    w: 16,
    h: 20,
    ax: 8,
    ay: 18,
    palette: { ...PAL, u: "#9a5a38", U: "#64382a", z: "#8fa888", Z: "#5f7a62" },
    frames: {
      down: [
        ".....kkkkkk.....",
        "....kugguuUk....",
        "...kuguuGuuUk...",
        "...kuuuuuuUUk...",
        "..kuuuGuuuUUUk..",
        "...kKKKUUKKKk...",
        "...kzyzUUzyZk...",
        "...kzzzzzzzZk...",
        "....kzkwkwZk....",
        "....kkGGGGkk....",
        "..kkgRrrrrRGkk..",
        "..kgGRrwwrRGGk..",
        "..kgGRrwwrRGGk..",
        "..kzkRrrrrRkzk..",
        "..kkkRrrRrRkkk..",
        "....kRkrRkRk....",
        "....kGGkkGGk....",
        "....kUukkUuk....",
        "....kkkkkkkk....",
        "................",
      ],
      down2: [
        "................",
        ".....kkkkkk.....",
        "....kugguuUk....",
        "...kuguuGuuUk...",
        "...kuuuuuuUUk...",
        "..kuuuGuuuUUUk..",
        "...kKKKUUKKKk...",
        "...kzyzUUzyZk...",
        "...kzzzzzzzZk...",
        "....kzkwkwZk....",
        "....kkGGGGkk....",
        "..kkgRrrrrRGkk..",
        "..kgGRrwwrRGGk..",
        "..kgGRrwwrRGGk..",
        "..kzkRrrrrRkzk..",
        "..kkkRrrRrRkkk..",
        "....kRkrRkRk....",
        "....kGGkkGGk....",
        "....kUukkkkk....",
        "....kkkk........",
      ],
      up: [
        ".....kkkkkk.....",
        "....kuoouuUk....",
        "...kuouuuuuUk...",
        "...kuuuuuuUUk...",
        "..kuuuuuuuUUUk..",
        "...kUuuuuuUUk...",
        "...kUUuuuUUUk...",
        "...kkGGGGGGkk...",
        "....kgGGGGGk....",
        "....kkGGGGkk....",
        "..kkgRrrrrRGkk..",
        "..kgGRrrrrRGGk..",
        "..kgGRrrrRRGGk..",
        "..kzkRrrrRRkzk..",
        "..kkkRrRrrRkkk..",
        "....kRkRrkRk....",
        "....kGGkkGGk....",
        "....kUukkUuk....",
        "....kkkkkkkk....",
        "................",
      ],
      up2: [
        "................",
        ".....kkkkkk.....",
        "....kuoouuUk....",
        "...kuouuuuuUk...",
        "...kuuuuuuUUk...",
        "..kuuuuuuuUUUk..",
        "...kUuuuuuUUk...",
        "...kUUuuuUUUk...",
        "...kkGGGGGGkk...",
        "....kgGGGGGk....",
        "....kkGGGGkk....",
        "..kkgRrrrrRGkk..",
        "..kgGRrrrrRGGk..",
        "..kgGRrrrRRGGk..",
        "..kzkRrrrRRkzk..",
        "..kkkRrRrrRkkk..",
        "....kRkRrkRk....",
        "....kGGkkGGk....",
        "....kkkkkUuk....",
        "........kkkk....",
      ],
      side: [
        ".....kkkkkk.....",
        "....kuoouuUk....",
        "...kuouuuuuUk...",
        "...kuuuuuuuUk...",
        "..kUuuuuuuuuUkk.",
        "...kUUKKKKKk....",
        "...kUUzzzyzk....",
        "...kUGzzzzzzk...",
        "....kGZzkwkk....",
        "....kkGGGkk.....",
        "....kRrrrrRk....",
        "....kRggGrRk....",
        "....kRgGGrRk....",
        "....kRkzzkRk....",
        "....kRrkkrRk....",
        "....kkRrkRkk....",
        "......kGGk......",
        "......kUuuk.....",
        "......kkkkk.....",
        "................",
      ],
      side2: [
        "................",
        ".....kkkkkk.....",
        "....kuoouuUk....",
        "...kuouuuuuUk...",
        "...kuuuuuuuUk...",
        "..kUuuuuuuuuUkk.",
        "...kUUKKKKKk....",
        "...kUUzzzyzk....",
        "...kUGzzzzzzk...",
        "....kGZzkwkk....",
        "....kkGGGkk.....",
        "....kRrrrrRk....",
        "....kRggGrRk....",
        "....kRgGGrRk....",
        "....kRkzzkRk....",
        "....kRrkkrRk....",
        "....kkRrkRkk....",
        "....kGGkkGGk....",
        "....kUkk.kUuk...",
        "....kkk..kkkk...",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        ".kkkk...........",
        "kuouUk.kkkkkk...",
        "kuuuUkkRrrrRGkk.",
        "kUuUUkzkRrwrGGUk",
        ".kkkkkkkRrRrkkUk",
        "....kkkkkkkkkkk.",
        "................",
      ],
    },
  },
  // The Headmaster: gaunt undead in gown and mortarboard, with cane.
  miniboss: {
    w: 20,
    h: 24,
    ax: 10,
    ay: 22,
    palette: { ...PAL, v: "#4a4260" },
    frames: {
      down: [
        "....................",
        "...kkkkkkkkkkkkkk...",
        "..kvvvvvvvvvvKKKKk..",
        "...kkkkKKKKKKkkkyk..",
        "......kKvKKKKk.kyk..",
        ".....kwwwwwwWWkkYk..",
        ".....kwkkwwkkWk.k...",
        ".....kwkrwwkrWk.....",
        ".....kWwwkkwwWk.....",
        "......kwwwwwWk......",
        "......kwkwkwgk......",
        ".kk....kkwwkk.......",
        "kyYkkkvKKwwKKKkk....",
        "kyYkvvKKKwwKKKKKk...",
        ".kTkvKkKKKKKKKkKk...",
        ".kTkvKkvKKKKKKkKk...",
        ".kTkvKkvKKKKKKkKk...",
        "kWWWkkkvKKKKKKkKk...",
        ".kTkkvKKKKKKKKkWWk..",
        ".kTk.kvKKKKKKKKkkk..",
        ".kTk.kvKKKKvKKKKk...",
        ".kTk.kvKKKKvKKKKk...",
        ".kTk.kKkKKkKKkKKk...",
        "..k...k.kk.kk.kk....",
      ],
      down2: [
        "....................",
        "...kkkkkkkkkkkkkk...",
        "..kvvvvvvvvvvKKKKk..",
        "...kkkkKKKKKKkkkyk..",
        "......kKvKKKKk.kyk..",
        ".....kwwwwwwWWk.kYk.",
        ".....kwkkwwkkWk..k..",
        ".....kwkrwwkrWk.....",
        ".....kWwwkkwwWk.....",
        "......kwwwwwWk......",
        "......kwkwkwgk......",
        ".kk....kkwwkk.......",
        "kyYkkkvKKwwKKKkk....",
        "kyYkvvKKKwwKKKKKk...",
        ".kTkvKkKKKKKKKkKk...",
        ".kTkvKkvKKKKKKkKk...",
        ".kTkvKkvKKKKKKkKk...",
        "kWWWkkkvKKKKKKkKk...",
        ".kTkkvKKKKKKKKkWWk..",
        ".kTk.kvKKKKKKKKkkk..",
        ".kTk.kvKKKKvKKKKk...",
        ".kTk.kvKKKKvKKKKk...",
        ".kTk.kKKkKKkKKkKk...",
        "..k...kk.kk.kk.k....",
      ],
      up: [
        "....................",
        "...kkkkkkkkkkkkkk...",
        "..kvvvvvvvvvvKKKKk..",
        "..kykkkKKKKKKkkkk...",
        "..kyk.kKvKKKKk......",
        "..kYkkwwwwwwWWk.....",
        "...k.kwwwwwwWWk.....",
        ".....kwwwwwWWWk.....",
        ".....kWwwwWWWgk.....",
        "......kWWWWWgk......",
        "......kkWWWgkk......",
        ".......kkKKkk....kk.",
        "....kkvKKKKKKKkkkyYk",
        "...kvvKKKKKKKKKKkyYk",
        "...kvKkKKKKKKKkKkTk.",
        "...kvKkvKKKKKKkKkTk.",
        "...kvKkvKKKKKKkKkTk.",
        "...kvKkvKKKKKKkkWWWk",
        "..kWWkvKKKKKKKKkkTk.",
        "..kkkvKKKKKKKKKkkTk.",
        "...kvKKKKvKKKKKkkTk.",
        "...kvKKKKvKKKKKkkTk.",
        "...kKkKKkKKkKKKkkTk.",
        "....k.kk.kk.kkk..k..",
      ],
      up2: [
        "....................",
        "...kkkkkkkkkkkkkk...",
        "..kvvvvvvvvvvKKKKk..",
        "..kykkkKKKKKKkkkk...",
        "..kyk.kKvKKKKk......",
        ".kYk.kwwwwwwWWk.....",
        "..k..kwwwwwwWWk.....",
        ".....kwwwwwWWWk.....",
        ".....kWwwwWWWgk.....",
        "......kWWWWWgk......",
        "......kkWWWgkk......",
        ".......kkKKkk....kk.",
        "....kkvKKKKKKKkkkyYk",
        "...kvvKKKKKKKKKKkyYk",
        "...kvKkKKKKKKKkKkTk.",
        "...kvKkvKKKKKKkKkTk.",
        "...kvKkvKKKKKKkKkTk.",
        "...kvKkvKKKKKKkkWWWk",
        "..kWWkvKKKKKKKKkkTk.",
        "..kkkvKKKKKKKKKkkTk.",
        "...kvKKKKvKKKKKkkTk.",
        "...kvKKKKvKKKKKkkTk.",
        "...kKKkKKkKKkKKkkTk.",
        "....kk.kk.kk.kk..k..",
      ],
      side: [
        "....................",
        "...kkkkkkkkkkkkkk...",
        "..kvvvvvvvvvvKKKKk..",
        "..kykkkKKKKKKkkkk...",
        "..kyk.kKvKKKKk......",
        "..kYkkwwwwwwwWk.....",
        "...k.kwwwwwkkwWk....",
        ".....kWwwwwkrwwk....",
        ".....kWWwwwwwkk.....",
        "......kkWwwwwwk.....",
        ".......kgkwkwkk.....",
        "......kkKkkkkk......",
        ".....kvKKKwwk....kk.",
        "....kvKKKKKwk...kyYk",
        "....kvKvvKKKk...kTk.",
        "....kvKvvKKKKk..kTk.",
        "....kvKkvvKKKKkWWWk.",
        "....kvKKkkkkkkk.kTk.",
        "....kvKKKKKKk...kTk.",
        "....kvKKKKKKk...kTk.",
        "...kvKKKKvKKKk..kTk.",
        "...kvKKKKvKKKk..kTk.",
        "...kKkKKkKKkKKk.kTk.",
        "....k.kk.kk.kk...k..",
      ],
      side2: [
        "....................",
        "...kkkkkkkkkkkkkk...",
        "..kvvvvvvvvvvKKKKk..",
        "..kykkkKKKKKKkkkk...",
        "..kyk.kKvKKKKk......",
        ".kYk.kwwwwwwwWk.....",
        "..k..kwwwwwkkwWk....",
        ".....kWwwwwkrwwk....",
        ".....kWWwwwwwkk.....",
        "......kkWwwwwwk.....",
        ".......kgkwkwkk.....",
        "......kkKkkkkk......",
        ".....kvKKKwwk....kk.",
        "....kvKKKKKwk...kyYk",
        "....kvKvvKKKk...kTk.",
        "....kvKvvKKKKk..kTk.",
        "....kvKkvvKKKKkWWWk.",
        "....kvKKkkkkkkk.kTk.",
        "....kvKKKKKKk...kTk.",
        "....kvKKKKKKk...kTk.",
        "...kvKKKKvKKKk..kTk.",
        "...kvKKKKvKKKk..kTk.",
        "...kKKkKKkKKkKk.kTk.",
        "....kk.kk.kk.k...k..",
      ],
      dead: [
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        "....................",
        ".......kkkkkkk......",
        "......kvvvvvKKk.....",
        "...kkkkkkKKKKkkk.kk.",
        "..kvvKKKKKKKKKKkkwWk",
        ".kvKKKvKKKKvKKKkwkwk",
        ".kKkKKkKKKkKKkKkkWgk",
        ".kkkkkkkkkkkkkkk.kk.",
        "....................",
      ],
    },
  },
  // Iron Knuckles: hulking rusted armour, huge fists, glowing eye slit.
  boss: {
    w: 24,
    h: 28,
    ax: 12,
    ay: 26,
    palette: { ...PAL, u: "#9a5a38", U: "#64382a" },
    frames: {
      down: [
        "........................",
        "....kk...kkkkkk...kk....",
        "....kWk.kgggGGGk.kWk....",
        ".....kWkggggGGGKkWk.....",
        "......kkggGGGGGKkk......",
        ".......kgkkkkkkKk.......",
        "..kkkk.kgoyooyoKk.kkkk..",
        ".kggggkkGkkkkkkKkkggGGk.",
        "kgggggGkGGkGkGkKkgggGGKk",
        "kgggGGGkkGGGGGKkkggGGGKk",
        "kggGuuGkggGGGGGKkgGuuGKk",
        "kGGuUUGkggGGuGGKkGuUUKKk",
        ".kGUUGkkgGGuUGGKkkUUKKk.",
        ".kkGGkkkGGGUuGGKkkkKKkk.",
        "..kgGk.kGGGGGGUKk.kGKk..",
        ".kkgGkkkGGGGGUUKkkkGKkk.",
        "kggggGGkkkkkkkkkkgggGGKk",
        "kgggGGGkUuUyyUuUkggGGGKk",
        "kggGGuUkkkkkkkkkkgGGuUKk",
        "kgkgkuUkGGGkkGGKkgkgkUKk",
        ".kkkkk.kgGGkkGGKk.kkkkk.",
        ".......kgGGkkGGKk.......",
        ".......kGuUkkGuKk.......",
        "......kkGGGkkGGKkk......",
        "......kggGGkkgGGKk......",
        "......kGGGUkkGGUKk......",
        "......kkkkkkkkkkkk......",
        "........................",
      ],
      down2: [
        "........................",
        "........................",
        "....kk...kkkkkk...kk....",
        "....kWk.kgggGGGk.kWk....",
        ".....kWkggggGGGKkWk.....",
        "......kkggGGGGGKkk......",
        ".......kgkkkkkkKk.......",
        "..kkkk.kgoyooyoKk.kkkk..",
        ".kggggkkGkkkkkkKkkggGGk.",
        "kgggggGkGGkGkGkKkgggGGKk",
        "kgggGGGkkGGGGGKkkggGGGKk",
        "kggGuuGkggGGGGGKkgGuuGKk",
        "kGGuUUGkggGGuGGKkGuUUKKk",
        ".kGUUGkkgGGuUGGKkkUUKKk.",
        ".kkGGkkkGGGUuGGKkkkKKkk.",
        "..kgGk.kGGGGGGUKk.kGKk..",
        ".kkgGkkkGGGGGUUKkkkGKkk.",
        "kggggGGkkkkkkkkkkgggGGKk",
        "kgggGGGkUuUyyUuUkggGGGKk",
        "kggGGuUkkkkkkkkkkgGGuUKk",
        "kgkgkuUkGGGkkGGKkgkgkUKk",
        ".kkkkk.kgGGkkGGKk.kkkkk.",
        ".......kgGGkkGGKk.......",
        ".......kGuUkkGuKk.......",
        "......kkGGGkkGGKkk......",
        "......kgGGGkkGGGKk......",
        "......kGGGKkkkkkkk......",
        "......kkkkkk............",
      ],
      up: [
        "........................",
        "....kk...kkkkkk...kk....",
        "....kWk.kgggGGGk.kWk....",
        ".....kWkggggGGGKkWk.....",
        "......kkggGGGGGKkk......",
        ".......kggGGGGGKk.......",
        "..kkkk.kgGGGGGGKk.kkkk..",
        ".kggggkkGGGGGGKKkkggGGk.",
        "kgggggGkkGGGGKKkkgggGGKk",
        "kgggGGGkkkkkkkkkkggGGGKk",
        "kggGuuGkggGKKGGKkgGuuGKk",
        "kGGuUUGkggGKKGGKkGuUUKKk",
        ".kGUUGkkgGGKKuGKkkUUKKk.",
        ".kkGGkkkGGGKKUGKkkkKKkk.",
        "..kgGk.kGGGGGGUKk.kGKk..",
        ".kkgGkkkGGGGGUUKkkkGKkk.",
        "kggggGGkkkkkkkkkkgggGGKk",
        "kgggGGGkUuUUuUuUkggGGGKk",
        "kggGGuUkkkkkkkkkkgGGuUKk",
        "kgkgkuUkGGGkkGGKkgkgkUKk",
        ".kkkkk.kgGGkkGGKk.kkkkk.",
        ".......kgGGkkGGKk.......",
        ".......kGuUkkGuKk.......",
        "......kkGGGkkGGKkk......",
        "......kggGGkkgGGKk......",
        "......kGGGUkkGGUKk......",
        "......kkkkkkkkkkkk......",
        "........................",
      ],
      up2: [
        "........................",
        "........................",
        "....kk...kkkkkk...kk....",
        "....kWk.kgggGGGk.kWk....",
        ".....kWkggggGGGKkWk.....",
        "......kkggGGGGGKkk......",
        ".......kggGGGGGKk.......",
        "..kkkk.kgGGGGGGKk.kkkk..",
        ".kggggkkGGGGGGKKkkggGGk.",
        "kgggggGkkGGGGKKkkgggGGKk",
        "kgggGGGkkkkkkkkkkggGGGKk",
        "kggGuuGkggGKKGGKkgGuuGKk",
        "kGGuUUGkggGKKGGKkGuUUKKk",
        ".kGUUGkkgGGKKuGKkkUUKKk.",
        ".kkGGkkkGGGKKUGKkkkKKkk.",
        "..kgGk.kGGGGGGUKk.kGKk..",
        ".kkgGkkkGGGGGUUKkkkGKkk.",
        "kggggGGkkkkkkkkkkgggGGKk",
        "kgggGGGkUuUUuUuUkggGGGKk",
        "kggGGuUkkkkkkkkkkgGGuUKk",
        "kgkgkuUkGGGkkGGKkgkgkUKk",
        ".kkkkk.kgGGkkGGKk.kkkkk.",
        ".......kgGGkkGGKk.......",
        ".......kGuUkkGuKk.......",
        "......kkGGGkkGGKkk......",
        "......kgGGGkkGGGKk......",
        "......kkkkkkkGGKKk......",
        "............kkkkkk......",
      ],
      side: [
        "............kk..........",
        ".........kkkkWk.........",
        "........kgggkWkk........",
        ".......kggggGkGGk.......",
        ".......kggGGGGGGk.......",
        ".......kgGGGkkkkk.......",
        ".......kgGGGkoyyk.......",
        "......kkGGGGkkkkk.......",
        ".....kggggGkGkGkKk......",
        "....kgggggGGGkkkkk......",
        "....kgggGGGGGGKkGKk.....",
        "....kggGuuGGGGKkGGKk....",
        "....kGGuUUuGGKKkGuKk....",
        ".....kGGUUGGKKkGGUKk....",
        "......kGGkgGKkGGGKk.....",
        "......kGGkgGKkGGUKk.....",
        "......kUukkkkkkkuUk.....",
        "......kGkggggGGGkKk.....",
        "......kGkgggGGGGkKk.....",
        "......kGkggGGGuUkKk.....",
        "......kGkgkgkgkUkKk.....",
        "......kkkkkkkkkkkkk.....",
        ".......kgGGGGGKk........",
        ".......kgGuUGGKk........",
        ".......kggGGGGGKk.......",
        ".......kGGGGGUKKk.......",
        ".......kkkkkkkkkk.......",
        "........................",
      ],
      side2: [
        "........................",
        "............kk..........",
        ".........kkkkWk.........",
        "........kgggkWkk........",
        ".......kggggGkGGk.......",
        ".......kggGGGGGGk.......",
        ".......kgGGGkkkkk.......",
        ".......kgGGGkoyyk.......",
        "......kkGGGGkkkkk.......",
        ".....kggggGkGkGkKk......",
        "....kgggggGGGkkkkk......",
        "....kgggGGGGGGKkGKk.....",
        "....kggGuuGGGGKkGGKk....",
        "....kGGuUUuGGKKkGuKk....",
        ".....kGGUUGGKKkGGUKk....",
        "......kGGkgGKkGGGKk.....",
        "......kGGkgGKkGGUKk.....",
        "......kUukkkkkkkuUk.....",
        "......kGkggggGGGkKk.....",
        "......kGkgggGGGGkKk.....",
        "......kGkggGGGuUkKk.....",
        "......kGkgkgkgkUkKk.....",
        "......kkkkkkkkkkkkk.....",
        ".......kgGGkGGKk........",
        "......kgGGkkkGGKk.......",
        ".....kgGGKk.kgGGGKk.....",
        ".....kGGKKk.kGGGKKk.....",
        ".....kkkkkk.kkkkkkk.....",
      ],
      dead: [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".........kkkkkk.........",
        "..kkkk..kgggGGGk..kkkk..",
        ".kgggGkkkgGGGGGKkkgGGGk.",
        "kgggGGGkkkkkkkkkkgGGGGKk",
        "kggGGuGkGKKKKKKGkGGuGGKk",
        "kgGGGUGkGGkGkGkKkGGUGKKk",
        "kGkGkGKkkUuUUuUkkGkGkKKk",
        ".kkkkkkkGGGkkGGGkkkkkkk.",
        ".......kkkkkkkkkk.......",
        "........................",
      ],
    },
  },
  // Undead bat. Frame 2 = wings down. Hovers (ay = h - 1).
  bat: {
    w: 16,
    h: 12,
    ax: 8,
    ay: 11,
    palette: PAL,
    frames: {
      down: [
        "................",
        ".kk...k..k...kk.",
        "kpPk.kPkkPk.kPPk",
        "kpPPkkPPPPkkPPPk",
        "kpPPPkrPPrkPPPPk",
        "kPkPPkPwwPkPPkPk",
        "kk.kPkPPPPkPk.kk",
        "....kkkPPkkk....",
        "......k..k......",
        "................",
        "................",
        "................",
      ],
      down2: [
        "................",
        "......k..k......",
        ".....kPkkPk.....",
        "..kkkkPPPPkkkk..",
        ".kpPPkrPPrkPPPk.",
        "kpPPPkPwwPkPPPPk",
        "kPPPkkPPPPkkPPPk",
        "kPPk.kkPPkk.kPPk",
        "kPk...kkkk...kPk",
        "kk............kk",
        "................",
        "................",
      ],
      up: [
        "................",
        ".kk...k..k...kk.",
        "kpPk.kPkkPk.kPPk",
        "kpPPkkPPPPkkPPPk",
        "kpPPPkPPPPkPPPPk",
        "kPkPPkPPPPkPPkPk",
        "kk.kPkPPPPkPk.kk",
        "....kkkPPkkk....",
        "......k..k......",
        "................",
        "................",
        "................",
      ],
      up2: [
        "................",
        "......k..k......",
        ".....kPkkPk.....",
        "..kkkkPPPPkkkk..",
        ".kpPPkPPPPkPPPk.",
        "kpPPPkPPPPkPPPPk",
        "kPPPkkPPPPkkPPPk",
        "kPPk.kkPPkk.kPPk",
        "kPk...kkkk...kPk",
        "kk............kk",
        "................",
        "................",
      ],
      side: [
        "................",
        "....kkk.........",
        "...kpPPkk...k.k.",
        "..kpPPPPPk.kPkPk",
        "..kPPPPPPPkPPPPk",
        "...kkPPPPPPPPrPk",
        ".....kkPPPPPPwk.",
        ".......kkPPPkk..",
        ".........kkk....",
        "................",
        "................",
        "................",
      ],
      side2: [
        "................",
        "................",
        "............k.k.",
        "....kkkkk..kPkPk",
        "...kPPPPPkkPPPPk",
        "...kkPPPPPPPPrPk",
        "..kpPkPPPPPPPwk.",
        "..kpPPkkkPPPkk..",
        "..kPPk...kkk....",
        "...kk...........",
        "................",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "...kk.kkkk.kk...",
        ".kkPPkPKKPkPPkk.",
        "kpPPPPkPPkPPPPPk",
      ],
    },
  },
  // Grey-brown rat, pink tail.
  rat: {
    w: 14,
    h: 10,
    ax: 7,
    ay: 8,
    palette: { ...PAL, a: "#8a7868", A: "#5e5048", c: "#e8a0a8", C: "#c07880" },
    frames: {
      down: [
        "..............",
        "..kk......kk..",
        ".kcCkkkkkkcCk.",
        ".kcCkaaaakcCk.",
        "..kkaaaaaAkk..",
        "..kakaaaakAk..",
        "..kaaaccaaAk..",
        ".kAaaawwaaaAk.",
        ".kkckkkkkkckkc",
        "..............",
      ],
      down2: [
        "..............",
        "..kk......kk..",
        ".kcCkkkkkkcCk.",
        ".kcCkaaaakcCk.",
        "..kkaaaaaAkk..",
        "..kakaaaakAk..",
        "..kaaaccaaAk..",
        ".kAaaawwaaaAk.",
        ".kckkkkkkkkckc",
        ".............c",
      ],
      up: [
        "..............",
        "..kk......kk..",
        ".kcCkkkkkkcCk.",
        ".kCCkaaaakCCk.",
        "..kkaaaaaAkk..",
        "..kaaaaaaaAk..",
        "..kaaaaaaaAk..",
        ".kAaaaaaaaAAk.",
        ".kkckkkcCkkckk",
        "......cC......",
      ],
      up2: [
        "..............",
        "..kk......kk..",
        ".kcCkkkkkkcCk.",
        ".kCCkaaaakCCk.",
        "..kkaaaaaAkk..",
        "..kaaaaaaaAk..",
        "..kaaaaaaaAk..",
        ".kAaaaaaaaAAk.",
        ".kkckkkCckkckk",
        ".......Cc.....",
      ],
      side: [
        "..............",
        "..............",
        "........kk....",
        "....kkkkcCk...",
        "..kkaaaakaakk.",
        ".kaaaaaaaakaak",
        ".kaaaaaaaaaack",
        "cCkAaaAAaaAkk.",
        "c..kck..kck...",
        "..............",
      ],
      side2: [
        "..............",
        "..............",
        "........kk....",
        "....kkkkcCk...",
        "..kkaaaakaakk.",
        ".kaaaaaaaakaak",
        ".kaaaaaaaaaack",
        ".ckAaaAAaaAkk.",
        "cC.kck...kck..",
        "..............",
      ],
      dead: [
        "..............",
        "..............",
        "..............",
        "..............",
        "..............",
        "..............",
        "...kckkkkck...",
        "..kkawwwwaakk.",
        "cCkAaaaaaaKack",
        "..............",
      ],
    },
  },
  // Jack-o-lantern on little root legs.
  pumpkin: {
    w: 16,
    h: 16,
    ax: 8,
    ay: 14,
    palette: { ...PAL, O: "#b05c20", q: "#f4b060" },
    frames: {
      down: [
        "................",
        ".......kkk......",
        "......kNnk......",
        "...kkkkNnkkkk...",
        "..kqqooOooOoOk..",
        ".kqqoooOoooOoOk.",
        ".kqooyoOooyooOk.",
        ".kqoyyyOoyyyoOk.",
        ".koooooyyooooOk.",
        ".koyyoyyyyoyyOk.",
        ".kOoyyyyoyyyoOk.",
        "..kOOooyyooOOk..",
        "...kkkOOOOkkk...",
        "...kek.kk.kek...",
        "..kkek....kekk..",
        "................",
      ],
      down2: [
        "................",
        ".......kkk......",
        "......kNnk......",
        "...kkkkNnkkkk...",
        "..kqqooOooOoOk..",
        ".kqqoooOoooOoOk.",
        ".kqooyoOooyooOk.",
        ".kqoyyyOoyyyoOk.",
        ".koooooyyooooOk.",
        ".koyyoyyyyoyyOk.",
        ".kOoyyyyoyyyoOk.",
        "..kOOooyyooOOk..",
        "...kkkOOOOkkk...",
        "..kek..kk..kek..",
        ".kkek......kekk.",
        "................",
      ],
      up: [
        "................",
        ".......kkk......",
        "......kNnk......",
        "...kkkkNnkkkk...",
        "..kqqooOooOoOk..",
        ".kqqoooOoooOoOk.",
        ".kqooooOoooOoOk.",
        ".kqooooOoooOoOk.",
        ".koooooOoooOoOk.",
        ".koooooOoooOoOk.",
        ".kOooooOoooOOOk.",
        "..kOOooOooOOOk..",
        "...kkkOOOOkkk...",
        "...kek.kk.kek...",
        "..kkek....kekk..",
        "................",
      ],
      up2: [
        "................",
        ".......kkk......",
        "......kNnk......",
        "...kkkkNnkkkk...",
        "..kqqooOooOoOk..",
        ".kqqoooOoooOoOk.",
        ".kqooooOoooOoOk.",
        ".kqooooOoooOoOk.",
        ".koooooOoooOoOk.",
        ".koooooOoooOoOk.",
        ".kOooooOoooOOOk.",
        "..kOOooOooOOOk..",
        "...kkkOOOOkkk...",
        "..kek..kk..kek..",
        ".kkek......kekk.",
        "................",
      ],
      side: [
        "................",
        ".......kkk......",
        "......kNnk......",
        "...kkkkNnkkkk...",
        "..kqqooOooOoOk..",
        ".kqqoooOoooOoOk.",
        ".kqooooOooyooOk.",
        ".kqooooOoyyyoOk.",
        ".kqooooOooooyyk.",
        ".koooooOoyoyyyk.",
        ".kOooooOooyyyOk.",
        "..kOOooOooOyOk..",
        "...kkkOOOOkkk...",
        "...kek.kk.kek...",
        "..kkek....kekk..",
        "................",
      ],
      side2: [
        "................",
        ".......kkk......",
        "......kNnk......",
        "...kkkkNnkkkk...",
        "..kqqooOooOoOk..",
        ".kqqoooOoooOoOk.",
        ".kqooooOooyooOk.",
        ".kqooooOoyyyoOk.",
        ".kqooooOooooyyk.",
        ".koooooOoyoyyyk.",
        ".kOooooOooyyyOk.",
        "..kOOooOooOyOk..",
        "...kkkOOOOkkk...",
        "..kek..kk..kek..",
        ".kkek......kekk.",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "....kk....kkk...",
        "..kkqokk.koOOkk.",
        ".kqooKKokkKKoOOk",
        ".kOoooookkoooOOk",
        "..kkkkkk..kkkkk.",
        "................",
      ],
    },
  },
  // Undead cactus. Stationary; frame 2 sways.
  cactus: {
    w: 16,
    h: 20,
    ax: 8,
    ay: 18,
    palette: { ...PAL, a: "#9ab06a", A: "#64824c", z: "#3e5634" },
    frames: {
      down: [
        "................",
        "....kkkkkkkk....",
        "...kaaaAAAAzk...",
        "...kaaAWAAAzk...",
        "...kakkAAkkzk...",
        ".k.kakkAAkkzk...",
        "kakkaAAAAAAzk...",
        "kAkkaAkwkwAzk.k.",
        "kAkkaWAkkkAzkkzk",
        "kAAAaAAAAAAzkkzk",
        ".kkkaAAWAAAzkkzk",
        "...kaAAAAAAzzzzk",
        "...kaAAAAAAzkkk.",
        "...kaAAWAAAzk...",
        "...kaAAAAAAzk...",
        "...kaWAAAAAzk...",
        "...kaAAAAWAzk...",
        "..kkzAAAAAzzkk..",
        "..kkkkkkkkkkkk..",
        "................",
      ],
      down2: [
        "................",
        ".....kkkkkkkk...",
        "....kaaaAAAAzk..",
        "....kaaAWAAAzk..",
        "....kakkAAkkzk..",
        ".k.kakkAAkkzk...",
        "kakkaAAAAAAzk...",
        "kAkkaAkwkwAzk.k.",
        "kAkkaWAkkkAzkkzk",
        "kAAAaAAAAAAzkkzk",
        ".kkkaAAWAAAzkkzk",
        "...kaAAAAAAzzzzk",
        "...kaAAAAAAzkkk.",
        "...kaAAWAAAzk...",
        "...kaAAAAAAzk...",
        "...kaWAAAAAzk...",
        "...kaAAAAWAzk...",
        "..kkzAAAAAzzkk..",
        "..kkkkkkkkkkkk..",
        "................",
      ],
      up: [
        "................",
        "....kkkkkkkk....",
        "...kaaaAAAAzk...",
        "...kaaAWAAAzk...",
        "...kaaAAAAAzk...",
        ".k.kaAAAWAAzk...",
        "kakkaAAAAAAzk...",
        "kAkkaAAAAAAzk.k.",
        "kAkkaWAAAAAzkkzk",
        "kAAAaAAAAAAzkkzk",
        ".kkkaAAWAAAzkkzk",
        "...kaAAAAAAzzzzk",
        "...kaAAAAAAzkkk.",
        "...kaAAWAAAzk...",
        "...kaAAAAAAzk...",
        "...kaWAAAAAzk...",
        "...kaAAAAWAzk...",
        "..kkzAAAAAzzkk..",
        "..kkkkkkkkkkkk..",
        "................",
      ],
      up2: [
        "................",
        ".....kkkkkkkk...",
        "....kaaaAAAAzk..",
        "....kaaAWAAAzk..",
        "....kaaAAAAAzk..",
        ".k.kaAAAWAAzk...",
        "kakkaAAAAAAzk...",
        "kAkkaAAAAAAzk.k.",
        "kAkkaWAAAAAzkkzk",
        "kAAAaAAAAAAzkkzk",
        ".kkkaAAWAAAzkkzk",
        "...kaAAAAAAzzzzk",
        "...kaAAAAAAzkkk.",
        "...kaAAWAAAzk...",
        "...kaAAAAAAzk...",
        "...kaWAAAAAzk...",
        "...kaAAAAWAzk...",
        "..kkzAAAAAzzkk..",
        "..kkkkkkkkkkkk..",
        "................",
      ],
      side: [
        "................",
        "....kkkkkkkk....",
        "...kaaaAAAAzk...",
        "...kaaAWAAAzk...",
        "...kaaAAAkkzk...",
        ".k.kaaAAAkkzk...",
        "kakkaAAAAAAzk...",
        "kAkkaAAAkwkwk.k.",
        "kAkkaWAAkkkkkkzk",
        "kAAAaAAAAAAzkkzk",
        ".kkkaAAWAAAzkkzk",
        "...kaAAAAAAzzzzk",
        "...kaAAAAAAzkkk.",
        "...kaAAWAAAzk...",
        "...kaAAAAAAzk...",
        "...kaWAAAAAzk...",
        "...kaAAAAWAzk...",
        "..kkzAAAAAzzkk..",
        "..kkkkkkkkkkkk..",
        "................",
      ],
      side2: [
        "................",
        ".....kkkkkkkk...",
        "....kaaaAAAAzk..",
        "....kaaAWAAAzk..",
        "....kaaAAAkkzk..",
        "..k.kaaAAAkkzk..",
        "kakkaAAAAAAzk...",
        "kAkkaAAAkwkwk.k.",
        "kAkkaWAAkkkkkkzk",
        "kAAAaAAAAAAzkkzk",
        ".kkkaAAWAAAzkkzk",
        "...kaAAAAAAzzzzk",
        "...kaAAAAAAzkkk.",
        "...kaAAWAAAzk...",
        "...kaAAAAAAzk...",
        "...kaWAAAAAzk...",
        "...kaAAAAWAzk...",
        "..kkzAAAAAzzkk..",
        "..kkkkkkkkkkkk..",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "......kk........",
        "..kk.kAzk.......",
        ".kaAkkAzkkkkkk..",
        ".kAAAAAzzAAAzzk.",
        "..kkkzAAAAzzkkk.",
        "....kkkkkkkk....",
        "................",
      ],
    },
  },
  // Undead flower: toothy bloom on a thorny stem. Stationary.
  flower: {
    w: 16,
    h: 18,
    ax: 8,
    ay: 16,
    palette: { ...PAL, f: "#a83264", F: "#6c1e4a", q: "#d05c90" },
    frames: {
      down: [
        ".....kk..kk.....",
        "...kkqfkkffkk...",
        "..kqffffffffFk..",
        "..kffkkkkkkfFk..",
        ".kqfkwkwwkwkfFk.",
        ".kffkkkkkkkkfFk.",
        ".kfFkwkwwkwkFFk.",
        "..kfFkkkkkkFFk..",
        "..kkFFfFFfFFkk..",
        "....kkkNnkkk....",
        ".kk...kNnk..kk..",
        "klnk.kkNnk.klnk.",
        "knnnkkNnkkknnNk.",
        ".kkknnNnnnNkkk..",
        "....kkkNnkkk....",
        "...keeeNneeek...",
        "...kkkkkkkkkk...",
        "................",
      ],
      down2: [
        "......kk..kk....",
        "....kkqfkkffkk..",
        "...kqffffffffFk.",
        "...kffkkkkkkfFk.",
        "..kqfkwkwwkwkfFk",
        "..kffkkkkkkkkfFk",
        "..kfFkwkwwkwkFFk",
        "...kfFkkkkkkFFk.",
        "...kkFFfFFfFFkk.",
        "....kkkNnkkk....",
        ".kk...kNnk..kk..",
        "klnk.kkNnk.klnk.",
        "knnnkkNnkkknnNk.",
        ".kkknnNnnnNkkk..",
        "....kkkNnkkk....",
        "...keeeNneeek...",
        "...kkkkkkkkkk...",
        "................",
      ],
      up: [
        ".....kk..kk.....",
        "...kkqfkkffkk...",
        "..kqffffffffFk..",
        "..kqfffFfffFFk..",
        ".kqfffFnNFffFFk.",
        ".kfffFnNNNFfFFk.",
        ".kfFffFNNFfFFFk.",
        "..kfFFfFFfFFFk..",
        "..kkFFfFFfFFkk..",
        "....kkkNnkkk....",
        ".kk...kNnk..kk..",
        "klnk.kkNnk.klnk.",
        "knnnkkNnkkknnNk.",
        ".kkknnNnnnNkkk..",
        "....kkkNnkkk....",
        "...keeeNneeek...",
        "...kkkkkkkkkk...",
        "................",
      ],
      up2: [
        "......kk..kk....",
        "....kkqfkkffkk..",
        "...kqffffffffFk.",
        "...kqfffFfffFFk.",
        "..kqfffFnNFffFFk",
        "..kfffFnNNNFfFFk",
        "..kfFffFNNFfFFFk",
        "...kfFFfFFfFFFk.",
        "...kkFFfFFfFFkk.",
        "....kkkNnkkk....",
        ".kk...kNnk..kk..",
        "klnk.kkNnk.klnk.",
        "knnnkkNnkkknnNk.",
        ".kkknnNnnnNkkk..",
        "....kkkNnkkk....",
        "...keeeNneeek...",
        "...kkkkkkkkkk...",
        "................",
      ],
      side: [
        ".....kk..kk.....",
        "...kkqfkkffkk...",
        "..kqfffffffffk..",
        "..kffffFkwkwkwk.",
        ".kqfffFkkkkkkk..",
        ".kfffFFkkkkkkk..",
        ".kffFFFkwkwkwk..",
        "..kfFFFFFFFFFk..",
        "..kkFFfFFfFFkk..",
        "....kkkNnkkk....",
        ".kk...kNnk..kk..",
        "klnk.kkNnk.klnk.",
        "knnnkkNnkkknnNk.",
        ".kkknnNnnnNkkk..",
        "....kkkNnkkk....",
        "...keeeNneeek...",
        "...kkkkkkkkkk...",
        "................",
      ],
      side2: [
        "......kk..kk....",
        "....kkqfkkffkk..",
        "...kqfffffffffk.",
        "...kffffFkwkwkwk",
        "..kqfffFkkkkkkk.",
        "..kfffFFkkkkkkk.",
        "..kffFFFkwkwkwk.",
        "...kfFFFFFFFFFk.",
        "...kkFFfFFfFFkk.",
        "....kkkNnkkk....",
        ".kk...kNnk..kk..",
        "klnk.kkNnk.klnk.",
        "knnnkkNnkkknnNk.",
        ".kkknnNnnnNkkk..",
        "....kkkNnkkk....",
        "...keeeNneeek...",
        "...kkkkkkkkkk...",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "......kkkk......",
        "..kkkkNnnkkkk...",
        ".kFfFkkNnkfFFk..",
        ".kkFFkeNneeFkk..",
        "...kkkkkkkkkk...",
        "................",
      ],
    },
  },
  // Coiled burial snake, raised head. Stationary turret.
  lurker: {
    w: 16,
    h: 16,
    ax: 8,
    ay: 14,
    palette: { ...PAL, v: "#8e9444", V: "#5e6632", z: "#3c4424", c: "#d8d0a0" },
    frames: {
      down: [
        "................",
        "......kkkk......",
        ".....kvvVVk.....",
        "....kvyVVyVk....",
        "....kvVVVVzk....",
        ".....kVccVk.....",
        ".....kkcckk.....",
        "......kcck......",
        "...kkkkcckkkk...",
        "..kvvvkcckVVzk..",
        ".kvVVVVkkVVVVzk.",
        ".kVkkkkkkkkkkzk.",
        "kvvVVVVVVVVVVzzk",
        "kVVcVVcVVcVVczzk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      down2: [
        "................",
        "......kkkk......",
        ".....kvvVVk.....",
        "....kvyVVyVk....",
        "....kvVVVVzk....",
        ".....kVccVk.....",
        ".....kkrrkk.....",
        "......krrk......",
        "...kkkkcckkkk...",
        "..kvvvkcckVVzk..",
        ".kvVVVVkkVVVVzk.",
        ".kVkkkkkkkkkkzk.",
        "kvvVVVVVVVVVVzzk",
        "kVVcVVcVVcVVczzk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      up: [
        "................",
        "......kkkk......",
        ".....kvvVVk.....",
        "....kvvVzVVk....",
        "....kvVzVzzk....",
        ".....kVVzVk.....",
        ".....kkVVkk.....",
        "......kvVk......",
        "...kkkkvVkkkk...",
        "..kvvvkvVkVVzk..",
        ".kvVVVVkkVVVVzk.",
        ".kVkkkkkkkkkkzk.",
        "kvvVVVVVVVVVVzzk",
        "kVVcVVcVVcVVczzk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      up2: [
        "................",
        ".......kkkk.....",
        "......kvvVVk....",
        ".....kvvVzVVk...",
        ".....kvVzVzzk...",
        "......kVVzVk....",
        "......kkVVkk....",
        "......kvVk......",
        "...kkkkvVkkkk...",
        "..kvvvkvVkVVzk..",
        ".kvVVVVkkVVVVzk.",
        ".kVkkkkkkkkkkzk.",
        "kvvVVVVVVVVVVzzk",
        "kVVcVVcVVcVVczzk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      side: [
        "................",
        ".......kkkkk....",
        "......kvvvVVkk..",
        ".....kvvVyVVVVk.",
        ".....kvVVVVzzkk.",
        ".....kVVkccckk..",
        ".....kvVckkkk...",
        "......kvVck.....",
        "...kkkkvVckkk...",
        "..kvvvvVVckVzk..",
        ".kvVVVVkkVVVVzk.",
        ".kVkkkkkkkkkkzk.",
        "kvvVVVVVVVVVVzzk",
        "kVVcVVcVVcVVczzk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      side2: [
        "................",
        ".......kkkkk....",
        "......kvvvVVkk..",
        ".....kvvVyVVVVk.",
        ".....kvVVVVzzkk.",
        ".....kVVkccckkrr",
        ".....kvVckkkk...",
        "......kvVck.....",
        "...kkkkvVckkk...",
        "..kvvvvVVckVzk..",
        ".kvVVVVkkVVVVzk.",
        ".kVkkkkkkkkkkzk.",
        "kvvVVVVVVVVVVzzk",
        "kVVcVVcVVcVVczzk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "....kkkkkkk.....",
        ".kkkvvVVVVzkkkk.",
        "kvVVcVVcVVcVkVVk",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
    },
  },
  // Stone cobra on a plinth, mossy. Same image all round.
  statue: {
    w: 16,
    h: 22,
    ax: 8,
    ay: 20,
    palette: PAL,
    frames: {
      down: [
        "................",
        "......kkkk......",
        ".....kWWggk.....",
        "....kWkggkGk....",
        "....kWggggGk....",
        "...kkWggggGkk...",
        "..kWWgGGGGggGk..",
        "..kWggggggggGk..",
        "..kWggGGGGggGk..",
        "..knggggggggGk..",
        "...knnGGGGgGk...",
        "....kkggggkk....",
        ".....kGGGGk.....",
        "...kkkggggkkk...",
        "..kWWggGGggGGk..",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      down2: [
        "................",
        "......kkkk......",
        ".....kWWggk.....",
        "....kWkggkGk....",
        "....kWggggGk....",
        "...kkWggggGkk...",
        "..kWWgGGGGggGk..",
        "..kWggggggggGk..",
        "..kWggGGGGggGk..",
        "..knggggggggGk..",
        "...knnGGGGgGk...",
        "....kkggggkk....",
        ".....kGGGGk.....",
        "...kkkggggkkk...",
        "..kWWggGGggGGk..",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      up: [
        "................",
        "......kkkk......",
        ".....kWWggk.....",
        "....kWkggkGk....",
        "....kWggggGk....",
        "...kkWggggGkk...",
        "..kWWgGGGGggGk..",
        "..kWggggggggGk..",
        "..kWggGGGGggGk..",
        "..knggggggggGk..",
        "...knnGGGGgGk...",
        "....kkggggkk....",
        ".....kGGGGk.....",
        "...kkkggggkkk...",
        "..kWWggGGggGGk..",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      up2: [
        "................",
        "......kkkk......",
        ".....kWWggk.....",
        "....kWkggkGk....",
        "....kWggggGk....",
        "...kkWggggGkk...",
        "..kWWgGGGGggGk..",
        "..kWggggggggGk..",
        "..kWggGGGGggGk..",
        "..knggggggggGk..",
        "...knnGGGGgGk...",
        "....kkggggkk....",
        ".....kGGGGk.....",
        "...kkkggggkkk...",
        "..kWWggGGggGGk..",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      side: [
        "................",
        "......kkkk......",
        ".....kWWggk.....",
        "....kWkggkGk....",
        "....kWggggGk....",
        "...kkWggggGkk...",
        "..kWWgGGGGggGk..",
        "..kWggggggggGk..",
        "..kWggGGGGggGk..",
        "..knggggggggGk..",
        "...knnGGGGgGk...",
        "....kkggggkk....",
        ".....kGGGGk.....",
        "...kkkggggkkk...",
        "..kWWggGGggGGk..",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      side2: [
        "................",
        "......kkkk......",
        ".....kWWggk.....",
        "....kWkggkGk....",
        "....kWggggGk....",
        "...kkWggggGkk...",
        "..kWWgGGGGggGk..",
        "..kWggggggggGk..",
        "..kWggGGGGggGk..",
        "..knggggggggGk..",
        "...knnGGGGgGk...",
        "....kkggggkk....",
        ".....kGGGGk.....",
        "...kkkggggkkk...",
        "..kWWggGGggGGk..",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        ".......kk.......",
        "...kk.kWgk.kkk..",
        "..kWgkkggGkgGGk.",
        "..kkkggGkkkgGkk.",
        ".kkkkkkkkkkkkkk.",
        ".kWWWWWWWWWWWgk.",
        ".kgggggggggggGk.",
        ".kgnggGggggNgGk.",
        ".knnlgggGgnNGGk.",
        ".kkkkkkkkkkkkkk.",
        "................",
      ],
    },
  },
  // Tomb spider: pale markings, a cluster of eyes.
  spider: {
    w: 16,
    h: 12,
    ax: 8,
    ay: 10,
    palette: PAL,
    frames: {
      down: [
        "................",
        "......kkkk......",
        ".kk..kKKKKk..kk.",
        "k..kkKWKKWKkk..k",
        "k.k.kKKWWKKk.k.k",
        "..k.kKWKKWKk.k..",
        ".k.kkkKKKKkkk.k.",
        ".k.kkGGGGGGkk.k.",
        "k..kkrKrrKrkk..k",
        "k.k...kwwk...k.k",
        "..k....kk....k..",
        "................",
      ],
      down2: [
        "................",
        ".kk...kkkk......",
        "k..k.kKKKKk.....",
        "k.k.kKWKKWKk.kk.",
        "..k.kKKWWKKkk..k",
        ".k.kkKWKKWKk.k.k",
        ".k.kkkKKKKkk.k..",
        "k..kkGGGGGGkk.k.",
        "k.k.krKrrKrkk.k.",
        "..k...kwwk..k..k",
        ".......kk....k.k",
        ".............k..",
      ],
      up: [
        "................",
        ".k....kkkk....k.",
        "k.k.kkGGGGkk.k.k",
        "k..k.kGGGGk.k..k",
        ".k.kkkKKKKkkk.k.",
        ".k.kKKWKKWKKk.k.",
        "k.k.kKKWWKKk.k.k",
        "k..kkKWKKWKkk..k",
        ".kk..kKKKKk..kk.",
        "k.....kkkk.....k",
        "................",
        "................",
      ],
      up2: [
        ".k..............",
        "k.k...kkkk......",
        "k..kkkGGGGkk..k.",
        ".k.k.kGGGGk..k.k",
        ".k.kkkKKKKkkk..k",
        "k.k.KKWKKWKKk.k.",
        "k..kkKKWWKKkk.k.",
        ".kk.kKWKKWKk.k.k",
        "k....kKKKKk.k..k",
        "......kkkk...kk.",
        "...............k",
        "................",
      ],
      side: [
        "................",
        "...kkkkk........",
        "..kKKWKKk.......",
        ".kKKWKWKKkkkkk..",
        ".kKKKWKKKkGGGGk.",
        ".kKKKKKKkkGGrGrk",
        "..kKKKKkkkkGGGwk",
        "...kkkkk.kkkkkk.",
        "..k..k.k..k..k..",
        ".k..k..k...k..k.",
        ".k..k..k...k..k.",
        "................",
      ],
      side2: [
        "................",
        "...kkkkk........",
        "..kKKWKKk.......",
        ".kKKWKWKKkkkkk..",
        ".kKKKWKKKkGGGGk.",
        ".kKKKKKKkkGGrGrk",
        "..kKKKKkkkkGGGwk",
        "...kkkkk.kkkkkk.",
        "...k.k..k.k..k..",
        "..k..k..k..k..k.",
        "..k.k...k..k...k",
        "................",
      ],
      dead: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "..k.k.k..k.k.k..",
        "..k.kk.kk.kk.k..",
        "...kkKKKKKKkk...",
        "..kKKWKKKKWKKk..",
        "...kkkkkkkkkk...",
        "................",
      ],
    },
  },
  // Boss snake HEAD only; the renderer draws the body tube. Anchor is the neck/centre.
  snake: {
    w: 16,
    h: 16,
    ax: 8,
    ay: 8,
    palette: { ...PAL, c: "#d8d0a0" },
    frames: {
      down: [
        ".....kkkkkk.....",
        "...kknnNNNNkk...",
        "..knnnyNNyNNNk..",
        ".klnnyYnNYyNNNk.",
        ".klnnnyYYyNNNNk.",
        "kkkknnnyyNNNkkkk",
        "kokonnnnNNNNokok",
        ".kooNnnnNNNNook.",
        ".klnnnnnNNNNNNk.",
        "..klnnnnNNNNNk..",
        "..klnnnnNNNNNk..",
        "...klnknNkNNk...",
        "...kknnnNNNkk...",
        "....kkkkkkkk....",
        "................",
        "................",
      ],
      down2: [
        ".....kkkkkk.....",
        "...kknnNNNNkk...",
        "..knnnyNNyNNNk..",
        ".klnnyYnNYyNNNk.",
        ".klnnnyYYyNNNNk.",
        "kkkknnnyyNNNkkkk",
        "kokonnnnNNNNokok",
        ".kooNnnnNNNNook.",
        ".klnnnnnNNNNNNk.",
        "..klnnnnNNNNNk..",
        "..klnnnnNNNNNk..",
        "...klnknNkNNk...",
        "...kknnnNNNkk...",
        "....kkkkkkkk....",
        ".......rr.......",
        "......r..r......",
      ],
      up: [
        "................",
        "................",
        "....kkkkkkkk....",
        "...kknnnNNNkk...",
        "...klnnnNNNNk...",
        "..klnnnnNNNNNk..",
        "..klnnnnNNNNNk..",
        ".klnnnnnNNNNNNk.",
        ".kNNNnnnNNNNNNk.",
        "kNkNnnnnNNNNNkNk",
        "kkkknnnyyNNNkkkk",
        ".klnnnyYYyNNNNk.",
        ".klnnyYnNYyNNNk.",
        "..knnnyNNyNNNk..",
        "...kknnNNNNkk...",
        ".....kkkkkk.....",
      ],
      up2: [
        "......r..r......",
        ".......rr.......",
        "....kkkkkkkk....",
        "...kknnnNNNkk...",
        "...klnnnNNNNk...",
        "..klnnnnNNNNNk..",
        "..klnnnnNNNNNk..",
        ".klnnnnnNNNNNNk.",
        ".kNNNnnnNNNNNNk.",
        "kNkNnnnnNNNNNkNk",
        "kkkknnnyyNNNkkkk",
        ".klnnnyYYyNNNNk.",
        ".klnnyYnNYyNNNk.",
        "..knnnyNNyNNNk..",
        "...kknnNNNNkk...",
        ".....kkkkkk.....",
      ],
      side: [
        "................",
        "................",
        "....kkkkk.......",
        "..kklnnnnkkk....",
        "kkklnnyYnnnnkk..",
        "kllnnyYnkkkknkk.",
        "knnnyYnnkokonnk.",
        "knnyYnnnnoonknk.",
        "knnnyYnnnnnnnnk.",
        "kNNNNyYNNkkkkkk.",
        "kNNNccccccccck..",
        "kkkNNccccccck...",
        "..kkNNNNNkkk....",
        "....kkkkk.......",
        "................",
        "................",
      ],
      side2: [
        "................",
        "................",
        "....kkkkk.......",
        "..kklnnnnkkk....",
        "kkklnnyYnnnnkk..",
        "kllnnyYnkkkknkk.",
        "knnnyYnnkokonnk.",
        "knnyYnnnnoonknk.",
        "knnnyYnnnnnnnnkr",
        "kNNNNyYNNkkkkkr.",
        "kNNNccccccccck.r",
        "kkkNNccccccck...",
        "..kkNNNNNkkk....",
        "....kkkkk.......",
        "................",
        "................",
      ],
      dead: [
        "................",
        "................",
        "....kkkkk.......",
        "..kklnnnnkkk....",
        "kkklnnyYnnnnkk..",
        "kllnnyYnkkkknkk.",
        "knnnyYnnnnnnnnk.",
        "knnyYnnnkkkkknk.",
        "knnnyYnnnnnnnnk.",
        "kNNNNyYNNkkkkkk.",
        "kNNNccccccccck..",
        "kkkNNccccccck...",
        "..kkNNNNNkkk....",
        "....kkkkk.......",
        "................",
        "................",
      ],
    },
  },
};

// --- seats ---------------------------------------------------------------------------
// Co-op: four people play one heroine with one name, so the only thing that tells them
// apart is the coat. Same drawing, three palette characters swapped: c coat, C shade,
// q highlight. Seat 0 keeps the plum. Colours are chosen to stay apart in the dark and
// under the mist, and to stay off the enemy reds.
export const SEAT_COATS: readonly { c: string; C: string; q: string }[] = [
  { c: "#8e4a86", C: "#5f2c5e", q: "#b673a8" }, // plum (the original)
  { c: "#2f7f8c", C: "#1c5260", q: "#5fb4bc" }, // teal
  { c: "#6b8a3a", C: "#435a24", q: "#9cba5e" }, // moss
  { c: "#b8752e", C: "#7c4a1c", q: "#e0a458" }, // ochre
];

export function seatSprite(sprite: string, seat: number): string {
  return `${sprite}@${seat}`;
}

/** The player sheets for seats 1..3: `jane@1` and so on. Seat 0 is the sheet as drawn. */
export function seatSheets(sprite = "jane"): SpriteSheet {
  const base = UNIT_SPRITES[sprite];
  const out: SpriteSheet = {};
  for (let seat = 1; seat < SEAT_COATS.length; seat++) {
    out[seatSprite(sprite, seat)] = { ...base, palette: { ...base.palette, ...SEAT_COATS[seat] } };
  }
  return out;
}
