[package]
name = "jane-render-soft"
description = "T0 backend: the CPU rasteriser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
jane-present.workspace = true

[dev-dependencies]
jane-core.workspace = true
jane-sim.workspace = true

[lints]
workspace = true
