// Butterfly Forest's furniture. Everything here is either a thing that grows when the light
// reaches it, or the light itself. Props that answer a verb have an `on` frame, which is the
// same thing after: the bud open, the bank green, the bridge mended, the lamp alight.

import type { Palette, SpriteSheet, SpriteSrc } from "@/art/types";
import { PAL } from "@/art/types";

const PX: Palette = {
  ...PAL,
  q: "#fff0bc", // sunlight
  Q: "#ffe08a", // sunlight, deeper
  c: "#b4d4ff", // moonlight
  C: "#7fa8e0", // moonlight, deeper
  v: "#6a4a30", // dry earth
  f: "#f4a0c0", // petal
  F: "#c06890", // petal shade
  h: "#2c6a38", // hedge dark
  x: "#0c0a12", // a hole in something
};

/** footH is the footprint height in 8 px cells. */
function prop(w: number, h: number, footH: number, frames: Record<string, string[]>): SpriteSrc {
  return { w, h, ax: 0, ay: h - footH * 8, palette: PX, frames };
}

const sheet: SpriteSheet = {
  bud: prop(8, 8, 1, {
    base: [
      "........",
      "...kk...",
      "..klnk..",
      "..klnk..",
      "..knNk..",
      "...kk...",
      "...kn...",
      "..kkk...",
    ],
    on: [
      "........",
      ".k.kk.k.",
      "kfkffkfk",
      ".kfFfFk.",
      "..kfyk..",
      "...kk...",
      "...kn...",
      "..kkk...",
    ],
  }),

  hedge_seed: prop(8, 8, 1, {
    base: [
      "........",
      "........",
      "........",
      "...kk...",
      "..kTTk..",
      "..kTtk..",
      "...kk...",
      "........",
    ],
    on: [
      "...kk...",
      "..klnk..",
      "..klnk..",
      "...kk...",
      "..kTTk..",
      "..kTtk..",
      "...kk...",
      "........",
    ],
  }),

  vine_root: prop(16, 8, 1, {
    base: [
      "................",
      "................",
      "....kkk...kk....",
      "...kTTtkkkTtk...",
      "..kTtvvTTtvvTk..",
      "...kkTvvTtkkk...",
      ".....kkkkk......",
      "................",
    ],
    on: [
      "..kl..kl...kl...",
      ".klnkklnk.klnk..",
      "..knkkknkkknk...",
      "...kTTtkkkTtk...",
      "..kTtnnTTtnnTk..",
      "...kkTnnTtkkk...",
      ".....kkkkk......",
      "................",
    ],
  }),

  summon_stone: prop(16, 16, 2, {
    base: [
      "................",
      "......kkkk......",
      ".....kggggk.....",
      "....kgggggGk....",
      "....kggwggGk....",
      "....kgwgwgGk....",
      "....kggwggGk....",
      "....kgggggGk....",
      "...kggwwwggGk...",
      "...kgggggggGk...",
      "...kggggggGGk...",
      "..kggggggggGGk..",
      "..kGGGGGGGGGGk..",
      "..kkkkkkkkkkkk..",
      "...eeeeeeeeee...",
      "................",
    ],
  }),

  forest_sunbeam: prop(16, 16, 2, {
    base: [
      "....qqqqqqqq....",
      "..qqQQQQQQQQqq..",
      ".qQQQQQQQQQQQQq.",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      "qQQQQQQQQQQQQQQq",
      ".qQQQQQQQQQQQQq.",
      "..qqQQQQQQQQqq..",
      "....qqqqqqqq....",
      "................",
    ],
  }),

  forest_moonbeam: prop(16, 16, 2, {
    base: [
      ".....cccccc.....",
      "...ccCCCCCCcc...",
      "..cCCCCCCCCCCc..",
      ".cCCCCCCCCCCCCc.",
      ".cCCCCCCCCCCCCc.",
      "cCCCCCCCCCCCCCCc",
      "cCCCCCCCCCCCCCCc",
      "cCCCCCCCCCCCCCCc",
      "cCCCCCCCCCCCCCCc",
      "cCCCCCCCCCCCCCCc",
      "cCCCCCCCCCCCCCCc",
      ".cCCCCCCCCCCCCc.",
      ".cCCCCCCCCCCCCc.",
      "..cCCCCCCCCCCc..",
      "...ccCCCCCCcc...",
      ".....cccccc.....",
    ],
  }),

  forest_dry_bank: prop(24, 16, 2, {
    base: [
      "........................",
      "........................",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kvvevvvvevvvvvvevvvvevvk",
      "kvvvvvvvvvvevvvvvvvvvvvk",
      "kevvvvevvvvvvvvvvevvvvek",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kvvvvevvvvvvvevvvvvvvvvk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kevvvvvvvevvvvvvvvvevvvk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "keeeeeeeeeeeeeeeeeeeeeek",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "........................",
    ],
    on: [
      "..k...k....k....k...k...",
      ".klk.klk..klk..klk.klk..",
      "kknkkknkkkknkkkknkkknkkk",
      "klnnlnnllnnllnnllnnllnnk",
      "knnlnnllnnllnnllnnllnnnk",
      "klnnllnnllnnllnnllnnlnnk",
      "knnllnnllnnllnnllnnllnnk",
      "klnnllnnllnnllnnllnnlnnk",
      "knnllnnllnnllnnllnnllnnk",
      "klnnllnnllnnllnnllnnlnnk",
      "knnllnnllnnllnnllnnllnnk",
      "kNNNNNNNNNNNNNNNNNNNNNNk",
      "kNNNNNNNNNNNNNNNNNNNNNNk",
      "keeeeeeeeeeeeeeeeeeeeeek",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "........................",
    ],
  }),

  forest_rockfall: prop(24, 16, 2, {
    base: [
      "........................",
      "....kkkk......kkkk......",
      "...kggGk....kkgggkk.....",
      "..kgggGGk..kgggggGGk....",
      ".kggggGGGkkggggggGGGk...",
      ".kgggGGGGkkgggGGGGGGk...",
      "kkggGGGGGkkggGGGGGGGkk..",
      "kggggGGGGkkgGGGGGGGGGk..",
      "kgggGGGGkkkkGGGGGGGGGkk.",
      "kkgGGGGkkggkkGGGGGGGGGk.",
      ".kkGGGkkgggGkkGGGGGGGGk.",
      "..kkkkkgggGGGkkGGGGGGGk.",
      "....kkkgGGGGGGkkGGGGGkk.",
      ".....kkkGGGGGGGkkGGGkk..",
      "......kkkkkkkkkkkkkkk...",
      "........................",
    ],
  }),

  forest_footbridge: prop(24, 16, 2, {
    base: [
      "........................",
      "kk....................kk",
      "kTk..................kTk",
      "kTkkkkkkkk....kkkkkkkkTk",
      "kTtttttttk....ktttttttTk",
      "kkkkkkkkkk....kkkkkkkkkk",
      "kmmmmmmmk......kmmmmmmmk",
      "kTmmmmmTk......kTmmmmmTk",
      "kmmmmmmmk......kmmmmmmmk",
      "kTmmmmmTk......kTmmmmmTk",
      "kmmmmmmmk......kmmmmmmmk",
      "kkkkkkkkk......kkkkkkkkk",
      "kTk...................Tk",
      "kTk...................Tk",
      "kk.....................k",
      "........................",
    ],
    on: [
      "........................",
      "kk....................kk",
      "kTk..................kTk",
      "kTkkkkkkkkkkkkkkkkkkkkTk",
      "kTttttttttttttttttttttTk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kTmmmmmTmmmmmmTmmmmmmTmk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kTmmmmmTmmmmmmTmmmmmmTmk",
      "kmmmmmmmmmmmmmmmmmmmmmmk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kTk...................Tk",
      "kTk...................Tk",
      "kk.....................k",
      "........................",
    ],
  }),

  forest_lamp_dead: prop(24, 24, 2, {
    base: [
      "........................",
      "........................",
      "........................",
      "........................",
      "...............kkkk.....",
      "..............kGxxGk....",
      "..............kxxxxk....",
      "..............kGxxGk....",
      "...............kkkk.....",
      "................kk......",
      "...............kGGk.....",
      "...........kkkkkGGk.....",
      "........kkkGGGGGGGk.....",
      "....kkkkGGGGkkkkkkk.....",
      "..kkGGGGkkkk............",
      ".kGGGkkk................",
      ".kkkk...................",
      "........................",
      "..eeee..................",
      ".eeeeeee................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
    on: [
      "........................",
      "........................",
      "........................",
      "........................",
      "...............kkkk.....",
      "..............kGqqGk....",
      "..............kqyyqk....",
      "..............kGqqGk....",
      "...............kkkk.....",
      "................kk......",
      "...............kGGk.....",
      "...........kkkkkGGk.....",
      "........kkkGGGGGGGk.....",
      "....kkkkGGGGkkkkkkk.....",
      "..kkGGGGkkkk............",
      ".kGGGkkk................",
      ".kkkk...................",
      "........................",
      "..eeee..................",
      ".eeeeeee................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  }),

  dry_tree: prop(24, 24, 2, {
    base: [
      "........................",
      ".....k.........k........",
      "....kTk.......kTk.......",
      "...kTTk.k.k..kTTk.......",
      "...kTk.kTkTk.kTk....k...",
      "....kTkkTkTkkTk....kTk..",
      ".....kTTTkTTTk....kTTk..",
      "......kTTkTTk....kTTk...",
      ".......kTTTk....kTTk....",
      "........kTTk..kkTTk.....",
      "........kTTkkkTTTk......",
      ".........kTTTTTTk.......",
      ".........kTTTTTk........",
      ".........kTTTTk.........",
      ".........kTTTTk.........",
      ".........kTTTTk.........",
      ".........kTTTTk.........",
      ".........kTTTTk.........",
      "........kTTTTTTk........",
      ".......kTTTTTTTTk.......",
      "......kkTTTTTTTTkk......",
      ".....keekkkkkkkkeek.....",
      "....keeeeeeeeeeeeeek....",
      "........................",
    ],
    on: [
      "........................",
      ".....k..................",
      "....kkk.......kkk.......",
      "...kkkk.......kkk.......",
      "...kkk.k.k...kkk........",
      "....kkkkkkk..kk.........",
      ".....kkkkkkkk...........",
      "......kkkkkk............",
      ".......kkkkk............",
      "........kkkk..kkkk......",
      "........kkkkkkkkk.......",
      ".........kkkkkkk........",
      ".........kkkkkk.........",
      ".........kkkkk..........",
      ".........kkkkk..........",
      ".........kkkkk..........",
      ".........kkkkk..........",
      ".........kkkkk..........",
      "........kkkkkkk.........",
      ".......kkkkkkkkk........",
      "......kkkkkkkkkkk.......",
      ".....keekkkkkkkkeek.....",
      "....keeeeeeeeeeeeeek....",
      "........................",
    ],
  }),

  forest_cases: prop(16, 16, 2, {
    base: [
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kTkkkkkkkkkkkkTk",
      "kTkbbbkkbbbkkbTk",
      "kTkbfbkkbFbkkbTk",
      "kTkbbbkkbbbkkbTk",
      "kTkkkkkkkkkkkkTk",
      "kTwwwkkwwwkkwwTk",
      "kTkkkkkkkkkkkkTk",
      "kTkbbbkkbbbkkbTk",
      "kTkbFbkkbfbkkbTk",
      "kTkbbbkkbbbkkbTk",
      "kTkkkkkkkkkkkkTk",
      "kTwwwkkwwwkkwwTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
    ],
  }),
};

export default sheet;
