// The Castle Museum's furniture. Everything here is either on a plinth or holding a door shut.
// Light from the top-left, outline PAL.k, and the same hand as the rest of the sheets.
//
// The exhibits get a `base` only: the light does not change them, it changes whether they are
// there at all (the breaker hides the prop and stands a unit up in its place). The things that
// answer a verb get an `on` frame, which is the same thing after the verb has been used on it.

import type { Palette, SpriteSheet, SpriteSrc } from "@/art/types";
import { PAL } from "@/art/types";

const PX: Palette = {
  ...PAL,
  x: "#0c0a12", // the inside of a case
  d: "#6a707c", // polished steel
  D: "#3f4550", // steel in shadow
  u: "#b0603a", // rust, tarnish, brass gone green-brown
  v: "#d8cfc0", // limestone
  V: "#a89c88", // limestone in shadow
  q: "#e8d8b0", // wax
  Q: "#b8a478", // wax in shadow
  f: "#c87a3c", // fox
  F: "#8a4a22", // fox in shadow
  z: "#7e8a94", // painted steel: shutters, lamp brackets
  Z: "#4c565e",
};

/** footH is the footprint height in 8 px cells: a tall prop rises upward out of its footprint. */
function prop(w: number, h: number, footH: number, frames: Record<string, string[]>): SpriteSrc {
  return { w, h, ax: 0, ay: h - footH * 8, palette: PX, frames };
}

/** One empty suit of armour, eight pixels wide. Three of them make a rail. */
const SUIT = [
  "........",
  "..kkkk..",
  ".kdddkk.",
  ".kdxxdk.",
  ".kdddkk.",
  "..kddk..",
  ".kddddk.",
  "kdddgddk",
  "kddgggdk",
  "kdddgddk",
  ".kddddk.",
  ".kdDDdk.",
  ".kd..dk.",
  ".kd..dk.",
  ".kD..Dk.",
];

const PLINTH_24 = [
  "kkkkkkkkkkkkkkkkkkkkkkkk",
  "kvvvvvvvvvvvvvvvvvvvvvvk",
  "kvVVVVVVVVuuVVVVVVVVVVvk",
  "kVVVVVVVVVVVVVVVVVVVVVVk",
  "kkkkkkkkkkkkkkkkkkkkkkkk",
];

const PLINTH_16 = [
  "kkkkkkkkkkkkkkkk",
  "kvvvvvvvvvvvvvvk",
  "kvVVVVuuVVVVVVvk",
  "kVVVVVVVVVVVVVVk",
  "kkkkkkkkkkkkkkkk",
];

const sheet: SpriteSheet = {
  // --- exhibits: solid in the light, gone in the dark ------------------------------------
  museum_exhibit_armour: prop(24, 20, 2, {
    base: [...SUIT.map((r) => r + r + r), ...PLINTH_24],
  }),

  museum_exhibit_waxwork: prop(16, 20, 2, {
    base: [
      "................",
      "......kkkk......",
      ".....kqqqqk.....",
      ".....kqQkqk.....",
      ".....kqqqqk.....",
      "......kqqk......",
      "....kkqqqqkk....",
      "...kqqqQQqqqk...",
      "...kqqQQQQqqk...",
      "...kqqqQQqqqk...",
      "...kqqqqqqqqk...",
      "....kqqqqqqk....",
      "....kqk..kqk....",
      "....kqk..kqk....",
      "....kQk..kQk....",
      ...PLINTH_16,
    ],
  }),

  museum_exhibit_fox: prop(16, 16, 2, {
    base: [
      "................",
      "...........kk...",
      "..........kffk..",
      "..kkkkkkkkkffk..",
      ".kffffffffffwk..",
      ".kfffffffffFFk..",
      ".kFffffffffffk..",
      ".kFkkFkkFkkFk...",
      "..k...k...k.....",
      "................",
      "................",
      ...PLINTH_16,
    ],
  }),

  // --- the painted-over arch: plaster, and a draught through it ---------------------------
  museum_arch: prop(24, 20, 2, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kvvkvvvvkvvvvkvvvvkvvvvk",
      "kvvkvvvvkvvvvkvvvvkvvvvk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kvvvvkvvvvkvvvvkvvvvkvvk",
      "kvvvvkvvvvkvvvvkvvvvkvvk",
      "kvvvvvvvvvvvvvvvvvvvvvvk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kvvkvvvvkvvvvkvvvvkvvvvk",
      "kvvkvvvvkvVVVkvvvvkvvvvk",
      "kvvvvvvvvVVVVVvvvvvvvvvk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kvvvvkvvvvkvvvvkvvvvkvvk",
      "kvvvvkvvvvkvvvvkvvvvkvvk",
      "kVVVVVVVVVVVVVVVVVVVVVVk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kVVVVVVVVVVVVVVVVVVVVVVk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  // --- a plinth is a plate: it is down while something stands on it -----------------------
  museum_plinth: prop(16, 16, 2, {
    base: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kvvvvvvvvvvvvvvk",
      "kvvvvvvvvvvvvvvk",
      "kvvvvuuuuvvvvvvk",
      "kVVVVVVVVVVVVVVk",
      "kkkkkkkkkkkkkkkk",
      ".kVVVVVVVVVVVVk.",
      ".kVVVVVVVVVVVVk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
    on: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kvvvvvvvvvvvvvvk",
      "kvvvvuuuuvvvvvvk",
      "kVVVVVVVVVVVVVVk",
      "kkkkkkkkkkkkkkkk",
      ".kVVVVVVVVVVVVk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  }),

  // --- the breaker: a grey box on the wall with one handle --------------------------------
  museum_breaker: prop(8, 16, 1, {
    base: [
      "........",
      "..kkkk..",
      "..kzzk..",
      "..kzZk..",
      ".kkzzkk.",
      ".kzzzzk.",
      ".kzyyzk.",
      ".kzyyzk.",
      ".kzzzzk.",
      ".kzZZzk.",
      ".kkzzkk.",
      "..kzzk..",
      "..kZZk..",
      "..kkkk..",
      "........",
      "........",
    ],
    on: [
      "........",
      "..kkkk..",
      "..kzzk..",
      "..kzZk..",
      ".kkzzkk.",
      ".kzzzzk.",
      ".kzZZzk.",
      ".kzZZzk.",
      ".kzzzzk.",
      ".kzyyzk.",
      ".kkzzkk.",
      "..kzzk..",
      "..kZZk..",
      "..kkkk..",
      "........",
      "........",
    ],
  }),

  // --- a gallery lamp on its bracket ------------------------------------------------------
  museum_gallery_lamp: prop(8, 16, 1, {
    base: [
      "........",
      "..kkkk..",
      ".kzzzzk.",
      ".kZzzZk.",
      "..kzzk..",
      "..kzzk..",
      ".kkzzkk.",
      "kywwwyk.",
      "kywwwyk.",
      ".kyyyk..",
      "..kkk...",
      "...k....",
      "...k....",
      "...k....",
      "..kkk...",
      "........",
    ],
  }),

  // --- power shutters: the gate rows a state edge uses ------------------------------------
  museum_shutter_h: prop(24, 12, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kzzzzzzzzzzzzzzzzzzzzzzk",
      "kZZZZZZZZZZZZZZZZZZZZZZk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kzzzzzzzzzzzzzzzzzzzzzzk",
      "kZZZZZZZZZZZZZZZZZZZZZZk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kzzzzzzzzzzzzzzzzzzzzzzk",
      "kZZZZZZZZZZZZZZZZZZZZZZk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kZzzzzzzzzzzzzzzzzzzzzZk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  museum_shutter_v: prop(8, 24, 3, {
    base: [
      "kkkkkkkk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kzzkzzZk",
      "kkkkkkkk",
    ],
  }),

  // --- an armour on its rail, standing across a doorway -----------------------------------
  museum_armour_door_h: prop(24, 16, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kDDDDDDDDDDDDDDDDDDDDDDk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "..kkkk....kkkk....kkkk..",
      ".kdxxdk..kdxxdk..kdxxdk.",
      ".kddddk..kddddk..kddddk.",
      "..kddk....kddk....kddk..",
      "kdddgddkkdddgddkkdddgddk",
      "kddgggdkkddgggdkkddgggdk",
      "kdddgddkkdddgddkkdddgddk",
      ".kddddk..kddddk..kddddk.",
      ".kdDDdk..kdDDdk..kdDDdk.",
      ".kd..dk..kd..dk..kd..dk.",
      ".kD..Dk..kD..Dk..kD..Dk.",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kVVVVVVVVVVVVVVVVVVVVVVk",
    ],
  }),

  museum_armour_door_v: prop(8, 24, 3, {
    base: [
      "kkkkkkkk",
      "kkdxxdkk",
      "kkddddkk",
      "kkkddkkk",
      "kdddgddk",
      "kddgggdk",
      "kdddgddk",
      "kkddddkk",
      "kkd..dkk",
      "kkkkkkkk",
      "kkdxxdkk",
      "kkddddkk",
      "kkkddkkk",
      "kdddgddk",
      "kddgggdk",
      "kdddgddk",
      "kkddddkk",
      "kkd..dkk",
      "kkkkkkkk",
      "kkdxxdkk",
      "kkddddkk",
      "kdddgddk",
      "kddgggdk",
      "kkkkkkkk",
    ],
  }),

  // --- dressing: a case with something in it ----------------------------------------------
  museum_case: prop(16, 20, 2, {
    base: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kTxxxxxxxxxxxxTk",
      "kTxxxxxxxxxxxxTk",
      "kTxxxxwwxxxxxxTk",
      "kTxxxwwwwxxxxxTk",
      "kTxxxwWWwxxxxxTk",
      "kTxxxxWWxxxxxxTk",
      "kTxxxxxxxxxxxxTk",
      "kTxxxxxxxxxxxxTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "kmttttttttttttmk",
      "kTttttttttttttTk",
      "kTtk........ktTk",
      "kTtk........ktTk",
      "kTTk........kTTk",
      "kkkk........kkkk",
    ],
  }),

  // --- the cloakroom stove -----------------------------------------------------------------
  museum_stove: prop(16, 16, 2, {
    base: [
      "................",
      "....kkkkkkk.....",
      "....kGGGGGk.....",
      "....kGggggk.....",
      "kkkkkkkkkkkkkkkk",
      "kGggggggggggggGk",
      "kGgkkkkkkkkkkgGk",
      "kGgkoyyoooookgGk",
      "kGgkyrryyoookgGk",
      "kGgkoyyoooookgGk",
      "kGgkkkkkkkkkkgGk",
      "kGggggggggggggGk",
      "kGGGGGGGGGGGGGGk",
      "kkkkkkkkkkkkkkkk",
      ".kGk......kGk...",
      ".kkk......kkk...",
    ],
  }),

  // --- the portrait with the face scratched out --------------------------------------------
  museum_portrait: prop(16, 20, 2, {
    base: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kyYYYYYYYYYYYYyk",
      "kYkkkkkkkkkkkkYk",
      "kYkePPPPPPPPekYk",
      "kYkeePkkkkPeekYk",
      "kYkeePkxxkPeekYk",
      "kYkeePkkxkPeekYk",
      "kYkeePxkkxPeekYk",
      "kYkePPkxkkPPekYk",
      "kYkePPPxxxPPekYk",
      "kYkeePPPPPPeekYk",
      "kYkkkkkkkkkkkkYk",
      "kyYYYYYYYYYYYYyk",
      "kkkkkkkkkkkkkkkk",
      ".kYk........kYk.",
      ".kkk........kkk.",
      "................",
      "................",
    ],
  }),

  // --- the damaged cubicle door: `on` is the same door, hanging straight --------------------
  museum_cubicle_door: prop(16, 20, 2, {
    base: [
      "................",
      "................",
      "...kkkk.........",
      "..kttttkk.......",
      "..kmttttkk......",
      "..kmtttttkk.....",
      "kkkmttttttkk....",
      "ktkmtttttttk....",
      "ktkmtttyttttk...",
      "ktkmttttttttk...",
      "ktkTtttttttTk...",
      "ktkTttttttTk....",
      "ktkTtttttTk.....",
      "ktkTttttTk......",
      "ktkTtttTk.......",
      "ktkTttTk........",
      "ktkTtTk.........",
      "ktkkkk..........",
      "kkk.............",
      "................",
    ],
    on: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kTttttttttttttTk",
      "kTmmmmmmmmmmmmTk",
      "kTmttttttttttmTk",
      "kTmttttttttttmTk",
      "kTmttttttttttmTk",
      "kTmtttttttyttmTk",
      "kTmttttttttttmTk",
      "kTmttttttttttmTk",
      "kTmttttttttttmTk",
      "kTmttttttttttmTk",
      "kTmmmmmmmmmmmmTk",
      "kTttttttttttttTk",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
      "................",
    ],
  }),

  // --- what a blast leaves, and what it opens ----------------------------------------------
  rubble: prop(24, 16, 2, {
    base: [
      "................k.......",
      ".......kkk.....kvk......",
      "......kvvvk...kvVVk.....",
      ".....kvVVvvk.kvvVVk..kk.",
      "..kk.kvVVVvkkvVVVk..kvvk",
      ".kvvkkVVVVVkkVVVVkkkvVVk",
      "kvVVvkVVVVVVVVVVVkvVVVVk",
      "kVVVVkkVVVVVVVVVkkVVVVVk",
      "kkVVVVkVVVVVVVVVkVVVVkkk",
      "kVVVVVkkVVVVVVVkkVVVVVVk",
      "kVVVVVVkVVVVVVVkVVVVVVVk",
      "kkVVVVVkkVVVVVkkVVVVVkkk",
      "kVVVVVVVkVVVVVkVVVVVVVVk",
      "kVVVVVVVVVVVVVVVVVVVVVVk",
      "kVVVVVVVVVVVVVVVVVVVVVVk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  cracked_wall_h: prop(24, 16, 1, {
    base: [
      "kkkkkkkkkkkkkkkkkkkkkkkk",
      "kvvvvvvvvkvvvvvvvvvvvvvk",
      "kvvvvvvvkvvvvvvvvvvvvvvk",
      "kvvvvvvkvvvvvvvvvvvvvvvk",
      "kkkkkkkvkkkkkkkkvkkkkkkk",
      "kvvvvvvkvvvvvvvkvvvvvvvk",
      "kvvvvvvvkvvvvvkvvvvvvvvk",
      "kvvvvvvvvkvvvkvvvvvvvvvk",
      "kkkkkkkkkkkvkkkkkkkkkkkk",
      "kvvvvvvvvvvkvvvvvvvvvvvk",
      "kvvvvvvvvvkvvvvvvvvvvvvk",
      "kvvvvvvvvkvvvvvvvvvvvvvk",
      "kkkkkkkkvkkkkkkkkkkkkkkk",
      "kVVVVVVkVVVVVVVVVVVVVVVk",
      "kVVVVVVVVVVVVVVVVVVVVVVk",
      "kkkkkkkkkkkkkkkkkkkkkkkk",
    ],
  }),

  cracked_wall_v: prop(8, 24, 3, {
    base: [
      "kkkkkkkk",
      "kvvkvvvk",
      "kvvkvvvk",
      "kvvvkvvk",
      "kkkkvkkk",
      "kvvvkvvk",
      "kvvvkvvk",
      "kvvkvvvk",
      "kkkvkkkk",
      "kvvkvvvk",
      "kvvkvvvk",
      "kvvvkvvk",
      "kkkkvkkk",
      "kvvvkvvk",
      "kvvvvkvk",
      "kvvvvkvk",
      "kkkkkvkk",
      "kvvvvkvk",
      "kvvvkvvk",
      "kvvvkvvk",
      "kkkkvkkk",
      "kVVVkVVk",
      "kVVVVVVk",
      "kkkkkkkk",
    ],
  }),

  cracked_case: prop(16, 20, 2, {
    base: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kTxxxkxxxxxxxxTk",
      "kTxxxxkxxxkxxxTk",
      "kTxxxxxkxkxxxxTk",
      "kTxxxxxxkxxxxxTk",
      "kTxxxxxkxkxxxxTk",
      "kTxxxxkxxxkxxxTk",
      "kTxxxkxxxxxkxxTk",
      "kTxxxxxxxxxxxxTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "kmttttttttttttmk",
      "kTttttttttttttTk",
      "kTtk........ktTk",
      "kTtk........ktTk",
      "kTTk........kTTk",
      "kkkk........kkkk",
    ],
    open: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kTTTTTTTTTTTTTTk",
      "kTk..........kTk",
      "kT............Tk",
      "kT............Tk",
      "kT....yyyy....Tk",
      "kT...yWWWWy...Tk",
      "kT....yyyy....Tk",
      "kT............Tk",
      "kTk..........kTk",
      "kTTTTTTTTTTTTTTk",
      "kkkkkkkkkkkkkkkk",
      "kmttttttttttttmk",
      "kTttttttttttttTk",
      "kTtk........ktTk",
      "kTtk........ktTk",
      "kTTk........kTTk",
      "kkkk........kkkk",
    ],
  }),

  // --- the Shot-Firer's glove, on its label ------------------------------------------------
  page_explosion: prop(16, 16, 2, {
    base: [
      "................",
      "....kkkkkk......",
      "...kQQQQQQk.....",
      "..kQqqqqqQk.....",
      "..kQqwwqqQk.....",
      "..kQqwwqqqk.....",
      "..kQqqqqqqk.....",
      "...kQQqqQk......",
      "....kkQQkk......",
      "................",
      ...PLINTH_16.slice(0, 5),
      "................",
    ],
    on: [
      "................",
      "....kkkkkk......",
      "...kQQQQQQk.....",
      "..kQqqqqqQk.....",
      "..kQqxxqqQk.....",
      "..kQqxxqqqk.....",
      "..kQqqqqqqk.....",
      "...kQQqqQk......",
      "....kkQQkk......",
      "................",
      ...PLINTH_16.slice(0, 5),
      "................",
    ],
  }),
};

export default sheet;
