// Butterfly Forest's cast. The butterfly and the moth are the same wings in different weather.
// The Collector is a man in a good coat with a net. The Emperor is the same shape as a moth
// and as wide as a dinner plate.

import type { Palette, SpriteSheet, SpriteSrc } from "@/art/types";
import { PAL } from "@/art/types";

const PX: Palette = {
  ...PAL,
  f: "#f4a0c0", // wing, warm
  F: "#c06890", // wing shade
  c: "#d8dcf0", // wing, cold
  C: "#9098c0", // wing shade, cold
  q: "#fff0bc", // pale, lit
  v: "#3a4a2c", // waxed coat green
  V: "#22301a", // coat shade
};

function unit(w: number, h: number, frames: Record<string, string[]>): SpriteSrc {
  return { w, h, ax: Math.floor(w / 2), ay: h - 2, palette: PX, frames };
}

const BUTTERFLY_FRAMES: Record<string, string[]> = {
  down: [
    "............",
    ".kk......kk.",
    "kffk....kffk",
    "kfFfkkkkfFfk",
    "kffkkyykkffk",
    ".kkkkyykkkk.",
    "...kkkkkk...",
    "....k..k....",
    "............",
    "............",
  ],
  down2: [
    "............",
    "....kkkk....",
    "...kffffk...",
    "..kfFkkFfk..",
    "..kffkykfk..",
    "...kkkyykk..",
    "....kkkkk...",
    "....k..k....",
    "............",
    "............",
  ],
  up: [
    "............",
    ".kk......kk.",
    "kffk....kffk",
    "kfFfkkkkfFfk",
    "kffkkYYkkffk",
    ".kkkkYYkkkk.",
    "...kkkkkk...",
    "....k..k....",
    "............",
    "............",
  ],
  side: [
    "............",
    "....kk......",
    "...kffk.....",
    "..kfFfk.....",
    "..kffkkyk...",
    "...kkkkyk...",
    "....kkkk....",
    ".....k.k....",
    "............",
    "............",
  ],
};

const MOTH_FRAMES: Record<string, string[]> = {
  down: [
    "............",
    ".kk......kk.",
    "kcck....kcck",
    "kcCckkkkcCck",
    "kcckkWWkkcck",
    ".kkkkWWkkkk.",
    "...kkkkkk...",
    "....k..k....",
    "............",
    "............",
  ],
  up: [
    "............",
    ".kk......kk.",
    "kcck....kcck",
    "kcCckkkkcCck",
    "kcckkggkkcck",
    ".kkkkggkkkk.",
    "...kkkkkk...",
    "....k..k....",
    "............",
    "............",
  ],
  side: [
    "............",
    "....kk......",
    "...kcck.....",
    "..kcCck.....",
    "..kcckkWk...",
    "...kkkkWk...",
    "....kkkk....",
    ".....k.k....",
    "............",
    "............",
  ],
};

const sheet: SpriteSheet = {
  butterfly: unit(12, 10, BUTTERFLY_FRAMES),
  moth: unit(12, 10, MOTH_FRAMES),

  collector: unit(16, 20, {
    down: [
      "................",
      ".....kkkkkk.....",
      "....kTTTTTTk....",
      "...kkkkkkkkkk...",
      "....kssssssk....",
      "....ksKssKsk....",
      "....kssssssk....",
      ".....kkkkkk.....",
      "...kvvvvvvvvk...",
      "..kvvvvvvvvvvk..",
      "..kvvVvvvvVvvk..",
      "..kvvvvvvvvvvk..",
      "..kvvvvvvvvvvk..",
      "...kvvvvvvvvk...",
      "...kVVVVVVVVk...",
      "....kGGkkGGk....",
      "....kGGkkGGk....",
      "....kkk..kkk....",
      "................",
      "................",
    ],
    up: [
      "................",
      ".....kkkkkk.....",
      "....kTTTTTTk....",
      "...kkkkkkkkkk...",
      "....kTTTTTTk....",
      "....kTTTTTTk....",
      "....kTTTTTTk....",
      ".....kkkkkk.....",
      "...kvvvvvvvvk...",
      "..kvvvvvvvvvvk..",
      "..kvvvvvvvvvvk..",
      "..kvvvvvvvvvvk..",
      "..kvvvvvvvvvvk..",
      "...kvvvvvvvvk...",
      "...kVVVVVVVVk...",
      "....kGGkkGGk....",
      "....kGGkkGGk....",
      "....kkk..kkk....",
      "................",
      "................",
    ],
    side: [
      "................",
      ".....kkkkkk.....",
      "....kTTTTTTkk...",
      "...kkkkkkkkkkk..",
      "....kssssskk....",
      "....ksKsssk.....",
      "....ksssssk.....",
      ".....kkkkkk.....",
      "...kvvvvvvvk....",
      "..kvvvvvvvvk.kk.",
      "..kvvVvvvvvkkwk.",
      "..kvvvvvvvvkkwk.",
      "..kvvvvvvvvk.kk.",
      "...kvvvvvvvk....",
      "...kVVVVVVVk....",
      "....kGGkGGk.....",
      "....kGGkGGk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  }),

  emperor: unit(24, 18, {
    down: [
      "........................",
      "..kkk..............kkk..",
      ".kWWWkk..kkkk..kkWWWWk..",
      "kWWWWWWkkWqqWkkWWWWWWWk.",
      "kWWqWWWkkWqqWkkWWWqWWWk.",
      "kWWWWWWkkWWWWkkWWWWWWWk.",
      ".kWWWWWkkWrrWkkWWWWWWk..",
      "..kWWWWkkWWWWkkWWWWWk...",
      "...kWWWkkWWWWkkWWWWk....",
      "....kWWkkWWWWkkWWWk.....",
      ".....kkkkWWWWkkkkk......",
      "........kWWWWk..........",
      "........kWWWWk..........",
      ".........kWWk...........",
      ".........kkkk...........",
      "..........kk............",
      "........................",
      "........................",
    ],
    up: [
      "........................",
      "..kkk..............kkk..",
      ".kWWWkk..kkkk..kkWWWWk..",
      "kWWWWWWkkWWWWkkWWWWWWWk.",
      "kWWgWWWkkWWWWkkWWWgWWWk.",
      "kWWWWWWkkWWWWkkWWWWWWWk.",
      ".kWWWWWkkWWWWkkWWWWWWk..",
      "..kWWWWkkWWWWkkWWWWWk...",
      "...kWWWkkWWWWkkWWWWk....",
      "....kWWkkWWWWkkWWWk.....",
      ".....kkkkWWWWkkkkk......",
      "........kWWWWk..........",
      "........kWWWWk..........",
      ".........kWWk...........",
      ".........kkkk...........",
      "..........kk............",
      "........................",
      "........................",
    ],
    side: [
      "........................",
      ".......kkk..............",
      "......kWWWkk............",
      ".....kWWWWWWk...........",
      ".....kWWqWWWk...........",
      "......kWWWWWk...........",
      "......kWWWWkk...........",
      ".......kWWWkkkk.........",
      ".......kWWWWkrk.........",
      "........kWWWkkk.........",
      "........kWWWk...........",
      ".........kWWk...........",
      ".........kWWk...........",
      "..........kk............",
      "..........kk............",
      "........................",
      "........................",
      "........................",
    ],
  }),
};

export default sheet;
