[package]
name = "jane-app"
description = "The SDL2 game binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
jane-core.workspace = true
jane-data.workspace = true
jane-sim.workspace = true
jane-net.workspace = true
jane-present.workspace = true
jane-render-soft.workspace = true
jane-render-gl2.workspace = true
jane-render-wgpu.workspace = true
sdl2.workspace = true

[lints]
workspace = true
